### ISSUE TITLE
在阿里小程序中使用组件引用组件会报错

### ISSUE THREAD

**Issue by wangzhenggui** [mallfoundry/taroify#1]
原因： 组件中lodash使用方式问题,作者是否可以使用 import isBoolean from "lodash/isBoolean" 这种写法；要不然阿里小程序下使用会有问题

**Comment by tgioer** [comment]
具体是什么错误？我在 taro 中使用了 `babel-plugin-lodash` 插件。请把问题详细的描述下，然后研究下如何解决。
