### ISSUE TITLE
TreeSelect 和 PopUp组件有报错

### ISSUE THREAD

**Issue by Jesse-Fan** [mallfoundry/taroify#107]
taro版本： 3.3.14
nervjs 渲染

TreeSelect 和 PopUp组件有报错： TypeError: Cannot read properties of undefined (reading 'props')

**Comment by tgioer** [comment]
使用 react 渲染有问题吗？

**Comment by Jesse-Fan** [comment]
> 使用 react 渲染有问题吗？

没有尝试 但是在nervjs有报错

**Comment by tgioer** [comment]
> > 使用 react 渲染有问题吗？
> 
> 没有尝试 但是在nervjs有报错

目前 taroify 主要支持 react 对 nervjs 和 vue3 没有做测试
