### ISSUE TITLE
Field 输入框 如何配合form使用？

### ISSUE THREAD

**Issue by hooliy** [mallfoundry/taroify#114]
Field 输入框 如何配合form使用？难道只能通过onChange 来 setState 吗？

**Comment by tgioer** [comment]
目前还没有 Form 组件，后续会有。

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/issues/118

**Comment by jianhao2010303** [comment]
+1

**Comment by YC725968** [comment]
Form大家都需要啊

**Comment by tgioer** [comment]
> Form大家都需要啊

在路上了
