### ISSUE TITLE
根本安装不上，淘宝镜像和 npmjs 的最新版本同步有延迟

### ISSUE THREAD

**Issue by skyliwq** [mallfoundry/taroify#119]
ERR! notarget No matching version found for @taroify/hooks@^0.0.18-alpha.3.

**Comment by tgioer** [comment]
国内的淘宝镜像有更新延迟，现在更新了。
如果发现 npmmirror 和 npmjs 的最新版本不同步可以手动调用以下链接：

- https://npmmirror.com/sync/@taroify/hooks
- https://npmmirror.com/sync/@taroify/icons
- https://npmmirror.com/sync/@taroify/core
