### ISSUE TITLE
真机调试Swpier组件报错

### ISSUE THREAD

**Issue by Qinruiy** [mallfoundry/taroify#120]
https://github.com/mallfoundry/taroify/blob/202561ef997efd96a4fbb3bb489114098d2325ec/packages/core/src/utils/dom/scroll.ts#L26

Cannot destructure property 'overflowY' of '(intermediate value)' as it is null.

**Comment by tgioer** [comment]
Swiper 组件近期会重构，你可以先使用 taro 的  Swiper

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/137
