### ISSUE TITLE
上传组件示例语法错误

### ISSUE THREAD

**Issue by Ericxiaoshuang** [mallfoundry/taroify#141]
https://taroify.gitee.io/taroify.com/components/uploader/
```
import Taro from "@tarojs/taro"
```
没有 @符号
```
Taro.chooseImage 
```
Taro.没有写,没有引入
import Taro from "@tarojs/taro";

**Comment by tgioer** [comment]
我是这样引入的

import { chooseImage } from "@tarojs/taro"

https://github.com/mallfoundry/taroify/blob/main/packages/demo/src/pages/form/uploader/index.tsx#L4

示例中基本上都没有写 import*
