### ISSUE TITLE
List 组件，onload会触发2-3次

### ISSUE THREAD

**Issue by crotchetCode** [mallfoundry/taroify#142]
验证方式：文档list模块，把setTimeout改成200ms左右（模拟真实端到端时间），onload会随机触发数次。
影响：会触发数次请求，造成无用请求。

**Comment by tgioer** [comment]
是好了吗？

**Comment by crotchetCode** [comment]
> 

是因为数据不够一屏导致的多次请求，我通过hooks 页码依赖解决了多次请求问题

**Comment by tgioer** [comment]
> > 
> 
> 是因为数据不够一屏导致的多次请求，我通过hooks 页码依赖解决了多次请求问题

有 hasMore 属性，数据不够可以设置 hasMore 属性。
