### ISSUE TITLE
Tabbar.TabItem的icon无效 引入报错

### ISSUE THREAD

**Issue by lppoi** [mallfoundry/taroify#144]
**TypeError**: Cannot read property 'props' of undefined
Unhandled promise rejection TypeError: Cannot read property 'props' of undefined
图标放外面能显示，放icon有的能显示有的报错(只试了例子里面的四个三个报错 只有<FriendsOutlined />能显示)

**Comment by tgioer** [comment]
哪些不能显示?

**Comment by tgioer** [comment]
是如何使用的？有代码吗？

**Comment by lppoi** [comment]
抱歉 不怎么看邮箱

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tgioer** [comment]
这个是github 推送的，如果还不行就在 issue 上讨论。



At 2021-12-04 08:13:23, "lppoi" ***@***.***> wrote:

抱歉 不怎么看邮箱

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tgioer** [comment]
@lppoi 那目前是可以了还是不行？

**Comment by lppoi** [comment]
嗯嗯好的  目前还是不行的  目前我用的是t那个nerv框架构建的taro

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tgioer** [comment]
你需要使用 react 框架
