### ISSUE TITLE
cell的icon显示图片为字符串

### ISSUE THREAD

**Issue by LGinC** [mallfoundry/taroify#157]
```html
<Cell size='large' icon='https://pic.rmb.bdstatic.com/bjh/597a358e3562e976947799aedb16dca9.png'>{this.state.nickName}</Cell>
```
![image](https://user-images.githubusercontent.com/15363011/144544177-00435bd6-c5a5-4693-89f2-fd588136fd7f.png)
文档上没有如何配置图片链接

**Comment by tgioer** [comment]
不支持字符串，你可以使用 <Image /> 组件
