### ISSUE TITLE
tabs 组件

### ISSUE THREAD

**Issue by Brain777777** [mallfoundry/taroify#161]
在使用 tabs 组件开启标签栏滚动时，在真机上会出现抖动问题。   
taro: 3.3.15
taroify:0.0.19-alpha.0
platform: Iphone 11

**Comment by tgioer** [comment]
能提供一个 repo 吗？或者录屏

**Comment by Brain777777** [comment]
https://user-images.githubusercontent.com/35163869/144704890-19d15b37-6e50-479a-ae98-48b73170214d.mp4

**Comment by tgioer** [comment]
我找了个ios手机试了下没问题，能不能提供个代码库我复现一下。

**Comment by Brain777777** [comment]
好像找到什么原因了，如果在组件内部声明了 useCountDown hook 即使没有引用返回的变量就会导致 tabs 切换的时候在真机上抖动，我本以为是我使用了其他什么东西导致了，但是我新建一个全新的项目使用同样的代码在真机上都会出现这个情况。
<img width="525" alt="1638626860(1)" src="https://user-images.githubusercontent.com/35163869/144712476-93e24621-ec04-425f-9398-1415b234d944.png">

**Comment by tgioer** [comment]
等我测试一下，目前可以把 useCountDown 包装成一个独立组件，让他局部渲染试试。

**Comment by Brain777777** [comment]
确实 useCountDown 必须要在一个独立的组件中使用才可以，因为 useCountDown 内部开启了 autoStart 后会一直触发 State 操作，而放在页面级组件的话频繁触发 State 导致页面组件一直在刷新，直到倒计时结束才会停止 State 更新，所以 tabs 切换的时候在真机上导致抖动。其实 CountDown 组件这样把 useCountDown  hook 暴露在外部组合使用其实对与开发者来说不是特别的友好，还建议把 useCountDown 绑定在 CountDown 组件内部，然后手动方法可以通过 ref 转发出来调用。

**Comment by tgioer** [comment]
后面争取合并在一起。
