### ISSUE TITLE
Button的loading不显示

### ISSUE THREAD

**Issue by ykrank** [mallfoundry/taroify#164]
v0.0.19-alpha.3 版本，loading状态时不显示loading圈

`<Button color="success" loading={{ type: "spinner" }} style={{color:"#fff"}}>12</Button>`

![image](https://user-images.githubusercontent.com/6565673/145140241-701b1d18-436e-4a47-9889-9028d4794b0c.png)

**Comment by ykrank** [comment]
taro: 3.3.16

**Comment by ykrank** [comment]
单独的Loading也不显示

**Comment by tgioer** [comment]
等我测试下

**Comment by tgioer** [comment]
可以升级到 '0.0.20-alpha.0' 再试试。

**Comment by ykrank** [comment]
知道原因了，原来的按需引入方式有问题，导致animation没被import。
原来文档里的
`[
      "import",
      {
        "libraryName": "@taroify/core",
        "libraryDirectory": "",
        "style": (name) => `${name}/index.scss`,
      },
      "@taroify/core",
    ],`

现在的
`
[
      "import",
      {
        libraryName: "@taroify/core",
        libraryDirectory: "",
        style: true,
      },
      "@taroify/core",
    ],
`

**Comment by tgioer** [comment]
👌🏻
