### ISSUE TITLE
设置designWidth: 375, ui组件倍数大小

### ISSUE THREAD

**Issue by Ericxiaoshuang** [mallfoundry/taroify#173]
// designWidth: 750,
  designWidth: 375,

  deviceRatio: {
    640: 2.34 / 2,
    750: 1,
    828: 1.81 / 2,
    375: 2 / 1,
  },

**Comment by Ericxiaoshuang** [comment]
补充:以375px设计稿 在微信小程序显示为2倍效果,有点大

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/174

**Comment by tgioer** [comment]
config/index.js
```js
module.exports = {
  // ...
  sass: {
    data: "$hd: 1;"
  }
}
```
