### ISSUE TITLE
【BUG】List组件的immediateCheck属性无效，ts提示未定义且不起作用

### ISSUE THREAD

**Issue by FengFuLiu** [mallfoundry/taroify#178]

**Comment by tgioer** [comment]
这个属性没有加，一会加上。

**Comment by aaaaahua** [comment]
> 这个属性没有加，一会加上。

好的，谢谢

**Comment by tgioer** [comment]
突然想起来，你需要 immediateCheck 做什么？

**Comment by FengFuLiu** [comment]
> 突然想起来，你需要 immediateCheck 做什么？

> 为什么 List 初始化后会立即触发 load 事件？
List 初始化后会触发一次 load 事件，用于加载第一屏的数据，这个特性可以通过 immediateCheck 属性关闭。

主要是因为如上原因

**Comment by tgioer** [comment]
这个文档是复制的 vant，下个版本会改正。可以在初次先设置 `hasMore={false}` 试一试。

**Comment by FengFuLiu** [comment]
> 这个文档是复制的 vant，下个版本会改正。可以在初次先设置 `hasMore={false}` 试一试。

👌
