### ISSUE TITLE
<Field></Field>类型password在h5包含2个warning

### ISSUE THREAD

**Issue by jianhao2010303** [mallfoundry/taroify#203]
1. password 应该包含在form表单
2. Input elements should have autocomplete attributes

3. colon文档上有描述，但是应用时报错，提示没有。

**Comment by tgioer** [comment]
近期会对 Field 进行重构，预计三四天就能发布。

**Comment by jianhao2010303** [comment]
期待ing。急需要

**Comment by tgioer** [comment]
这个是 Taro 对组件进行封装的问题没办法解决。可以给 taro 提交个 issue
