### ISSUE TITLE
PullRefresh 在微信小程序 iOS 存在过渡动画效果卡顿问题

### ISSUE THREAD

**Issue by tgioer** [mallfoundry/taroify#207]

**Comment by tgioer** [comment]
微信小程序的过渡效果、动画效果在 iOS 手机上可能会存在各种小问题，这种问题不是组件库本身的问题，可能是是微信 iOS 小程序的问题，可以通过杀死微信 App 进程在试试。

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/issues/251

**Comment by 553082694** [comment]
卡顿解决了吗？我目前0.0.27-alpha.0的版本，下拉卡的要死了！！！

> #251
