### ISSUE TITLE
和taro的mini-css-extract-plugin有兼容问题

### ISSUE THREAD

**Issue by ykrank** [mallfoundry/taroify#21]
版本： 
@taroify/core@0.0.12-alpha.12
mini-css-extract-plugin@0.8.0

`WARNING in chunk common [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/@tarojs/mini-runner/node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/@tarojs/mini-runner/node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/@tarojs/mini-runner/node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroify/core/pull-refresh/index.scss
 * css ./node_modules/@tarojs/mini-runner/node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/@tarojs/mini-runner/node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/@tarojs/mini-runner/node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroify/core/row/index.scss

WARNING in chunk common [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/@tarojs/mini-runner/node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/@tarojs/mini-runner/node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/@tarojs/mini-runner/node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroify/core/cell/index.scss
 * css ./node_modules/@tarojs/mini-runner/node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/@tarojs/mini-runner/node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/@tarojs/mini-runner/node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroify/core/row/index.scss`

**Comment by tgioer** [comment]
taro 的版本是多少？

**Comment by ykrank** [comment]
Taro v3.3.8

**Comment by ykrank** [comment]
升级到最新的3.3.9一样的错误

**Comment by tgioer** [comment]
是使用了 Row, Cell, PullRefresh 这三个组件出现的问题吗？

**Comment by ykrank** [comment]
是的
import { Button, Row, Cell, Col, Image, PullRefresh } from "@taroify/core";

**Comment by tgioer** [comment]
这个问题是这样出现的，我感觉和 按需加载 插件有关系。
比如有两个页面: A.tsx 和 B.tsx

在 A.tsx 文件中：
````
function A() {
  return (
    <>
      <Cell />
      <Toast />
    </>
  )
}
````


在 B.tsx 文件中：
````
function A() {
  return (
    <>
      <Toast />
      <Cell />
    </>
  )
}
````

这两个组件在不同页面使用中正好反过来就会出现这个问题。

**Comment by tgioer** [comment]
同时 和导入的顺序没有关系，和使用的顺序有关系

**Comment by tgioer** [comment]
这里有一个解决方案
https://github.com/NervJS/taro/issues/7907#issuecomment-727678881
