### ISSUE TITLE
DatetimePicker 新增 date-minute 类型（年月日时分）

### ISSUE THREAD

**Issue by jianhao2010303** [mallfoundry/taroify#211]
DatetimePicker能否有年月日小时分的类型，会议场景中一般不关心秒。

**Comment by tgioer** [comment]
有一个 fields 属性，fields={[year month day hour]}，这样试试

**Comment by tgioer** [comment]
或者 type = date-hour

**Comment by tgioer** [comment]
目前好像不支持 年月日时分，下个版本会考虑。

**Comment by jianhao2010303** [comment]
好的。谢谢。这个在会议场景非常非常重要

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/227
