### ISSUE TITLE
PullRefresh 结合echarts错位

### ISSUE THREAD

**Issue by lizhongkun** [mallfoundry/taroify#213]
下拉松手，echarts图错位

![正常](https://user-images.githubusercontent.com/41602501/147433909-546e13ca-fe31-4b8c-a05d-e69cbd08628e.jpg)
![错位](https://user-images.githubusercontent.com/41602501/147433921-d1dd7b0d-e2ca-4935-9653-18ac10072aa1.jpg)

**Comment by tgioer** [comment]
可能要下拉完以后，重新渲染下 echarts

**Comment by lizhongkun** [comment]
@tgioer  "释放即可刷新" 到 "加载中" 会出现瞬间，事件结束后会恢复正常

**Comment by tgioer** [comment]
@lizhongkun 这是安卓手机吗？问题解决了吗？

**Comment by lizhongkun** [comment]
@tgioer  ios14.8.1，目前是采用小程序下拉刷新
