### ISSUE TITLE
Switch组件在小程序中不适配

### ISSUE THREAD

**Issue by jianhao2010303** [mallfoundry/taroify#214]
1、结合cell组件使用中，设置size = 24，在iphoneX中查看，样式已飞。

**Comment by tgioer** [comment]
![1640685378(1)](https://user-images.githubusercontent.com/18252854/147553984-4ea3167b-c84f-4849-8f80-1c77c8762d60.png)

```tsx
<Cell title="Switch">
   <Switch size={24} />
</Cell>
```

我测试没有问题。

**Comment by jianhao2010303** [comment]
不好意思，<Cell align="center" title="标题" rightIcon={<Switch size="24" />} /> 这样会乱。

**Comment by jianhao2010303** [comment]
rightIcon 会乱。

**Comment by jianhao2010303** [comment]
已改成你代码的方式，显示正常。

**Comment by tgioer** [comment]
![1640686549](https://user-images.githubusercontent.com/18252854/147555904-2bd34cf8-da5b-4e98-bd1c-bbc8298f6192.png)

```tsx
<Cell align="center" title="标题" rightIcon>
  <Switch size={24} />
</Cell>
```

没啥问题？

**Comment by jianhao2010303** [comment]
<Cell align="center" title="标题" rightIcon={<Switch size="24" />} />

**Comment by jianhao2010303** [comment]
<Cell align="center" title="标题" rightIcon={\<Switch size="24" \/>\} \/>

**Comment by tgioer** [comment]
哪里的文档？

**Comment by jianhao2010303** [comment]
https://taroify.gitee.io/taroify.com/components/switch/

**Comment by tgioer** [comment]
![1640686906(1)](https://user-images.githubusercontent.com/18252854/147556377-2008b5ab-9fc3-4d22-9051-9ea7e67ce50d.png)

```tsx
<Cell align="center" title="标题" rightIcon={<Switch size="24" />} />
``

没有问题啊

**Comment by tgioer** [comment]
你那是什么效果？

**Comment by jianhao2010303** [comment]
![image](https://user-images.githubusercontent.com/22093101/147556548-742d9358-9184-4d73-b2e4-d86ea91be12e.png)

**Comment by tgioer** [comment]
你把代码上传下，我看看。你是不是修改样式了？

**Comment by tgioer** [comment]
比如图标的大小，没有做 scope

**Comment by jianhao2010303** [comment]
改成了放在children 中样式。
![image](https://user-images.githubusercontent.com/22093101/147556801-a529d5e1-d01b-4a9b-8640-1b02862f42dc.png)

**Comment by jianhao2010303** [comment]
代码走后台服务了。。。有逻辑，在本地开发。

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/225
