### ISSUE TITLE
Swiper滑动过程中很卡

### ISSUE THREAD

**Issue by luyang12138** [mallfoundry/taroify#215]
滑动【过程中】出现明显卡顿；
机器：iphone12

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/issues/216

**Comment by luyang12138** [comment]
我的是15.1，tabs的swiper切换过程中仍然不流畅。
用vantui试了下，发现是可以流畅的。
希望作者能查一下原因。

**Comment by tgioer** [comment]
我用的 iOS 不可以，你可以录个视频吗？

**Comment by luyang12138** [comment]
在这回复一下，在切换时如果慢动作，a和b假设都是灰色背景（而不是白色），并且都已经加载过，由a滑动到b时，b会先出现白色背景完且内容全无，等滑动操作完成跳转到b了，b的背景才变为正常，并且出现b本来的内容。我的猜测是，难道是滑动之后才把b的内容加载进去嘛？这样是不是有问题？

**Comment by luyang12138** [comment]
由a滑动到b时，b会先出现白色背景完且内容全无，等滑动操作完成跳转到b了，b的背景才变为正常，并且出现b本来的内容。这个感觉可能是造成不流畅的原因。安卓机我也试了，也同样存在

**Comment by tgioer** [comment]
你这个是 tabs 还是 swiper 遇到的问题？

**Comment by luyang12138** [comment]
sorry，tabs的，我以为你的tabs是基于swiper实现的

**Comment by tgioer** [comment]
滑动是基于 swiper 实现

**Comment by tgioer** [comment]
你可以不可以在真机上做个测试。
微信小程序的代码：https://developers.weixin.qq.com/s/nMm7f5mU7zwK

你真机运行下，看看卡顿吗？

@luyang12138

**Comment by mefengl** [comment]
> 

同样的问题，我后来换用Taro原生组件。

**Comment by mefengl** [comment]
和 @luyang12138 同样的问题，即一周期后会首个item白屏，换用Taro原生Swiper没有问题。

**Comment by gooddaddy** [comment]
@tgioer 这bug修复了没有？这bug还是存在，或者有没有临时的解决方案

**Comment by mefengl** [comment]
@gooddaddy 最佳实践是，有Taro官方滑动组件，用官方组件
比如，Swiper
https://taro-docs.jd.com/taro/docs/components/viewContainer/swiper
