### ISSUE TITLE
Tabs可以添加lazyLoad嘛

### ISSUE THREAD

**Issue by luyang12138** [mallfoundry/taroify#217]

**Comment by tgioer** [comment]
不是有 lazyRender 吗？

**Comment by luyang12138** [comment]
api文档里没有，而且刚刚试了下，似乎并没有lazy啊！

**Comment by tgioer** [comment]
![1640701103(1)](https://user-images.githubusercontent.com/18252854/147575453-edda94ca-80cd-414a-b899-cd3095b7e550.png)

```tsx
<Tabs lazyRender>
  <Tabs.TabPane title="标签 1">内容 1</Tabs.TabPane>
  <Tabs.TabPane title="标签 2">内容 2</Tabs.TabPane>
  <Tabs.TabPane title="标签 3">内容 3</Tabs.TabPane>
  <Tabs.TabPane title="标签 4">内容 4</Tabs.TabPane>
</Tabs>
```

可以啊

**Comment by luyang12138** [comment]
我比你多添加了 swipeable，你试试在添加swipeable的情况下还能不能lazyload

**Comment by luyang12138** [comment]
我试了下，不加 swipeable是可以的，加了之后就不行。
而且总体感觉swiper不流畅，在切换时如果慢动作，a和b假设都是灰色背景（而不是白色），并且都已经加载过，由a滑动到b时，b会先出现白色背景完且内容全无，等滑动操作完成跳转到b了，b的背景才变为正常，并且出现b本来的内容。我的猜测是，难道是滑动之后才把b的内容加载进去嘛？这样是不是有问题？

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/218

**Comment by tgioer** [comment]
> 

现在确实是等滑动到 active 时，才渲染内容的。

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/219

swipeable & lazyRender 滑动背景的问题已解决
