### ISSUE TITLE
calendar 日历渲染较慢，有明显的卡顿，滑到最末的日期，会产生击穿，会滑动遮罩下的 list

### ISSUE THREAD

**Issue by idujiawei** [mallfoundry/taroify#237]

**Comment by tgioer** [comment]
在微信小程序中，可以使用 CustomWrapper 包住组件

**Comment by tgioer** [comment]
![1641378688(1)](https://user-images.githubusercontent.com/18252854/148202911-d855adda-8d7c-411d-aee5-f6119e43f6de.png)

**Comment by idujiawei** [comment]
使用了 CustomWrapper ，设置默认日期为当前日期，最小日期为2020-01-01，打开日历，停留在2020-01-01，而不是滚动到默认日期的位置，滑动击穿的问题有什么解决方案吗

**Comment by idujiawei** [comment]
滑动击穿添加 catchMove 属性解决了

**Comment by tgioer** [comment]
怎么操作的？

**Comment by idujiawei** [comment]
当前问题：使用 CustomWrapper 后，打开弹层，日历停在 2020-01月，并没有滚动到 2022-01，查看渲染后的  scroll-top=0

打开弹窗，实际效果
![image](https://user-images.githubusercontent.com/20924706/148211894-89698b89-51e8-4df0-a673-4b1a218c85b7.png)


![image](https://user-images.githubusercontent.com/20924706/148211715-c1c45916-f671-4416-9a7d-53ff7e1a9aaa.png)



```js
// minDate 2020-01-01
// currentDay 默认当前日期 ，如：2022-01-05
// maxDate 当前日期 +1 ，如：2022-01-06

<CustomWrapper>
  <Popup catchMove style={{ height: '80%' }} rounded placement='bottom' open={open} onClose={setOpen}>
    <Calendar
      catchMove
      min={new Date(minDate)}
      max={new Date(maxDate)}
      value={new Date(currentDay)}
      onConfirm={handleConfirm}
    />
  </Popup>
</CustomWrapper>
```

**Comment by tgioer** [comment]
在真实环境中， 不要直接给 min,max,value 设置变量。

尽量使用：`const [minDate] = useState(new Date())` 这种方式。

catchMove 我一会更新下文档。
