### ISSUE TITLE
希望Picker组件 onConfirm 可以返回option的参数

### ISSUE THREAD

**Issue by idujiawei** [mallfoundry/taroify#239]
添加了自定义属性来存放数据

```js
<Picker.Column>
  {_.map(data, item => {
    const key = _.get(item, valueKey);
    const labelStr = formatLabel(item);

    return (<Picker.Option key={key} value={key} data-option={item}>{labelStr}</Picker.Option>)
  })}
</Picker.Column>
```

通过 `console.log(valueOptionsRef.current)` 可以看到选中后，Option 上的属性都能获取到
![image](https://user-images.githubusercontent.com/20924706/148321564-2d5b3b76-cf68-476d-9337-f1249823eae9.png)

希望 onConfirm 回调，可以新增 options 参数，用来返回 valueOptionsRef.current 的内容，

现在选中后，想获取选中的 option 的数据，还得通过遍历整个数组来获取，很不方便

**Comment by tgioer** [comment]
onConfirm?(values: any | any[], options: PickerOptionObject | PickerOptionObject[]): void

你试试第二个形参。

**Comment by idujiawei** [comment]
第二个只返回了 index、value，没有其他的

**Comment by idujiawei** [comment]
实际我需要自定义属性里面的数据，如：data-option 里的

**Comment by tgioer** [comment]
👌

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/242

**Comment by tgioer** [comment]
https://taroify.gitee.io/taroify.com/changelog/#v0024-alpha0
