### ISSUE TITLE
DatetimePicker 2月有31号

### ISSUE THREAD

**Issue by idujiawei** [mallfoundry/taroify#240]
![image](https://user-images.githubusercontent.com/20924706/148484167-c387818c-6ea6-4a5f-9482-9bd6cca51f6a.png)

**Comment by tgioer** [comment]
你先设置 value 试试

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/254

**Comment by tgioer** [comment]
https://taroify.gitee.io/taroify.com/changelog/#v0024-alpha0
