### ISSUE TITLE
Uploader 丢失 removable 属性

### ISSUE THREAD

**Issue by mtiger95** [mallfoundry/taroify#243]
![1641649784(1)](https://user-images.githubusercontent.com/23418622/148646669-20222480-aa2f-41d2-b8f3-3128ee4c9670.png)
![914e74412b4bad5760e6fbe486df06f](https://user-images.githubusercontent.com/23418622/148646680-e64adad3-f371-4e60-9176-2d36d847137e.png)
![f4d10559b1aadf4fe15a283f0889614](https://user-images.githubusercontent.com/23418622/148646696-05edaedd-1633-47a9-b6ad-27901d6944dc.png)

**Comment by tgioer** [comment]
文档应该有问题，这个remove应该在 Uploader.Image 组件上

https://github.com/mallfoundry/taroify/blob/main/packages/core/src/uploader/uploader-image.tsx#L17

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/256

**Comment by tgioer** [comment]
https://taroify.gitee.io/taroify.com/changelog/#v0024-alpha0
