### ISSUE TITLE
custom-tab-bar 报错

### ISSUE THREAD

**Issue by EdivenH** [mallfoundry/taroify#246]
Unhandled promise rejection TypeError: Cannot read property 'height' of null
    at .._.._.._.._packages_core_src_hooks_use-height.ts:9
    at WASubContext.js?t=wechat&s=1641883010668&v=2.21.2:2
    at n (WASubContext.js?t=wechat&s=1641883010668&v=2.21.2:2)(env: Windows,mp,1.05.2111300; lib: 2.21.2)

定位文件 ~@taroify/hooks/use-height.js
_ref 为null

**Comment by tgioer** [comment]
Tabbar 不支持 custom-tab-bar

**Comment by Vinsurs** [comment]
> Tabbar 不支持 custom-tab-bar

你好 use-height.js能否做到仅当传了placeholder才去执行这里的placeholder占位计算; 我看目前是不管placeholder prop传没传都是会执行useHeight；我目前没使用placeholder 但是报这个错挺难看的😁

**Comment by Vinsurs** [comment]
> Tabbar 不支持 custom-tab-bar

你好 use-height.js能否做到仅当传了placeholder才去执行这里的placeholder占位计算; 我看目前是不管placeholder prop传没传都是会执行useHeight；我目前没使用placeholder 但是报这个错挺难看的😁

**Comment by tgioer** [comment]
> > Tabbar 不支持 custom-tab-bar
> 
> 你好 use-height.js能否做到仅当传了placeholder才去执行这里的placeholder占位计算; 我看目前是不管placeholder prop传没传都是会执行useHeight；我目前没使用placeholder 但是报这个错挺难看的😁

一会我研究下

**Comment by tgioer** [comment]
在 v0.0.26-alpha.1 版本 `useHeight` 的问题已修复。

同时需要在 `custom-tab-bar/index.scss` 引入一下样式：
```tsx
@import "~@taroify/icons/index.scss";
@import "~@taroify/core/badge/index.scss";
@import "~@taroify/core/tabbar/index.scss";
```

**Comment by Toshinaki** [comment]
> Tabbar 不支持 custom-tab-bar

不支持自定义tabbar吗？https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html
那这个组件的意义何在？
