### ISSUE TITLE
PullRefresh 真机调试无效，模拟器测试正常

### ISSUE THREAD

**Issue by Thresh17** [mallfoundry/taroify#251]
![7b1da8615829dbe4d961ae5b89ea181](https://user-images.githubusercontent.com/30347913/149054045-0668404b-6c1a-4535-a658-d9c38800ef84.jpg)
PullRefresh下拉刷新组件在真机上下拉没有加载动画，也不会触发下拉的事件，目前测试用的ios

**Comment by Thresh17** [comment]
安卓手机下拉正常，但是会有卡顿

**Comment by tgioer** [comment]
这个组件还需要再优化下，下拉滑动在小程序端会卡顿。

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/issues/207
