### ISSUE TITLE
notify, toast, dialog 这些组件存在跨页面问题

### ISSUE THREAD

**Issue by endink** [mallfoundry/taroify#259]
小程序中，函数式调用时候如果两个页面都放置了 id 组件（notify, dialog, toast），show 了以后如果点返回按钮或手机返回按钮不会消失,  就算麻烦点，通过 useEffect 注册一个 close 的钩子 , 返回到上一页，在页面上还是能看到 dialog, notift, toast 消失的动画，导致这些组件的函数式调用基本无法使用。

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/260

**Comment by tgioer** [comment]
https://taroify.gitee.io/taroify.com/changelog/#v0024-alpha1
