### ISSUE TITLE
Empty 组件中的 Image 存在样式被覆盖的问题

### ISSUE THREAD

**Issue by tgioer** [mallfoundry/taroify#268]
<img width="342" alt="07c32d1d9df113dd31a054f987abd9a" src="https://user-images.githubusercontent.com/18252854/149870684-32fb1869-09b4-4db8-8e16-7be640acd15c.png">

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/271

**Comment by airbreak** [comment]
遇到一样的问题。还以为图片没有，才发现图片高度没了。
