### ISSUE TITLE
IndexList 组件存在页面展示和数组变量不对应情况

### ISSUE THREAD

**Issue by airbreak** [mallfoundry/taroify#281]
默认先把所有的城市都展示出来，输入框可以输入关键字进行过滤。
**问题出现步骤：**
1. 先输入 “商丘”，此时可正常过滤。
2. 删除搜索内容，此时页面上会出现如下图问题。
![image](https://user-images.githubusercontent.com/14807618/150171726-40387f74-3f5d-4634-a21e-5226bb4d4f8e.png)

```
const indexListAll = [{"groupName":"B","children":[{"adcode":"110100","name":"北京市"}]},{"groupName":"S","children":[{"adcode":"411400","name":"商丘市"},{"adcode":"140600","name":"朔州市"}]}]
  const [keyWord, setKeyWord] = useState<string>('')

  function citysListFilter() {
    const newList = indexListAll.filter((item) => {
      const tmpArr = item.children.filter(k => k.name.indexOf(keyWord) === 0)
      return tmpArr.length > 0
    })
    return newList
  }
  function onSearch(key) {
    setKeyWord(key)
  }

  function debounce(fn, delay) {
    let timer = null;
    return function () {
      var context = this
      var args = arguments
      clearTimeout(timer)
      timer = setTimeout(function () {
        fn.apply(context, args)
      }, delay)
    }
  }
  
  return (
    <View>
        <Input
          placeholder='请输入地区名称查询'
          onInput={(e) => debounce(() => onSearch(e.target.value), 500)()} />
        <IndexList>
          {
            citysListFilter().map((item) => {
              return (
                <Fragment key={item.name}>
                  <IndexList.Anchor index={item.groupName} />
                  {
                    item.children.map((child => {
                      return ( 
                        <Cell
                          key={child}
                          title={<View>{child.name}<Arrow style={{marginLeft: '4px'}} /></View>}
                          onClick={() => selectCityItem(child)}
                        />
                      )
                    }))
                  }
                </Fragment>
              )
            })
          }
        </IndexList>
    </View>
  )
```

**Comment by tgioer** [comment]
主要原因在于 `<Fragment key={item.name}>` 的 key 存在重复，请保证这里的 key 是唯一的，同时 `<Cell key={child}` key 只可以使用 string | number 类型的值。

```tsx
import { Cell, IndexList, Input } from "@taroify/core"
import { Arrow } from "@taroify/icons"
import { View } from "@tarojs/components"
import * as React from "react"
import { useState } from "react"

const indexListAll = [
  { groupName: "B", children: [{ adcode: "110100", name: "北京市" }] },
  {
    groupName: "S",
    children: [
      { adcode: "411400", name: "商丘市" },
      { adcode: "140600", name: "朔州市" },
    ],
  },
]

function Index() {
  const [keyWord, setKeyWord] = useState<string>("")

  function citysListFilter() {
    const newList = indexListAll.filter((item) => {
      const tmpArr = item.children.filter((k) => k.name.indexOf(keyWord) === 0)
      return tmpArr.length > 0
    })
    return newList
  }

  function onSearch(key) {
    setKeyWord(key)
  }

  function debounce(fn, delay) {
    let timer = null
    return function () {
      var context = this
      var args = arguments
      clearTimeout(timer)
      timer = setTimeout(function () {
        fn.apply(context, args)
      }, delay)
    }
  }

  return (
    <View>
      <Input
        placeholder="请输入地区名称查询"
        onInput={(e) => debounce(() => onSearch(e.target.value), 500)()}
      />
      <IndexList>
        {citysListFilter().map((item) => {
          return (
            <React.Fragment key={item.groupName}>
              <IndexList.Anchor index={item.groupName} />
              {item.children.map((child) => {
                return (
                  <Cell
                    key={child.name}
                    title={
                      <View>
                        {child.name}
                        <Arrow style={{ marginLeft: "4px" }} />
                      </View>
                    }
                    // onClick={() => selectCityItem(child)}
                  />
                )
              })}
            </React.Fragment>
          )
        })}
      </IndexList>
    </View>
  )
}

export default Index
```

**Comment by airbreak** [comment]
感谢大佬的回答，确实是因为key的问题，但是这里还有一小点需要修改，map方法 内的第一个节点不能用Fragment，需要用一个真实的节点，比如View之类的，否则还是会出现同样的问题。

> 主要原因在于 `<Fragment key={item.name}>` 的 key 存在重复，请保证这里的 key 是唯一的，同时 `<Cell key={child}` key 只可以使用 string | number 类型的值。
> 
> ```tsx
> import { Cell, IndexList, Input } from "@taroify/core"
> import { Arrow } from "@taroify/icons"
> import { View } from "@tarojs/components"
> import * as React from "react"
> import { useState } from "react"
> 
> const indexListAll = [
>   { groupName: "B", children: [{ adcode: "110100", name: "北京市" }] },
>   {
>     groupName: "S",
>     children: [
>       { adcode: "411400", name: "商丘市" },
>       { adcode: "140600", name: "朔州市" },
>     ],
>   },
> ]
> 
> function Index() {
>   const [keyWord, setKeyWord] = useState<string>("")
> 
>   function citysListFilter() {
>     const newList = indexListAll.filter((item) => {
>       const tmpArr = item.children.filter((k) => k.name.indexOf(keyWord) === 0)
>       return tmpArr.length > 0
>     })
>     return newList
>   }
> 
>   function onSearch(key) {
>     setKeyWord(key)
>   }
> 
>   function debounce(fn, delay) {
>     let timer = null
>     return function () {
>       var context = this
>       var args = arguments
>       clearTimeout(timer)
>       timer = setTimeout(function () {
>         fn.apply(context, args)
>       }, delay)
>     }
>   }
> 
>   return (
>     <View>
>       <Input
>         placeholder="请输入地区名称查询"
>         onInput={(e) => debounce(() => onSearch(e.target.value), 500)()}
>       />
>       <IndexList>
>         {citysListFilter().map((item) => {
>           return (
>             <React.Fragment key={item.groupName}>
>               <IndexList.Anchor index={item.groupName} />
>               {item.children.map((child) => {
>                 return (
>                   <Cell
>                     key={child.name}
>                     title={
>                       <View>
>                         {child.name}
>                         <Arrow style={{ marginLeft: "4px" }} />
>                       </View>
>                     }
>                     // onClick={() => selectCityItem(child)}
>                   />
>                 )
>               })}
>             </React.Fragment>
>           )
>         })}
>       </IndexList>
>     </View>
>   )
> }
> 
> export default Index
> ```

**Comment by tgioer** [comment]
> 

是同样的数据吗？还是其他的数据。如果是，可以提供一下复现数据，我研究一下。
