### ISSUE TITLE
下拉PullRefresh 刷新结合list 在微信开发者工具，滚动条滑至底部 滚动触发加载数据，失效

### ISSUE THREAD

**Issue by z10026393** [mallfoundry/taroify#3]
import React, { useState, useEffect, useRef } from "react";
import { View } from "@tarojs/components";
import { useDidHide, useDidShow } from "@tarojs/taro";
import { Tabs, PullRefresh, List, Loading, Empty } from "@taroify/core";
import "@taroify/core/pull-refresh/index.scss";
import "@taroify/core/Tabs/index.scss";
import "@taroify/core/Empty/index.scss";
import "@taroify/core/loading/index.scss";
import "@taroify/core/List/index.scss";

function Information() {
  const init = async () => {
    console.log("请求 数据 >>> information");
  };
  useEffect(() => {
    init();
  }, []);

  useDidShow(() => {
    console.log("componentDidShow");
  });

  useDidHide(() => {
    console.log("componentDidHide");
  });
  let list = [
    { label: "事件上报" },
    { label: "全民参与" },
    { label: "建议上报" },
  ];
  const [hasMore, setHasMore] = useState(true);
  const listRef = useRef([]);
  const [loading, setLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [activeKey, setActiveKey] = useState("0");
  // 图标处理
  // Tabs切换事件
  function onChangeTabs(key) {
    setActiveKey(key);
    onRefresh();
    // changeActiveKey(key);
  }
  // 下拉刷新
  function onRefresh() {
    setRefreshing(true);
    setLoading(false);
    listRef.current = [];
    onLoad();
  }
  // 滚动刷新
  const onLoad = () => {
    setLoading(true);
    setTimeout(() => {
      setRefreshing(false);
      for (let i = 0; i < 10; i++) {
        const id = listRef.current.length + 1;
        listRef.current.push({
          text: "111111111",
          img: '',
          id: i % 2 != 0 || false,
          Time: "2020-10-05",
        });
      }
      setLoading(false);
      setHasMore(listRef.current.length < 80);
    }, 1000);
  };
  console.log(listRef.current, "=listRef.current==");
  return (
    <View className="InformationBody">
        <Tabs
          sticky
          activeKey={activeKey}
          ellipsis={false}
          onChange={({ key }) => onChangeTabs(key)}
        >
          {list.map((item, index) => (
            <Tabs.TabPane key={index} title={item.label}>
              <PullRefresh loading={refreshing} onRefresh={onRefresh}>
                <List
                  immediateCheck={false}
                  immediate-check={false}
                  loading={loading}
                  hasMore={hasMore}
                  onLoad={onLoad}
                  offset={500}
                >
                  {listRef.current.map((item, Index) => (
                    // <Cell item={item} Index={Index} key={Index}></Cell>
                    <View key={Index}>{Index}</View>
                  ))}
                  <List.Placeholder>
                    {loading && <Loading>加载中... </Loading>}
                    {!hasMore && "没有更多了"}
                  </List.Placeholder>
                </List>
              </PullRefresh>
            </Tabs.TabPane>
          ))}
        </Tabs>
    </View>
  );
}
export default Information;

**Comment by tgioer** [comment]
目前来看，taro weapp 的 nextTick 在 usePageScroll 中不能执行，这个要等 taro 修复一下再说。https://github.com/NervJS/taro/issues/10179

**Comment by tgioer** [comment]
Taro 3.3.6 已修复。https://github.com/NervJS/taro/pull/10188
