### ISSUE TITLE
@taroify/icons 提供全部的 VanIcon 组件

### ISSUE THREAD

**Issue by tgioer** [mallfoundry/taroify#30]

**Comment by lingziyb** [comment]
文档示例里的图标不能用的，可以像下面这样做：

```javascript
import { VanIcon } from "@taroify/icons/van";

export default () => ( <VanIcon name="phone" /> )
```

@mallfoundry 仓主啥时候把所有图标包装组件暴露出来呢 ^-^ ||| ....

**Comment by felix9ia** [comment]
@lingziyb 你怎么解决的，我也很好奇如果我想遍历的数组里指定icon怎么搞？

**Comment by TechQuery** [comment]
> @lingziyb 你怎么解决的，我也很好奇如果我想遍历的数组里指定icon怎么搞？

@felix9ia 数组每一项里面存图标的 `name` 就行了。

**Comment by felix9ia** [comment]
类似这样吗？

```
const pages = [
  {
    id: "orderManage",
    name: "订单管理",
    path: "",
    icon: "FriendsOutlined"
  },
  {
    id: "goodsManage",
    name: "商品管理",
    path: "",
    icon: "HomeOutlined"

  },
  {
    id: "shopManage",
    name: "店铺管理",
    path: "",
    icon: "SettingOutlined"
  }
]
```
用的时候是 
```
<Icon name={item.icon}>
```
但是我没有生效啊...

**Comment by TechQuery** [comment]
> 类似这样吗？
> 
> ```
> const pages = [
>   {
>     id: "orderManage",
>     name: "订单管理",
>     path: "",
>     icon: "FriendsOutlined"
>   },
>   {
>     id: "goodsManage",
>     name: "商品管理",
>     path: "",
>     icon: "HomeOutlined"
> 
>   },
>   {
>     id: "shopManage",
>     name: "店铺管理",
>     path: "",
>     icon: "SettingOutlined"
>   }
> ]
> ```
> 用的时候是 
> ```
> <Icon name={item.icon}>
> ```
> 但是我没有生效啊...

你这些都是图标包装组件的函数名，不是图标的 `name` 值。

你也可以都去掉引号变成 `import` 的形式，再用如下方法使用：

```jsx
<item.icon />
```
