### ISSUE TITLE
Recommended Tool Features

### ISSUE THREAD

**Issue by wangweizm** [mallfoundry/taroify#304]
I hope that the pop-up window can be placed in a function. It is really troublesome to insert nodes now. You can do more callbacks for props and less nesting of child nodes.

**Comment by tgioer** [comment]
> I hope that the pop-up window can be placed in a function. 
I don't understand what it means to put popup in a function.
Is the Popup component required to provide imperative handle?

> You can do more callbacks for props and less nesting of child nodes.
I don't understand what it means here, right.

Could you please provide some more detailed explanation?

For example: code, examples, etc...

**Comment by wangweizm** [comment]
yes.hooks

**Comment by tgioer** [comment]
For example: code, examples, etc...

**Comment by tgioer** [comment]
```tsx
Popup.open()
```
Link this ?
