### ISSUE TITLE
话说什么时候发布正式版。

### ISSUE THREAD

**Issue by AimLuo** [mallfoundry/taroify#32]

**Comment by tgioer** [comment]
有几个 taro 的 bug 还没有修复，要等 taro 的 bug 修复完。

**Comment by TinsFox** [comment]
> 有几个 taro 的 bug 还没有修复，要等 taro 的 bug 修复完。

这个怕是要等很久了，不如自己PR（PR了也不知道多久Merge，手动狗头）

**Comment by sgknight2020** [comment]
快点更新，急不可耐的想用了^_^

**Comment by tgioer** [comment]
@sgknight2020 可以使用的，0.0.20-alpha.0 是目前最稳定的版本。

**Comment by tgioer** [comment]
目前已知平台 BUG 已经全部修复。

**Comment by YC725968** [comment]
啥时候提交为正式版啊

**Comment by tgioer** [comment]
> 啥时候提交为正式版啊

快了，快了。

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/issues/333
