### ISSUE TITLE
Taroify for Alipay

### ISSUE THREAD

**Issue by tgioer** [mallfoundry/taroify#33]

**Comment by tgioer** [comment]
Taroify for alipay 在 `^0.0.17-alpha.0` 除
Picker 存在滑动穿透问题
ActionSheet 存在样式问题
Circle 存在实现问题

其余组件以完美支持。

**Comment by tgioer** [comment]
![image](https://user-images.githubusercontent.com/18252854/140260485-848b5c4a-9580-47b3-ac13-baff16757b1b.png)

在阿里小程序中要开启  component2

**Comment by olifer655** [comment]
对于微信小程序， Popup 也存在穿透问题

**Comment by tgioer** [comment]
> 对于微信小程序， Popup 也存在穿透问题

哪个版本的？
