### ISSUE TITLE
Taroify 1.0 Roadmap

### ISSUE THREAD

**Issue by ickg5** [mallfoundry/taroify#333]
为发布 Release 版本提供更健壮的支持，未来的一段时间我们将为整个项目提供更规范的方案。

- 单元测试（Unit Test）
- Github
    - [x] #345
    - [x] #346
    - [ ] Actions

-  Git Commit
    - 采用祈使句作为提交模板

**Comment by weiwenhuaming** [comment]
鼓掌~

**Comment by coderYarn** [comment]
go!go!go!

**Comment by TinsFox** [comment]
文档还需要完善一下，组件的ConfigProvider可用变量有些组件没有列出来，如Cell

**Comment by tgioer** [comment]
> 文档还需要完善一下，组件的ConfigProvider可用变量有些组件没有列出来，如Cell

https://github.com/mallfoundry/taroify/issues/392

**Comment by whevether** [comment]
请问支持react-native嘛

**Comment by tgioer** [comment]
> 请问支持react-native嘛

不支持

**Comment by whevether** [comment]
> > 请问支持react-native嘛
> 
> 
> 
> 不支持

有考虑支持计划吗？   如果能支持那就真的牛逼了

**Comment by tgioer** [comment]
> > > 请问支持react-native嘛
> > 
> > 
> > 不支持
> 
> 有考虑支持计划吗？ 如果能支持那就真的牛逼了

从未考虑过

**Comment by kingchary** [comment]
请问后面会支持react 18吗

**Comment by tgioer** [comment]
> 请问后面会支持react 18吗

taro 升级，就跟着升级。

**Comment by bingtsingw** [comment]
咦, 才发现, 没有用commitlint和husky吗

**Comment by tgioer** [comment]
> 咦, 才发现, 没有用commitlint和husky吗

主要是不支持祈使句，我没找到好的模板。

**Comment by charsunny** [comment]
有没有考虑对齐下react vant的Card组件？

**Comment by tgioer** [comment]
> 有没有考虑对齐下react vant的Card组件？

应该会

**Comment by iversonwool** [comment]
这个项目跟 @antmjs/vantui有什么区别？都可以用在taro工程中吗？

**Comment by hqwlkj** [comment]
NoticeBar 在h5 中切换页面后，数据不滚动的问题怎么处理呢？
