### ISSUE TITLE
问下组件库支持 Taro 3.+ 的跨平台开发么？

### ISSUE THREAD

**Issue by weiwenhuaming** [mallfoundry/taroify#337]
组件库支持 Taro 输出 H5 的吧？
目前看到有 issue 提到可以支持 H5，应该是支持的，不过还是来此确认一下。

目标平台:
- 微信小程序
- H5 

Taro 版本：
- Taro 3.+

**Comment by tgioer** [comment]
支持

**Comment by weiwenhuaming** [comment]
> 支持

谢谢啦，这就用起来。
