### ISSUE TITLE
[Bug Report] Picker 组件 onCancel 报错

### ISSUE THREAD

**Issue by idujiawei** [mallfoundry/taroify#375]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.27-alpha.4

### 描述一下您遇到的问题以及重现步骤

![image](https://user-images.githubusercontent.com/20924706/154938389-0a1f825a-fc9d-40d4-8cf3-982047673445.png)

data 为 []，空数组，点击取消，报错

代码：
![image](https://user-images.githubusercontent.com/20924706/154938884-a59cb278-c325-4fe9-a0fb-bf199b42d8a1.png)

**Comment by idujiawei** [comment]
valueOptionsRef.current 为 [undefined]

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/378

**Comment by tgioer** [comment]
请更新至 0.0.27-alpha.5
