### ISSUE TITLE
[建议]Dialog应该给选项调整z-index. 

### ISSUE THREAD

**Issue by wjxforu** [mallfoundry/taroify#38]
做了CustomTabBar希望可以遮挡住. 
本身z-index调整到99999是可以挡住custom-tabbar的. 
但是目前我看Dialog分了两个. 需要调整bg到99990, 然后前面的弹窗的为99999, 这样子能达到较好的效果

![image](https://user-images.githubusercontent.com/7859666/137248392-83ae8732-132f-483e-81b0-eecf53bffdd9.png)

![image](https://user-images.githubusercontent.com/7859666/137248281-d88287d0-96dd-4358-8f0c-7d15b7243a67.png)

**Comment by wjxforu** [comment]
我不太清楚怎么把css注入到 taroify的组件里面去. 
刚弄前端不久, 所以这一块没太有清晰的路径哈
最外层的react component肯定不是最终的.

**Comment by tgioer** [comment]
在 taroify 中，能用 css 解决的样式问题，就不提供 prop 来设置

**Comment by wjxforu** [comment]
认同的, 能用css的不提供prop来设置. 
只是不太清楚怎么用css解决. 怎么获取到taroify用的class, 或者注入class到指定的comp上面. 内层的comp不知道怎么获取到. 
如果能有个说明会比较好一点. 
感谢.

**Comment by tgioer** [comment]
在 taroify 中会给所有的组件提供 `className` 的属性，通过设置 `className` 属性来设置样式。当需要设置组件的内部元素的样式时可以使用嵌套样式。

比如可以给 Button 组件：

```tsx
<Button className="custom-class" />
```

```css
.custom-class .taroify-button__content {
  background-color: red;
  //....
}
```

如果不知道一个组件的内部结构，可以通过 F12 开发者工具调试获得 DOM 结构查看。

**Comment by wjxforu** [comment]
好嘞, 感谢.
