### ISSUE TITLE
[Bug Report] DropdownMenu组件引入报错

### ISSUE THREAD

**Issue by miaomiaoya** [mallfoundry/taroify#386]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.27-alpha.5

### 描述一下您遇到的问题以及重现步骤

DropdownMenu组件引入报错
![image](https://user-images.githubusercontent.com/39975343/155921210-512f32e7-bdf3-4e16-83d5-a691c6999875.png)

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/391
