### ISSUE TITLE
[Bug Report] Popup组件点击穿透，触发了遮罩下的Input

### ISSUE THREAD

**Issue by WangJM001** [mallfoundry/taroify#388]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

微信开发者工具，真机调试

### 你正在使用的 Taroify 版本是多少

0.0.27-alpha.4

### 描述一下您遇到的问题以及重现步骤

Popup组件点击穿透，触发了遮罩下的Input
![1646032584(1)](https://user-images.githubusercontent.com/20501316/155940369-4e6e623e-dfeb-4ed5-8212-fffbe2ab15f1.png)

**Comment by tgioer** [comment]
iOS 的 input 穿透？

**Comment by WangJM001** [comment]
是的 iOS，点击popup上面的元素触发了下层input的focus，我图上标记的那个元素其实是遮罩下面的

**Comment by tgioer** [comment]
这个问题，你可以在群里问一下。

**Comment by Yorksh1re** [comment]
给 input 组件加上 `always-embed` 属性，使其强制处于[同层渲染](https://developers.weixin.qq.com/miniprogram/dev/component/input.html#always-embed)。
![image](https://user-images.githubusercontent.com/70258597/156978554-cb08ee79-a434-4592-b4ec-f20a53249685.png)

**Comment by cloud2303** [comment]
IOS15实测加上`always-embed`并不能生效，还会出现问题。
` let [IsOpen,setIsOpen] = useState(false)//你的弹窗组件`
1. 可以给input设置Disabled
 `<Input className="mt-64" disabled={IsOpen}   placeholder='这里是input'/>`
2. 可以设置input显隐
`{IsOpen?"":<Input className="mt-64"  placeholder='这里是input'/>}`

**Comment by WangJM001** [comment]
谢了
