### ISSUE TITLE
field组件在ts下不存在value属性

### ISSUE THREAD

**Issue by shunshunyue** [mallfoundry/taroify#394]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.27-alpha.5

### 描述一下您遇到的问题以及重现步骤

使用field组件value属性ts报属性不存在

**Comment by tgioer** [comment]
Field 组件存在 value 属性吗？

**Comment by shunshunyue** [comment]
文档是这样用的呀

**Comment by shunshunyue** [comment]
>       <Field
        value={value}
        label="城市"
        placeholder="选择城市"
        readonly
        rightIcon={<ArrowRight />}
        onClick={() => setOpenPicker(true)}
      />
      <Popup open={openPicker} rounded placement="bottom" onClose={setOpenPicker}>
        <Picker
          onCancel={() => setOpenPicker(false)}
          onConfirm={(values) => {
            setValue(values)
            setOpenPicker(false)
          }}
        >
          <Picker.Toolbar>
            <Picker.Button>取消</Picker.Button>
            <Picker.Title>标题</Picker.Title>
            <Picker.Button>确认</Picker.Button>
          </Picker.Toolbar>
          <Picker.Column>
            <Picker.Option>杭州</Picker.Option>
            <Picker.Option>宁波</Picker.Option>
            <Picker.Option>温州</Picker.Option>
            <Picker.Option>绍兴</Picker.Option>
            <Picker.Option>湖州</Picker.Option>
            <Picker.Option>嘉兴</Picker.Option>
            <Picker.Option>金华</Picker.Option>
          </Picker.Column>
        </Picker>
      </Popup>

**Comment by tgioer** [comment]
这是之前的文档没有及时更新，请看一下最新的 Field 文档

**Comment by shunshunyue** [comment]
最新的在哪里呀  麻烦有咩有地址

**Comment by tgioer** [comment]
https://taroify.gitee.io/taroify.com/components/field/

**Comment by tgioer** [comment]
```tsx
function PickerPopup() {
  const [value, setValue] = useState("")
  const [openPicker, setOpenPicker] = useState(false)

  return (
    <>
      <Field label="城市" rightIcon={<ArrowRight />} onClick={() => setOpenPicker(true)}>
        <Input readonly placeholder="选择城市" value={value} />
      </Field>
      <Popup open={openPicker} rounded placement="bottom" onClose={setOpenPicker}>
        <Popup.Backdrop />
        <Picker
          onCancel={() => setOpenPicker(false)}
          onConfirm={(values) => {
            setValue(values)
            setOpenPicker(false)
          }}
        >
          <Picker.Toolbar>
            <Picker.Button>取消</Picker.Button>
            <Picker.Title>标题</Picker.Title>
            <Picker.Button>确认</Picker.Button>
          </Picker.Toolbar>
          <Picker.Column>
            <Picker.Option>杭州</Picker.Option>
            <Picker.Option>宁波</Picker.Option>
            <Picker.Option>温州</Picker.Option>
            <Picker.Option>绍兴</Picker.Option>
            <Picker.Option>湖州</Picker.Option>
            <Picker.Option>嘉兴</Picker.Option>
            <Picker.Option>金华</Picker.Option>
          </Picker.Column>
        </Picker>
      </Popup>
    </>
  )
}
```

**Comment by shunshunyue** [comment]
好的 谢谢
