### ISSUE TITLE
[Bug Report] form表单函数校验

### ISSUE THREAD

**Issue by miaomiaoya** [mallfoundry/taroify#397]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.27-alpha.6

### 描述一下您遇到的问题以及重现步骤

form表单函数校验通过后也是会触发onValidate这个方法

**Comment by tgioer** [comment]
能否提供一个可直接运行测试的代码?

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/400
