### ISSUE TITLE
Taroify FAQ

### ISSUE THREAD

**Issue by ickg5** [mallfoundry/taroify#398]
- [淘宝镜像（npmmirror）和 NPM 的最新版本同步有延迟](https://github.com/mallfoundry/taroify/issues/119)
- [iOS Input 组件点击穿透](https://github.com/mallfoundry/taroify/issues/388#issuecomment-1060271699) [@jiahui](https://github.com/cloud2303)
- [375 设计稿，组件样式放大一倍](https://github.com/mallfoundry/taroify/issues/173#issuecomment-991390507)
- [DEMO 无法查看时，可以清空缓存再试试](https://github.com/mallfoundry/taroify/issues/421#issuecomment-1075868653)

**Comment by jianhao2010303** [comment]
希望增加 button group组件
