### ISSUE TITLE
使用tab组件ui有异常

### ISSUE THREAD

**Issue by hellozsh** [mallfoundry/taroify#4]
[
<img width="478" alt="截屏2021-09-03 下午6 49 55" src="https://user-images.githubusercontent.com/17559931/131994136-f8ed4bdd-5653-4cf1-8c4e-c04c5269d9eb.png">
](url)

如图，我的margin只对左边起作用，右边不起作用，
不用这个组件的时候，这个页面是正常的

**Comment by hellozsh** [comment]
补充 Taro v3.3.2

**Comment by tgioer** [comment]
贴出来代码看一下

**Comment by hellozsh** [comment]
<img width="871" alt="截屏2021-09-06 上午9 39 00" src="https://user-images.githubusercontent.com/17559931/132148797-a9512370-5980-4811-8bad-fd12e02dac79.png">
<img width="236" alt="截屏2021-09-06 上午9 40 01" src="https://user-images.githubusercontent.com/17559931/132148817-701418ea-b558-41a9-9d74-fd3dce6e487a.png">

以下是第一个页面的
<img width="705" alt="截屏2021-09-06 上午10 09 27" src="https://user-images.githubusercontent.com/17559931/132150754-4db79bde-0c73-4e25-bee2-399eb2e68c29.png">
<img width="394" alt="截屏2021-09-06 上午10 09 44" src="https://user-images.githubusercontent.com/17559931/132150762-56fbbfba-0c03-4a15-851b-04d53d2b6003.png">
我这里测试把这个.lastRecord {
  display: flex;
} 这个display: flex;去掉就没事，他应该影响了tab组件效果吧

**Comment by hellozsh** [comment]
第一个页面的
<img width="705" alt="截屏2021-09-06 上午10 09 27" src="https://user-images.githubusercontent.com/17559931/132150900-b0408988-026b-4469-83a4-000278e956db.png">
<img width="394" alt="截屏2021-09-06 上午10 09 44" src="https://user-images.githubusercontent.com/17559931/132150909-7df7bd70-9b26-4d1d-adef-a27e8788b6a6.png">

**Comment by tgioer** [comment]
提一个最小仓库，或者最小代码集。看截图看不出来
