### ISSUE TITLE
[Bug Report] 真机Popup组件出现抖动

### ISSUE THREAD

**Issue by WangJM001** [mallfoundry/taroify#404]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.27-alpha.6

### 描述一下您遇到的问题以及重现步骤

真机Popup组件出现抖动

https://user-images.githubusercontent.com/20501316/158513774-867f9325-9ead-4205-9176-962e9665591b.mp4

**Comment by tgioer** [comment]
请提供一个可直接测试运行的代码

**Comment by WangJM001** [comment]
`
import { Button, Popup } from '@taroify/core';
import { View } from '@tarojs/components';
import { useState } from 'react';

function Test() {
  const [popupVisible, setPopupVisible] = useState(false);

  return (
    <View>
      <Button onClick={() => setPopupVisible(true)}>Open</Button>
      <Popup
        mountOnEnter={false}
        open={popupVisible}
        rounded
        placement="bottom"
        onClose={setPopupVisible}
      >
        <View style={{ height: 200 }}>Popup</View>
      </Popup>
    </View>
  );
}

export default Test;

`

**Comment by tgioer** [comment]
我暂时没有iOS的真机，你试试杀掉微信进程，重新打开小程序看看。

**Comment by WangJM001** [comment]
还是有问题

**Comment by bigmeow** [comment]
@tgioer 升级到ios15.4必现, 这个版本之下的ios系统没有问题
以下是taroify demo的表现
https://user-images.githubusercontent.com/10484248/158750969-69462ce0-3659-4f9a-a00c-563d82d71329.mp4

**Comment by bigmeow** [comment]
@tgioer 
另外，不只是小程序，在这个系统版本的 微信网页、Safari浏览器都可以重现, 测试网页： https://taroify.gitee.io/taroify.com/h5/index.html#/pages/basic/popup/index

**Comment by tgioer** [comment]
那这....

**Comment by bigmeow** [comment]
https://github.com/mallfoundry/taroify/blob/257caac8b17ac5ee0bacaa827862a86ced2f7491/packages/core/src/popup/popup.scss?_pjax=%23js-repo-pjax-container#L9
删掉这行代码可以暂时解决问题，不过感觉动画还是不那么流畅。
bug原因推测是这里的动画执行顺序和Transition 组件的动画没有同步协调，所以看起来会弹出2次

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/431

**Comment by tgioer** [comment]
请更新至 0.0.29-alpha.3 再试试

**Comment by WangJM001** [comment]
ok了
