### ISSUE TITLE
IndexList 索引栏在Popup 弹出层，点击索引栏无效果

### ISSUE THREAD

**Issue by qiuweikangdev** [mallfoundry/taroify#408]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5

### 平台/设备/浏览器

h5

### 你正在使用的 Taroify 版本是多少

0.0.28-alpha.0

### 描述一下您遇到的问题以及重现步骤

IndexList 索引栏在Popup 弹出层，点击索引栏无效果, 无法滚动，
1、希望点击索引栏可以滚动指定位置
2、希望IndexList可以增加参数，支持可以根据索引项默认滚动的位置

**Comment by tgioer** [comment]
目前 IndexList 不支持嵌套在 ScrollView 里面，只支持页面级内使用。

**Comment by qiuweikangdev** [comment]
IndexList 是不支持Popup 弹出层里面吗

**Comment by tgioer** [comment]
你嵌套在 Popup 内，就不属于也页面级的了
