### ISSUE TITLE
[Bug Report] ActionBar 复制官网示例 badge 无效 

### ISSUE THREAD

**Issue by skyliwq** [mallfoundry/taroify#410]
### 问题出在哪个包

@taroify/commerce

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.28-alpha.0

### 描述一下您遇到的问题以及重现步骤

ActionBar 复制官网实例 badge 无效  已正常引入 import "@taroify/commerce/index.scss"

**Comment by tgioer** [comment]
是怎么失效的？按需引用吗？

**Comment by skyliwq** [comment]
不是按需引入 就是不显示 import "@taroify/commerce/index.scss"

**Comment by tgioer** [comment]
如果 commerce 不按需加载，必须全部都得采用不按需加载。
你可以把 commerce 采用按需加载
```tsx
// babel.config.js
{
  plugins:[
    // ...
    [
      "import",
      {
        libraryName: "@taroify/commerce",
        libraryDirectory: "",
        style: true,
      },
      "@taroify/commerce",
    ],
  ]
}
```
