### ISSUE TITLE
[Bug Report] Popup 滚动穿透的问题

### ISSUE THREAD

**Issue by skyliwq** [mallfoundry/taroify#411]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.28-alpha.0

### 描述一下您遇到的问题以及重现步骤

Popup 里存在滚动穿透的问题 ，是需要自己处理还是组件自身有处理功能！

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/issues/388#issuecomment-1060271699

**Comment by tgioer** [comment]
穿透是 Input 吗？

**Comment by skyliwq** [comment]
Toast 如果不启用backdrop 会被穿透到下层 该如何解决呀

**Comment by tgioer** [comment]
是 iOS 吗？
