### ISSUE TITLE
官网 DEMO 展示不出来

### ISSUE THREAD

**Issue by idujiawei** [mallfoundry/taroify#421]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5

### 你正在使用的 Taroify 版本是多少

1

### 描述一下您遇到的问题以及重现步骤

![image](https://user-images.githubusercontent.com/20924706/159610248-45f0648d-8e76-4f5a-acaf-2a3e0a0b8263.png)

**Comment by tgioer** [comment]
清空缓存，重新刷新
