### ISSUE TITLE
下拉菜单组件不兼容苹果,点击会样式错位和卡顿

### ISSUE THREAD

**Issue by shaoming1101** [mallfoundry/taroify#426]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

安卓和苹果都会出现

### 你正在使用的 Taroify 版本是多少

0.0.28

### 描述一下您遇到的问题以及重现步骤

下拉菜单测试版本很卡

**Comment by tgioer** [comment]
请提供可以直接复现的函数组件

**Comment by shaoming1101** [comment]
![b0c14b4525ae6e5c15b0d9eb5c35310](https://user-images.githubusercontent.com/86390105/160036272-f9aaddd4-6822-416d-8fab-513aec88eac3.png)
这个组件直接应用到小程序里面,在苹果手机上预览就会卡顿

**Comment by shaoming1101** [comment]
可以自行在苹果手机上测试

**Comment by tgioer** [comment]
我今天找到了最新版本ios的手机测试了下，是会出现弹出两次的问题吗？

**Comment by shaoming1101** [comment]
是的,而且样式弹出还有些问题

**Comment by tgioer** [comment]
这个问题是 Popup 导致的，这两天会修复的

**Comment by tgioer** [comment]
请更新至 0.0.29-alpha.3 再试试

**Comment by shaoming1101** [comment]
已调试,这两个组件依然下拉有问题,
1,下拉刷新组件,卡顿依然存在,ios系统还是会弹出两次.
2,picker组件,弹出无异常,选择子选项不流畅,卡顿,
3,picker组件,无法选中初始的第一个值,必须滑动一下才能选中
![1648628251(1)](https://user-images.githubusercontent.com/86390105/160784979-6b6ea727-785c-437e-94f1-b74dc3bbcd3f.jpg)

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/436

**Comment by tgioer** [comment]
出现卡顿，请使用 CustomWrapper 组件嵌套包裹一下组件

**Comment by tgioer** [comment]
请更新至 0.0.29-alpha.4
