### ISSUE TITLE
[Bug Report] Form组件的校验规则问题

### ISSUE THREAD

**Issue by velley** [mallfoundry/taroify#428]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.27

### 描述一下您遇到的问题以及重现步骤

当FormItem没有required必填校验但有partten正则校验时，用户不进行输入，提交时会导致正则校验不通过。理论上空值确实无法通过正则校验，但是对于实际使用场景来讲，设置partten但不设置required，预期就是要允许用户不填入数据，正则校验只在填入时触发。针对这点，我个人意见是最好做一下修改。谢谢！

### 你知道如何解决这个问题吗

Yes

**Comment by tgioer** [comment]
请提供一个我可以直接测试的组件代码
