### ISSUE TITLE
下拉菜单可以加一个状态吗 

### ISSUE THREAD

**Issue by shunshunyue** [mallfoundry/taroify#452]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.27-alpha.5

### 描述一下您遇到的问题以及重现步骤

目前下拉菜单打开后背后页面还是可以滑动  想用overflow: "hidden"解决  发现下拉菜单获取不到状态

**Comment by tgioer** [comment]
等我研究下

**Comment by tgioer** [comment]
DropdownMenu 提供了 onChange 事件，你可以通过监听 onChange 事件来处理。

```tsx
<DropdownMenu onChange={()=> console.log('change')}>
```

**Comment by shunshunyue** [comment]
ok   感谢  完美解决
