### ISSUE TITLE
[Bug Report] 下拉菜单 item 如果滑动到到最底部或者最顶部时进行滑动,会滑动整个页面

### ISSUE THREAD

**Issue by Coffee-rabbit** [mallfoundry/taroify#462]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

v0.0.29-alpha.6

### 描述一下您遇到的问题以及重现步骤

下拉菜单 item 如果滑动到到最底部或者最顶部进行滑动,会滑动整个页面

**Comment by tgioer** [comment]
如何复现？

**Comment by Coffee-rabbit** [comment]
演示代码 : https://github.com/Coffee-rabbit/taroifyIssuse

**Comment by tgioer** [comment]
小程序没办法操作根节点，你可以通过手动给 page 元素设置 `overflow: hidden;` 样式来解决。
https://github.com/mallfoundry/taroify/issues/452
