### ISSUE TITLE
useCascader 返回的数据不对

### ISSUE THREAD

**Issue by idujiawei** [mallfoundry/taroify#466]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.29-alpha.4

### 描述一下您遇到的问题以及重现步骤

useCascader 返回的数据不对

**Comment by idujiawei** [comment]
[
              {
                label: "浙江省",
                value: "330000",
                children: [
                  {
                    label: "杭州市",
                    value: "330100",
                    children: [
                      {
                        label: "上城区",
                        value: "330102"
                      },
                      {
                        label: "下城区",
                        value: "330103"
                      },
                      {
                        label: "江干区",
                        value: "330104"
                      }
                    ]
                  },
                  {
                    label: "宁波市",
                    value: "330200",
                    children: [
                      {
                        label: "海曙区",
                        value: "330203"
                      },
                      {
                        label: "江北区",
                        value: "330205"
                      },
                      {
                        label: "北仑区",
                        value: "330206"
                      }
                    ]
                  },
                  {
                    label: "温州市",
                    value: "330300",
                    children: [
                      {
                        label: "鹿城区",
                        value: "330302"
                      },
                      {
                        label: "龙湾区",
                        value: "330303"
                      },
                      {
                        label: "瓯海区",
                        value: "330304"
                      }
                    ]
                  }
                ]
              },
              {
                label: "江苏省",
                value: "320000",
                children: [
                  {
                    label: "南京市",
                    value: "320100",
                    children: [
                      {
                        label: "玄武区",
                        value: "320102"
                      },
                      {
                        label: "秦淮区",
                        value: "320104"
                      },
                      {
                        label: "建邺区",
                        value: "320105"
                      }
                    ]
                  },
                  {
                    label: "无锡市",
                    value: "320200",
                    children: [
                      {
                        label: "锡山区",
                        value: "320205"
                      },
                      {
                        label: "惠山区",
                        value: "320206"
                      },
                      {
                        label: "滨湖区",
                        value: "320211"
                      }
                    ]
                  },
                  {
                    label: "徐州市",
                    value: "320300",
                    children: [
                      {
                        label: "鼓楼区",
                        value: "320302"
                      },
                      {
                        label: "云龙区",
                        value: "320303"
                      },
                      {
                        label: "贾汪区",
                        value: "320305"
                      }
                    ]
                  }
                ]
              }
            ]
            
const { columns } = useCascader({
      value,
      data: options,
      depth: 3
 });

**Comment by tgioer** [comment]
请提供一个可复现的代码示例。

**Comment by idujiawei** [comment]
import { Cascader, Field, Popup } from "@taroify/core"
import { useCascader } from "@taroify/hooks"
import { ArrowRight } from "@taroify/icons"
import * as _ from "lodash"
import { useState } from "react"

const area = [
              {
                label: "浙江省",
                value: "330000",
                children: [
                  {
                    label: "杭州市",
                    value: "330100",
                    children: [
                      {
                        label: "上城区",
                        value: "330102"
                      },
                      {
                        label: "下城区",
                        value: "330103"
                      },
                      {
                        label: "江干区",
                        value: "330104"
                      }
                    ]
                  },
                  {
                    label: "宁波市",
                    value: "330200",
                    children: [
                      {
                        label: "海曙区",
                        value: "330203"
                      },
                      {
                        label: "江北区",
                        value: "330205"
                      },
                      {
                        label: "北仑区",
                        value: "330206"
                      }
                    ]
                  },
                  {
                    label: "温州市",
                    value: "330300",
                    children: [
                      {
                        label: "鹿城区",
                        value: "330302"
                      },
                      {
                        label: "龙湾区",
                        value: "330303"
                      },
                      {
                        label: "瓯海区",
                        value: "330304"
                      }
                    ]
                  }
                ]
              },
              {
                label: "江苏省",
                value: "320000",
                children: [
                  {
                    label: "南京市",
                    value: "320100",
                    children: [
                      {
                        label: "玄武区",
                        value: "320102"
                      },
                      {
                        label: "秦淮区",
                        value: "320104"
                      },
                      {
                        label: "建邺区",
                        value: "320105"
                      }
                    ]
                  },
                  {
                    label: "无锡市",
                    value: "320200",
                    children: [
                      {
                        label: "锡山区",
                        value: "320205"
                      },
                      {
                        label: "惠山区",
                        value: "320206"
                      },
                      {
                        label: "滨湖区",
                        value: "320211"
                      }
                    ]
                  },
                  {
                    label: "徐州市",
                    value: "320300",
                    children: [
                      {
                        label: "鼓楼区",
                        value: "320302"
                      },
                      {
                        label: "云龙区",
                        value: "320303"
                      },
                      {
                        label: "贾汪区",
                        value: "320305"
                      }
                    ]
                  }
                ]
              }
            ]

function BasicCascader() {
  const [open, setOpen] = useState(false)
  const [value, setValue] = useState<string[]>([])
  const [fieldValue, setFieldValue] = useState("")
  const { columns } = useCascader({ value, depth: 3, options: area })
  return (
    <>
      <Field
        readonly
        label="选项值"
        placeholder="请选择地区"
        value={fieldValue}
        rightIcon={<ArrowRight />}
        onClick={() => setOpen(true)}
      />
      <Popup open={open} rounded placement="bottom" onClose={setOpen}>
        <Popup.Close />
        <Cascader
          value={value}
          onSelect={setValue}
          onChange={(values, options) => {
            setOpen(false)
            setFieldValue(
              _.join(
                _.map(options, ({ children }) => children),
                "/",
              ),
            )
          }}
        >
          <Cascader.Header>请选择所在地区</Cascader.Header>
          {
            _.map(columns, (options, index) => (
              <Cascader.Tab key={index}>
                {
                  _.map(options, (option) => (
                    <Cascader.Option key={option.value} value={option.value}>
                      {option.label}
                    </Cascader.Option>
                  ))
                }
              </Cascader.Tab>
            ))
          }
        </Cascader>
      </Popup>
    </>
  )
}

**Comment by idujiawei** [comment]
onChange 也有问题，当选择到最后一项后，在回到前面的项，切换选择项，第一次并不会触发onChange事件

**Comment by idujiawei** [comment]
onChange 也有问题，当选择到最后一项后，在回到前面的项，切换选择项，第一次并不会触发onChange事件

**Comment by tgioer** [comment]
嗯，这确实是个bug

**Comment by tgioer** [comment]
> 嗯，在选择最后一项后，在返回到上一项，然后再点刚刚选择的那一项会存在点击没反映的问题。（这确实是个BUG）

https://github.com/mallfoundry/taroify/pull/484
