### ISSUE TITLE
包尺寸太大了[Bug Report] 

### ISSUE THREAD

**Issue by codthing** [mallfoundry/taroify#469]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

^0.0.29-alpha.7

### 描述一下您遇到的问题以及重现步骤

![image](https://user-images.githubusercontent.com/16655229/164801186-8fbe7a40-d59f-47e3-a9ae-edbfee4c81dc.png)

VSCode中检测到这个包很大很大，为什么这个包那么大，有没有办法解决一下，让它小一点

**Comment by tgioer** [comment]
使用按需加载也这样嘛？
https://taroify.gitee.io/taroify.com/quickstart/#%E5%BC%95%E5%85%A5%E7%BB%84%E4%BB%B6
```tsx
// babel.config.js
module.exports = {
  plugins: [
    [
      "import",
      {
        libraryName: "@taroify/core",
        libraryDirectory: "",
        style: true,
      },
      "@taroify/core",
    ],
    [
      "import",
      {
        libraryName: "@taroify/icons",
        libraryDirectory: "",
        camel2DashComponentName: false,
        style: () => "@taroify/icons/style",
      },
      "@taroify/icons",
    ],
  ],
};
```

**Comment by codthing** [comment]
@tgioer 
是的，配置了按需加载

**Comment by WangJM001** [comment]
vscode 插件始终显示的整个包的大小，配置了按需加载实际打包大小没这么大的

**Comment by codthing** [comment]
@WangJM001 
谢谢提醒，这个我没有在插件方得到确认。

**Comment by WangJM001** [comment]
你用webpack-bundle-analyzer 分析下就明白了

**Comment by codthing** [comment]
@WangJM001 
谢谢提示，我今天测试了Taro和Remax的开发体验，我感觉还是Remax更友好一点。

**Comment by codedart2018** [comment]
> 

remax输在ui上。

**Comment by yanchengqu** [comment]
> 使用按需加载也这样嘛？ https://taroify.gitee.io/taroify.com/quickstart/#%E5%BC%95%E5%85%A5%E7%BB%84%E4%BB%B6
> 
> ```tsx
> // babel.config.js
> module.exports = {
>   plugins: [
>     [
>       "import",
>       {
>         libraryName: "@taroify/core",
>         libraryDirectory: "",
>         style: true,
>       },
>       "@taroify/core",
>     ],
>     [
>       "import",
>       {
>         libraryName: "@taroify/icons",
>         libraryDirectory: "",
>         camel2DashComponentName: false,
>         style: () => "@taroify/icons/style",
>       },
>       "@taroify/icons",
>     ],
>   ],
> };
> ```

按需加载不起作用，包非常大

**Comment by yanchengqu** [comment]
> 使用按需加载也这样嘛？ https://taroify.gitee.io/taroify.com/quickstart/#%E5%BC%95%E5%85%A5%E7%BB%84%E4%BB%B6
> 
> ```tsx
> // babel.config.js
> module.exports = {
>   plugins: [
>     [
>       "import",
>       {
>         libraryName: "@taroify/core",
>         libraryDirectory: "",
>         style: true,
>       },
>       "@taroify/core",
>     ],
>     [
>       "import",
>       {
>         libraryName: "@taroify/icons",
>         libraryDirectory: "",
>         camel2DashComponentName: false,
>         style: () => "@taroify/icons/style",
>       },
>       "@taroify/icons",
>     ],
>   ],
> };
> ```

配置了，但是包还是非常大
