### ISSUE TITLE
[Bug Report] prod 下 Input onChange 事件报错

### ISSUE THREAD

**Issue by WangJM001** [mallfoundry/taroify#470]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

微信开发者工具，真机调试

### 你正在使用的 Taroify 版本是多少

0.0.29-alpha.7

### 描述一下您遇到的问题以及重现步骤

input onChange prod环境下报错，dev环境没问题
![CleanShot 2022-04-23 at 21 08 38@2x](https://user-images.githubusercontent.com/20501316/164895926-5ac8f31f-b1a5-47f6-b8b3-d53bfc63245b.png)
<img width="780" alt="CleanShot 2022-04-23 at 21 10 40@2x" src="https://user-images.githubusercontent.com/20501316/164895965-a5c00a5a-1094-4cb4-8357-59ece8baa31b.png">

**Comment by tgioer** [comment]
我这测试的没问题，Input 内部没有使用 `Date.now()` 的代码

**Comment by WangJM001** [comment]
确实和组件库无关，使用lodash导致的问题
