### ISSUE TITLE
提个tabs需求.希望可以加个参数固定tabs数量或禁止滑动

### ISSUE THREAD

**Issue by codedart2018** [mallfoundry/taroify#473]
在某些情况下，我们并不希望tabs或以滑动。默认固定的是5个，但可能刚好6个超出去一点。这个时候我们的情况就希望它能固定下来。因为一个去滑动从某种情况上来说不是太合理。希望加个参数禁止滑动全部给展示出来！
比如这样
<img width="382" alt="image" src="https://user-images.githubusercontent.com/12706830/165216180-02f751f3-41d1-4d74-86c1-3140dfc70361.png">
这样，被挡住了，不是太希望想要的。
<img width="392" alt="image" src="https://user-images.githubusercontent.com/12706830/165216301-aa62a426-ca6b-421f-b92d-cead2bff92a1.png">

**Comment by Pilotager** [comment]
0.1.0-alpha.8 版本发布
