### ISSUE TITLE
[Feature Request] Calendar 设置DayOfWeek固定，Subtitle随滑动变化

### ISSUE THREAD

**Issue by Laotree** [mallfoundry/taroify#475]
### 使用示例，包括组件或 Hooks

```

不设置固定高度时，滑动之后，星期数没有固定

```

<img width="368" alt="image" src="https://user-images.githubusercontent.com/16837634/165330144-c3c3a31f-3e8c-43b9-88c4-234b5a638fe4.png">

```

style={{maxHeight:"400px"}} 
设置固定高度后，副标题的年月没有跟随滑动变化

```

<img width="368" alt="image" src="https://user-images.githubusercontent.com/16837634/165330027-3867fb67-19ea-4560-a149-123ee988da5a.png">

### 解决方案

* 不设置固定高度时，滑动之后，星期数固定
* 固定高度后，副标题的年月跟随滑动变化

**Comment by tgioer** [comment]
使用
``tsx
style={{height:"400px"}} 
```
再试试

**Comment by Laotree** [comment]
> 使用
> 
> ```tsx
> style={{height:"400px"}} 
> ```
> 
> 再试试

it works
