### ISSUE TITLE
[Bug Report] Avatar 组件中的图片出现了拉伸问题

### ISSUE THREAD

**Issue by ShibaPipi** [mallfoundry/taroify#478]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.29-alpha.7

### 描述一下您遇到的问题以及重现步骤

Avatar 组件中的图片出现了拉伸问题，查看微信开发这工具发现，Avatar 组件内部的 Image 组件虽然增加了 class="taroify-image"，但是没有引入对应的样式（可能是 sass ?）。

### 你知道如何解决这个问题吗

Yes

### 您是否愿意参与修复这个问题，并创建一个 PR

Yes

### 修复这个问题的解决方案

个人觉得自己知道解决方案，也想提交 PR，不过本人之前没有提交过 PR，是个菜鸟，还是请官方团队在 Avatar 组件中引入 Image 的样式，尝试是否能修复此问题，谢谢。

**Comment by tgioer** [comment]
您可以花几分钟尝试下提交一个 PR，从此开启一个美好的开源事业。

**Comment by ShibaPipi** [comment]
> 您可以花几分钟尝试下提交一个 PR，从此开启一个美好的开源事业。

我来努力尝试一下，其实我也想提一个 PR 的。
