### ISSUE TITLE
[Bug Report] Radio搭配Cell.Group使用时，监听Cell点击事件修改Radio.Group的value不会触发onChange事件

### ISSUE THREAD

**Issue by jhxxs** [mallfoundry/taroify#479]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

微信小程序/开发者工具

### 你正在使用的 Taroify 版本是多少

^0.0.29-alpha.7

### 描述一下您遇到的问题以及重现步骤

在使用[`Radio`组件搭配`Cell.Group`](https://taroify.github.io/taroify.com/components/radio/#%E4%B8%8E-cell-%E7%BB%84%E4%BB%B6%E4%B8%80%E8%B5%B7%E4%BD%BF%E7%94%A8)使用时，按照demo的写法发现，点击cell不会触发radio选中，只有点击radio本身才会触发选中效果。
![radiogroup](https://user-images.githubusercontent.com/7448223/165674856-949c7b2e-820f-4a4b-8c79-3654a0b286b0.gif)

而我尝试监听cell的`onClick`事件来动态修改`Radio.Group`的`value`，发现`Radio.Group`不会触发`onChange`事件了

代码示例:
```tsx
const [state, setState] = useState<T["value"]>(value)
return (
  <Radio.Group
    defaultValue={state}
    value={state}
    onChange={(e) => {
      console.log("change", e)
    }}
  >
  <Cell.Group bordered={false}>
    {list.map((v) => (
      <Cell
        className={css`
          padding-left: 32px;
          padding-right: 32px;
        `}
        onClick={() => {
          setState(v.value)
        }}
        clickable
        title={
          <View
            className={css`
              font-weight: 500;
              font-size: 30px;
              color: ${Theme.textFirst};
            `}
          >
            {v.label ?? v.value}
          </View>
        }
        align="center"
      >
        <Radio name={v.value} />
      </Cell>
    ))}
  </Cell.Group>
  </Radio.Group>
)
```

录像效果如下:
![radiogroup2](https://user-images.githubusercontent.com/7448223/165675187-8a0b5847-58ef-42a9-af6e-19e3e5fe0295.gif)

### 你知道如何解决这个问题吗

No

### 您是否愿意参与修复这个问题，并创建一个 PR

No

**Comment by tgioer** [comment]
Cell 和 Radio 是两个独立的组件，在内部没有做任何的关联。
如果需要点击 Cell 触发 Radio，可以自行监听 Cell 的 onClick 事件，然后设置 Radio 的 value。
设置 Radio 的 value 不会触发 Radio 的 onChange 事件。

**Comment by tgioer** [comment]
这一切应该都符合正常逻辑，如果你有需要，可以自行通过 Cell 和 Radio 组件封装一个 RadioCell 组件。
