### ISSUE TITLE
能否给Form.controll加一个依赖属性，用于联动功能

### ISSUE THREAD

**Issue by leifeng** [mallfoundry/taroify#481]
### 使用示例，包括组件或 Hooks

比如有2个表单项（Form.Item）
1. 单选框A
2. 单选框B
这 2 个单选数据都是由接口返回的，如果 B 的数据依赖 A 的选项，当 A 发生变化时，在B里可以或取 A 的值，从而调用接口。

能否给 FormControl 添加额外的属性 `deps={["A"]}`，传入依赖的表单项的key，依赖变化时可以触发B的渲染。

目前看源码里
```
//只有以下变化才会触发渲染，就算我使用自定义表单组件，传额外的值也不会触发渲染
    children,
    formName,
    name,
    onDelegatingBlur,
    onDelegatingChange,
    validateStatus,
    value,
```

### 解决方案

1.要不提供一个deps的属性用于联动
2.要不FormControl的渲染可以添加额外的依赖

**Comment by tgioer** [comment]
其实就是想监控一个表单项的变化触发？

**Comment by leifeng** [comment]
是的
