### ISSUE TITLE
List滚动会重复加载数据，并频繁触发 Cannot read property 'overflowY' of null

### ISSUE THREAD

**Issue by bs32g1038** [mallfoundry/taroify#482]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.29-alpha.8

### 描述一下您遇到的问题以及重现步骤

使用List，当进行滚动加载时，会多次重复加载请求，应该对该执行进行锁定

![image](https://user-images.githubusercontent.com/16550983/166894774-e63b54aa-bc09-4d32-b305-c338e0de048a.png)

**Comment by tgioer** [comment]
使用 useRef 也会这样嘛？
