### ISSUE TITLE
[Bug Report] 在支付宝小程序中，IndexList 的索引栏的点击事件未生效

### ISSUE THREAD

**Issue by airbreak** [mallfoundry/taroify#487]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

支付宝小程序

### 平台/设备/浏览器

支付宝小程序开发工具和支付宝app

### 你正在使用的 Taroify 版本是多少

0.0.29-alpha.3

### 描述一下您遇到的问题以及重现步骤

打包成支付宝小程序后，IndexList  右侧的索引点击事件未生效。初步判断问题可能出现在以下代码片段：   
```
function getClientCoordinates(event) {
      var clientX = event.clientX,
          clientY = event.clientY,
          touches = event.touches;

      if (clientX && clientY) {
        return {
          clientX: clientX,
          clientY: clientY
        };
      }

      return touches[0];
    }
```
支付宝小程序中clientX、  clientY  未挂载在event句柄中，而是添加了一层 detail。 同时touches也为undefined，因此函数未生效。

**Comment by loethen** [comment]
百度小程序也不支持

**Comment by Pilotager** [comment]
新版本可以了
