### ISSUE TITLE
[Bug Report] 使用按需加载方式，ShareSheet 组件的样式需要手动引入

### ISSUE THREAD

**Issue by shaolongcai** [mallfoundry/taroify#489]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.29-alpha.8

### 描述一下您遇到的问题以及重现步骤

在引入了转换插件后（方式一引入），用 shareSheet 组件 一定要引入

` import "@taroify/core/share-sheet/style`

否则样式将会错乱。

其他组件经验证没有这个问题，可以不需要另外引入样式

**Comment by tgioer** [comment]
不应该存在这样的问题，如果有问题。可以提供一个测试示例
