### ISSUE TITLE
[Feature Request] SwipeCell需要加入滑动拦截

### ISSUE THREAD

**Issue by jhxxs** [mallfoundry/taroify#494]
### 使用示例，包括组件或 Hooks

目前在实际使用过程中发现`SwipeCell`组件没有做滑动拦截处理，导致左右滑动时会触发页面的滚动

https://user-images.githubusercontent.com/7448223/168509912-46f7e71c-5bd2-4fad-9976-55e60ba92cd4.mp4

### 解决方案

希望可以加入滑动拦截

**Comment by ziqiya** [comment]
6，你直接加个 catchMove:true 有没有考虑过SwipeCell 在 PullFresh 列表里的下拉问题，你这一加现在所有的下拉列表里的SwipeCell 都无法触发下拉刷新的拖动事件了（根本没办法往下拖）

**Comment by jhxxs** [comment]
> 6，你直接加个 catchMove:true 有没有考虑过SwipeCell 在 PullFresh 列表里的下拉问题，你这一加现在所有的下拉列表里的SwipeCell 都无法触发下拉刷新的拖动事件了（根本没办法往下拖）

你再提个 pr 改回来吧哈哈
