### ISSUE TITLE
[Bug Report] loading.scss compiled warning

### ISSUE THREAD

**Issue by umcai** [mallfoundry/taroify#496]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5

### 平台/设备/浏览器

ubuntu 20.04

### 你正在使用的 Taroify 版本是多少

0.0.29-alpha.8

### 描述一下您遇到的问题以及重现步骤

![image](https://user-images.githubusercontent.com/11835233/168944213-18a174b2-fdc8-41c7-ac60-5594b843cd33.png)

### 你知道如何解决这个问题吗

Yes

### 您是否愿意参与修复这个问题，并创建一个 PR

Yes

### 修复这个问题的解决方案

[The line](https://github.com/mallfoundry/taroify/blob/f9e24e34642a95e041b9b276a281a393a413761b/packages/core/src/loading/loading.scss#L42) changed to 
```
opacity: calc(1 - (0.75 / 12) * ($i - 1));
```

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/issues/504
