### ISSUE TITLE
[Bug Report] scss文件编辑警告错误

### ISSUE THREAD

**Issue by momtboy** [mallfoundry/taroify#498]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

windows,微信小程序

### 你正在使用的 Taroify 版本是多少

3.3.20

### 描述一下您遇到的问题以及重现步骤

![image](https://user-images.githubusercontent.com/9612078/168979032-f5282050-e126-4b34-9ab3-26550628c7a4.png)

`chunk common [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroify/index.scss
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroifyarea/index.scss

chunk common [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroifyindex.scss
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroifyarea/index.scss

chunk common [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroify-view/index.scss
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroifyn/index.scss
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroifyn-base/index.scss
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroifyng/index.scss

chunk common [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroifyr/index.scss
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroifyn/index.scss
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroifyn-base/index.scss
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroifyng/index.scss

chunk common [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./src/components/AmNav/
 * css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-0-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroifyn/index.scss
e-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-0-4!./node_modules/@taroify/core/loading/index.scss`

**Comment by tgioer** [comment]
小程序是多页面应用，所以会存在这个问题。没办法解决
