### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by yanzulee** [mallfoundry/taroify#500]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.0.29-alpha.8

### 描述一下您遇到的问题以及重现步骤

IndexList索引栏只支持数据滑动触顶的时候右边slider才会改变，现有的需求IndexList并不是在全屏下，可能是中间的一个区域，现在不支持传递到触及位置而做相应slider的改变，如图

![Uploading image.png…]()

### 你知道如何解决这个问题吗

Yes

**Comment by tgioer** [comment]
IndexList 不支持嵌套在 View，目前只支持全局
