### ISSUE TITLE
[weapp] NoticeBar滚动一到两次后就停止滚动

### ISSUE THREAD

**Issue by yoonzm** [mallfoundry/taroify#501]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

微信小程序taroify

### 你正在使用的 Taroify 版本是多少

微信小程序taroify demo

### 描述一下您遇到的问题以及重现步骤

NoticeBar滚动一到两次后就停止滚动

**Comment by hqwlkj** [comment]
有没有遇到 页面切换后 NoticeBar 就不滚动了的问题

**Comment by hbztd** [comment]
> 有没有遇到 页面切换后 NoticeBar 就不滚动了的问题

可以手动调用reset

**Comment by hbztd** [comment]
> ### 问题出在哪个包
> @taroify/core
> 
> ### 问题出在哪个平台/设备/浏览器
> 微信小程序
> 
> ### 平台/设备/浏览器
> 微信小程序taroify
> 
> ### 你正在使用的 Taroify 版本是多少
> 微信小程序taroify demo
> 
> ### 描述一下您遇到的问题以及重现步骤
> NoticeBar滚动一到两次后就停止滚动
> 
> ### 如果可能的话，请包含一个代码框的链接与复制的问题
> _No response_
> 
> ### 你知道如何解决这个问题吗
> _No response_
> 
> ### 您是否愿意参与修复这个问题，并创建一个 PR
> _No response_
> 
> ### 修复这个问题的解决方案
> _No response_

未复现

**Comment by hbztd** [comment]
#623
