### ISSUE TITLE
Form > Input 校验未通过时，placeholder不应该是 error 颜色

### ISSUE THREAD

**Issue by lenghuaping** [mallfoundry/taroify#503]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

mac os 12.3.1 / chrome latest

### 你正在使用的 Taroify 版本是多少

0.0.29-alpha.8

## demo示例即可复现到。
<img width="391" alt="image" src="https://user-images.githubusercontent.com/31724313/169970630-66085b39-a27c-410b-b575-ea06e779c1b8.png">

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/31724313/169971162-8b3b8153-ff2f-4796-b756-3165e56bab6d.png">

### 如果可能的话，请包含一个代码框的链接与复制的问题

https://taroify.gitee.io/taroify.com/components/form/

### 你知道如何解决这个问题吗

Yes

### 您是否愿意参与修复这个问题，并创建一个 PR

Yes

### 修复这个问题的解决方案

Input 校验未通过时，placeholder不应该是 error 颜色

**Comment by tgioer** [comment]
好的，下个版本会和 vant3+ 保持一致

**Comment by chengluliu** [comment]
0.1.0-alpha.1   好像没有更新这个问题

**Comment by Feafortecsy** [comment]
> 0.1.0-alpha.1 好像没有更新这个问题

我通过样式覆盖处理的。

``` less
  .taroify-input--danger,
  .taroify-input__placeholder--danger {
    color: #999;
  }
```

**Comment by chengluliu** [comment]
> 

谢谢 我也去试试先.  可以临时解决问题

**Comment by chengluliu** [comment]
> > 0.1.0-alpha.1 好像没有更新这个问题
> 
> 我通过样式覆盖处理的。
> 
> ```css-less
>   .taroify-input--danger,
>   .taroify-input__placeholder--danger {
>     color: #999;
>   }
> ```

谢谢 我也去试试先. 可以临时解决问题

**Comment by Pilotager** [comment]
https://github.com/mallfoundry/taroify/pull/573
