### ISSUE TITLE
百度小程序日历组件 初始化设置默认值，没有跳转到对应月份

### ISSUE THREAD

**Issue by qing-zhi** [mallfoundry/taroify#507]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

百度小程序

### 你正在使用的 Taroify 版本是多少

^0.0.29-alpha.9

### 描述一下您遇到的问题以及重现步骤

指定默认日期是8月7号到8月9号，用户打开日历页面应该跳转到8月，但实际是没有
`
const minDate = new Date();
  const maxDate = dayjs(minDate).add(11, 'month');

  return (
    <Calendar
      title='日历'
      type='range'
      min={minDate}
      defaultValue={[new Date('2022-08-07'),new Date('2022-08-09')]}
      max={new Date(maxDate)}
      style={{ height: "600px" }}
      subtitle={false}
    />
  )
`

**Comment by Pilotager** [comment]
v0.1.1-alpha.6
