### ISSUE TITLE
[Bug Report] 文档中下列表演示demo，下拉刷新会触发List组件的onLoad

### ISSUE THREAD

**Issue by zhen-one** [mallfoundry/taroify#509]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5

### 平台/设备/浏览器

Chrome

### 你正在使用的 Taroify 版本是多少

文档版本

### 描述一下您遇到的问题以及重现步骤

官网文档  List组件 下拉刷新示例
https://taroify.gitee.io/taroify.com/components/list/

**Comment by tgioer** [comment]
没看懂什么意思，下拉刷新不应该触发 onLoad 事件？
