### ISSUE TITLE
taro 飞书小程序上 引入icon会报错

### ISSUE THREAD

**Issue by mrchenxxx** [mallfoundry/taroify#511]
### 问题出在哪个包

@taroify/icons

### 问题出在哪个平台/设备/浏览器

百度小程序

### 平台/设备/浏览器

我开发的是飞书小程序

### 你正在使用的 Taroify 版本是多少

6.1.11

### 描述一下您遇到的问题以及重现步骤

taro 飞书小程序上 引入icon会报错
找不到模块“@taroify/icons”或其相应的类型声明。ts(2307)

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/520
