### ISSUE TITLE
Form和表单在h5中输入内容失去焦点就清除了内容

### ISSUE THREAD

**Issue by zhangfu-git** [mallfoundry/taroify#517]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5

### 平台/设备/浏览器

MAC 谷歌

### 你正在使用的 Taroify 版本是多少

^0.1.0-alpha.0

### 描述一下您遇到的问题以及重现步骤

使用了文档里面的Form代码，在浏览器中，输入内容，失去焦点后Input的内容被清空

**Comment by tgioer** [comment]
没遇到，请提供测试代码
