### ISSUE TITLE
Taro v3.4.12安装配置以后报错

### ISSUE THREAD

**Issue by hcweb** [mallfoundry/taroify#518]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

 "@taroify/core": "^0.1.0-alpha.0",

### 描述一下您遇到的问题以及重现步骤

编译  发现入口  src/app.jsx
编译  发现页面  src/pages/index/index.jsx
🙅   编译失败. 2022/6/23 23:32:03

./node_modules/@taroify/core/loading/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@tarojs/mini-runner/node_modules/sass-loader/dist/cjs.js):
SassError: Undefined operation "calc(0.75 / 12) * 0".
   ╷
42 │           opacity: 1 - calc(0.75 / 12) * ($i - 1);
   │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@taroify\core\loading\loading.scss 42:24  @import
  node_modules\@taroify\core\loading\index.scss 1:9      root stylesheet

监听文件修改中...

./node_modules/@taroify/core/loading/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@tarojs/mini-runner/node_modules/sass-loader/dist/cjs.js):
SassError: Undefined operation "calc(0.75 / 12) * 0".
   ╷
42 │           opacity: 1 - calc(0.75 / 12) * ($i - 1);
   │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@taroify\core\loading\loading.scss 42:24  @import
  node_modules\@taroify\core\loading\index.scss 1:9      root stylesheet
    at D:\taro_workspace\qjyb\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\taro_workspace\qjyb\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\taro_workspace\qjyb\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\taro_workspace\qjyb\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\taro_workspace\qjyb\node_modules\@tarojs\mini-runner\node_modules\sass-loader\dist\index.js:62:7
    at Function.call$2 (D:\taro_workspace\qjyb\node_modules\@tarojs\mini-runner\node_modules\sass\sass.dart.js:92571:16)
    at _render_closure1.call$2 (D:\taro_workspace\qjyb\node_modules\@tarojs\mini-runner\node_modules\sass\sass.dart.js:81074:12)
    at _RootZone.runBinary$3$3 (D:\taro_workspace\qjyb\node_modules\@tarojs\mini-runner\node_modules\sass\sass.dart.js:27256:18)
    at _FutureListener.handleError$1 (D:\taro_workspace\qjyb\node_modules\@tarojs\mini-runner\node_modules\sass\sass.dart.js:25812:19)
    at _Future__propagateToListeners_handleError.call$0 (D:\taro_workspace\qjyb\node_modules\@tarojs\mini-runner\node_modules\sass\sass.dart.js:26110:49)
    at Object._Future__propagateToListeners (D:\taro_workspace\qjyb\node_modules\@tarojs\mini-runner\node_modules\sass\sass.dart.js:4536:77)    
    at _Future._completeError$2 (D:\taro_workspace\qjyb\node_modules\@tarojs\mini-runner\node_modules\sass\sass.dart.js:25942:9)
    at _AsyncAwaitCompleter.completeError$2 (D:\taro_workspace\qjyb\node_modules\@tarojs\mini-runner\node_modules\sass\sass.dart.js:25596:12)   
    at Object._asyncRethrow (D:\taro_workspace\qjyb\node_modules\@tarojs\mini-runner\node_modules\sass\sass.dart.js:4335:17)
    at D:\taro_workspace\qjyb\node_modules\@tarojs\mini-runner\node_modules\sass\sass.dart.js:12852:20
    at _wrapJsFunctionForAsync_closure.$protected (D:\taro_workspace\qjyb\node_modules\@tarojs\mini-runner\node_modules\sass\sass.dart.js:4360:15)
 @ ./node_modules/@taroify/core/loading/style/index.js 2:0-23
 @ ./node_modules/@taroify/core/button/style/index.js
 @ ./node_modules/babel-loader/lib!./src/pages/index/index.jsx
 @ ./src/pages/index/index.jsx

node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.

下面已安装的扩展
 "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@taroify/core": "^0.1.0-alpha.0",
    "@tarojs/components": "3.2.13",
    "@tarojs/plugin-framework-react": "^3.4.12",
    "@tarojs/react": "3.2.13",
    "@tarojs/runtime": "3.2.13",
    "@tarojs/taro": "3.2.13",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "sass": "^1.53.0",
    "sass-loader": "^13.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/mini-runner": "3.2.13",
    "@tarojs/webpack-runner": "3.2.13",
    "@types/react": "^17.0.2",
    "@types/webpack-env": "^1.13.6",
    "babel-plugin-import": "^1.13.5",
    "babel-preset-taro": "3.2.13",
    "eslint": "^6.8.0",
    "eslint-config-taro": "3.2.13",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "stylelint": "9.3.0"
  }

babel.config.js配置信息
module.exports = {
  presets: [
    ['taro', {
      framework: 'react',
      ts: false
    }]
  ],
  plugins: [
    [
      "import",
      {
        libraryName: "@taroify/core",
        libraryDirectory: "",
        style: true,
      },
      "@taroify/core",
    ],
    [
      "import",
      {
        libraryName: "@taroify/icons",
        libraryDirectory: "",
        camel2DashComponentName: false,
        style: () => "@taroify/icons/style",
      },
      "@taroify/icons",
    ],
  ],
}

**Comment by skyliwq** [comment]
同样问题 待解决

**Comment by tgioer** [comment]
Taro CLI 也是 v3.4.12 吗?

**Comment by skyliwq** [comment]
taro v3.4.3

**Comment by skyliwq** [comment]
等你更新呢 大神

**Comment by tgioer** [comment]
更新 TaroCLI 至 3.4.10 以上

**Comment by Vinsurs** [comment]
@tgioer  升级TaroCLI 至 3.4.12 以上 并没有作用，错误依然存在

**Comment by skyliwq** [comment]
是的

**Comment by Vinsurs** [comment]
@skyliwq @tgioer 请问这个问题解决了吗

**Comment by effortcheep** [comment]
>

不光是 CLI 到最新的，项目本身 也要到 3.4.12 
到项目目录下 执行 taro update project 即可

**Comment by effortcheep** [comment]
> @skyliwq @tgioer 请问这个问题解决了吗

你要升级项目里面的  taro 版本

**Comment by b-yp** [comment]
同样问题前来求助，但是我的 taro 版本已经升级到 3.6.30 了

**Comment by b-yp** [comment]
> 同样问题前来求助，但是我的 taro 版本已经升级到 3.6.30 了

我将 dist 目录上删除之后重新 dev  一下就好了
