### ISSUE TITLE
飞书小程序引入图标组件显示方块

### ISSUE THREAD

**Issue by mrchenxxx** [mallfoundry/taroify#519]
### 问题出在哪个包

@taroify/icons

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

我开发的是飞书小程序

### 你正在使用的 Taroify 版本是多少

最新的

### 描述一下您遇到的问题以及重现步骤

![image](https://user-images.githubusercontent.com/44868578/175806312-5b658a34-1855-41f3-8224-2c245781d1b6.png)

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/520
