### ISSUE TITLE
在支付宝小程序中使用（List、swiper）会出现Object(...)(...).fields is not a function

### ISSUE THREAD

**Issue by whiteGreat** [mallfoundry/taroify#521]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

支付宝小程序

### 你正在使用的 Taroify 版本是多少

0.0.29-alpha.9     0.1.0-alpha.1

### 描述一下您遇到的问题以及重现步骤

Uncaught (in promise) TypeError: Object(...)(...).fields is not a function
    at 127.0.0.1:63957/index.worker.js?hash=b51acef6&from_service_worker=true&url=file%3A%2F%2F%2Findex.html&ap_framework_sceneId=0000:25438
    at new Promise (<anonymous>)
    at getComputedStyle (127.0.0.1:63957/index.worker.js?hash=b51acef6&from_service_worker=true&url=file%3A%2F%2F%2Findex.html&ap_framework_sceneId=0000:25437)
    at 127.0.0.1:63957/index.worker.js?hash=b51acef6&from_service_worker=true&url=file%3A%2F%2F%2Findex.html&ap_framework_sceneId=0000:23987
    at 127.0.0.1:63957/index.worker.js?hash=b51acef6&from_service_worker=true&url=file%3A%2F%2F%2Findex.html&ap_framework_sceneId=0000:16067
    at e.executeFunctionAsync (runtime.bundle.js/:1)
    at runtime.bundle.js/:1

### 你知道如何解决这个问题吗

No

**Comment by LBJDJW** [comment]
> 现在使用的taro版本是@tarojs/cli": "3.4.11", 在"@taroify/core": "^0.0.29-alpha.9","@taroify/core": "^0.1.0-alpha.1"中都存在相同问题

大佬，我用的List组件 钉钉小程序也是报这个错误,有解决方案不 请教一下大佬  `vendors.js:15139 Uncaught (in promise) TypeError: Object(...)(...).fields is not a function
    at vendors.js:15139:1
    at new Promise (<anonymous>)
    at getComputedStyle (vendors.js:15138:1)
    at _callee$ (index.js:492:1)
    at tryCatch (vendors.js:646:1)
    at Generator.<anonymous> (vendors.js:730:1)
    at Generator.next (vendors.js:671:1)
    at asyncGeneratorStep (index.js:433:1)
    at _next (index.js:452:1)
    at index.js:457:1
(anonymous) @ vendors.js:15139
getComputedStyle @ vendors.js:15138
_callee$ @ index.js:492
tryCatch @ vendors.js:646
(anonymous) @ vendors.js:730
(anonymous) @ vendors.js:671
asyncGeneratorStep @ index.js:433
_next @ index.js:452
(anonymous) @ index.js:457
(anonymous) @ index.js:449
_getScrollParent @ index.js:519
getScrollParent @ index.js:472
_callee$ @ index.js:342
tryCatch @ vendors.js:646
(anonymous) @ vendors.js:730
(anonymous) @ vendors.js:671
asyncGeneratorStep @ index.js:221
_next @ index.js:240
(anonymous) @ index.js:245
(anonymous) @ index.js:237
(anonymous) @ taro.js:7918
e.executeFunctionAsync @ (index):1
(anonymous) @ (index):1
Promise.then (async)
asyncGeneratorStep @ index.js:230
_next @ index.js:240
(anonymous) @ index.js:245
(anonymous) @ index.js:237
(anonymous) @ taro.js:7918
e.executeFunctionAsync @ (index):1
(anonymous) @ (index):1
setTimeout (async)
e.setTimeout @ (index):1
setTimeout @ (index):1
e.setTimeout @ af-appx.worker.min.js:26
timerFunc @ taro.js:7917
next @ taro.js:7942
(anonymous) @ taro.js:7945
e.executeFunctionAsync @ (index):1
(anonymous) @ (index):1
setTimeout (async)
e.setTimeout @ (index):1
setTimeout @ (index):1
e.setTimeout @ af-appx.worker.min.js:26
next @ taro.js:7944
(anonymous) @ taro.js:7945
e.executeFunctionAsync @ (index):1
(anonymous) @ (index):1
setTimeout (async)
e.setTimeout @ (index):1
setTimeout @ (index):1
e.setTimeout @ af-appx.worker.min.js:26
next @ taro.js:7944
(anonymous) @ taro.js:7945
e.executeFunctionAsync @ (index):1
(anonymous) @ (index):1
setTimeout (async)
e.setTimeout @ (index):1
setTimeout @ (index):1
e.setTimeout @ af-appx.worker.min.js:26
next @ taro.js:7944
(anonymous) @ taro.js:7945
e.executeFunctionAsync @ (index):1
(anonymous) @ (index):1
setTimeout (async)
e.setTimeout @ (index):1
setTimeout @ (index):1
e.setTimeout @ af-appx.worker.min.js:26
next @ taro.js:7944
(anonymous) @ taro.js:7945
e.executeFunctionAsync @ (index):1
(anonymous) @ (index):1
setTimeout (async)
e.setTimeout @ (index):1
setTimeout @ (index):1
e.setTimeout @ af-appx.worker.min.js:26
next @ taro.js:7944
nextTick @ taro.js:7949
(anonymous) @ index.js:330
Gg @ vendors.js:29824
Fh @ vendors.js:29871
Ch @ vendors.js:29858
Xc @ vendors.js:29718
Ad @ vendors.js:29851
df @ vendors.js:29769
(anonymous) @ index.js:673
callback @ taro.js:480
(anonymous) @ taro.js:7590
safeExecute @ taro.js:7589
exec @ taro.js:7781
config.<computed> @ taro.js:7786
(anonymous) @ af-appx.worker.min.js:26
Qn @ af-appx.worker.min.js:26
(anonymous) @ af-appx.worker.min.js:26
runBatch @ af-appx.worker.min.js:26
batchedUpdates @ af-appx.worker.min.js:26
executeUserFunction @ af-appx.worker.min.js:26
firePageEvent @ af-appx.worker.min.js:26
fireLegacyEvent @ af-appx.worker.min.js:26
onPageScroll @ af-appx.worker.min.js:26
processData @ af-appx.worker.min.js:26
onData @ af-appx.worker.min.js:26
onMessage @ af-appx.worker.min.js:26
port.port.onmessage @ af-appx.worker.min.js:26
e.executeFunctionAsync @ (index):1
e.handleMessageFromRender4MessagePort @ (index):1
e.handleMessageFromRender @ (index):1
t.postMessage2Host @ (index):1
e.postMessage2Host @ (index):1
e.handleAPI4PostMessage @ (index):1
e.bridgeCall @ (index):1
e.callBridgePluginAsyncInternal @ (index):1
(anonymous) @ (index):1
setTimeout (async)
e.bridgeCall @ (index):1
t.invokeBridgeAsync @ (index):1
call @ (index):1
a.onmessage @ af-appx.min.js:14
Show 40 more frames
vendors.js:15139 Uncaught (in promise) TypeError: Object(...)(...).fields is not a function
    at vendors.js:15139:1
    at new Promise (<anonymous>)
    at getComputedStyle (vendors.js:15138:1)
    at _callee$ (index.js:492:1)
    at tryCatch (vendors.js:646:1)
    at Generator.<anonymous> (vendors.js:730:1)
    at Generator.next (vendors.js:671:1)
    at asyncGeneratorStep (index.js:433:1)
    at _next (index.js:452:1)
    at index.js:457:1`
