### ISSUE TITLE
[Bug Report] taro3.5中css编译报错

### ISSUE THREAD

**Issue by bingtsingw** [mallfoundry/taroify#527]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

小程序

### 你正在使用的 Taroify 版本是多少

0.1.0-alpha.1

### 描述一下您遇到的问题以及重现步骤

build 编译报错
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/10382462/179394337-371c799b-b4c9-446a-b93d-30d4baa370c9.png">

### 如果可能的话，请包含一个代码框的链接与复制的问题

https://github.com/bingtsingw/taro-35-taroify

**Comment by ceu** [comment]
这个库是没人维护了吗？taro3.5 报错的 bug 一直没解决

**Comment by whevether** [comment]
> 这个库是没人维护了吗？taro3.5 报错的 bug 一直没解决

因为star太少了。作者没有动力了。  现在这个大环境肯定是先保证自己饭碗,开源首先要保证自己能吃放。
