### ISSUE TITLE
React 18依赖

### ISSUE THREAD

**Issue by liudichen** [mallfoundry/taroify#534]
### 问题出在哪个包

@taroify/core, @taroify/hooks

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

latest

### 描述一下您遇到的问题以及重现步骤

当前这2个包的
`"peerDependencies"："^17.0.2"`
可否修改为
`"peerDependencies"：">=17.0.0"`
之类的以兼容React18，
否则安装其他包时也老是报错。。。

### 你知道如何解决这个问题吗

Yes

### 修复这个问题的解决方案

`"peerDependencies"：">=17.0.0"`

**Comment by skyliwq** [comment]
同样问题希望尽快解决，要不没办法更新了！
