### ISSUE TITLE
[Bug Report] Navbar 会被 Image 给覆盖掉，请问这个咋解决额？

### ISSUE THREAD

**Issue by sunwenming** [mallfoundry/taroify#540]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5

### 平台/设备/浏览器

chrome

### 你正在使用的 Taroify 版本是多少

0.1.0-alpha.1

### 描述一下您遇到的问题以及重现步骤

您好，
    Navbar 会被 Image 给覆盖掉，请问这个咋解决额？
<img width="299" alt="截屏2022-09-30 22 43 01" src="https://user-images.githubusercontent.com/22268505/193295309-efc6ecbd-0bc3-430d-ac31-bef72189c32f.png">

```
<Navbar title='标题' fixed placeholder>
     <Navbar.NavRight>按钮</Navbar.NavRight>
</Navbar>
```

### 你知道如何解决这个问题吗

No

### 修复这个问题的解决方案

不知道咋修复了...

**Comment by Pilotager** [comment]
https://github.com/mallfoundry/taroify/pull/571
