### ISSUE TITLE
[Bug Report] Cascader Props 的参数defaultValue给了默认值后，tab和下边list不对应

### ISSUE THREAD

**Issue by stablehuang** [mallfoundry/taroify#544]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

android/ios都能复现

### 你正在使用的 Taroify 版本是多少

0.1.0-alpha.1

### 描述一下您遇到的问题以及重现步骤

“Cascader级联选择”组件问题：
1. Cascader Props 的参数defaultValue给了默认值后，上面tab选中了，但是下边没切换（目前tab选中最后一项，tab下面的list是第一个tab的）。
2. 给了默认值后，级联深度为2，点击第一级不会跳到第二级。如果级联深度为3，就不会有这个问题。

### 如果可能的话，请包含一个代码框的链接与复制的问题

https://codesandbox.io/s/interesting-mcnulty-byl4xk?file=/src/pages/index/index.tsx

### 修复这个问题的解决方案

defaultValue给了默认值后，将tab选中态和下面的list对应

**Comment by feidaZhang** [comment]
+1
