### ISSUE TITLE
[Bug Report] 评分组件Rate 在 支付宝小程序 点击时 报错 TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by chantAria** [mallfoundry/taroify#553]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

支付宝小程序

### 平台/设备/浏览器

Mac 支付宝小程序开发者工具3.3.3

### 你正在使用的 Taroify 版本是多少

0.0.29-alpha.9

### 描述一下您遇到的问题以及重现步骤

在 Taro 使用 Taroify 生成一个Rate组件，npm run dev:alipay 后在支付宝小程序开发者工具预览，点击评分时报错 TypeError: Cannot read properties of undefined (reading '0')
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/35865392/216903063-975b2391-9b23-45ab-b8a3-e50849aefa2e.png">

### 你知道如何解决这个问题吗

No

### 您是否愿意参与修复这个问题，并创建一个 PR

No

**Comment by ankouyang** [comment]
这个问题修复了吗？同问

**Comment by Pilotager** [comment]
0.1.0-alpha.2 版本修复了
