### ISSUE TITLE
这个库已经不再维护了吗？

### ISSUE THREAD

**Issue by TaroXin** [mallfoundry/taroify#556]
### 问题出在哪个包

@taroify/commerce

### 问题出在哪个平台/设备/浏览器

微信小程序, 支付宝小程序, 百度小程序

### 你正在使用的 Taroify 版本是多少

lastest

### 描述一下您遇到的问题以及重现步骤

看到最新的更新记录停在了去年的十月份

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by whevether** [comment]
> 好像是没人维护了。。

没有赞助。没有多少star.其实这个库要比京东那个好用。 但是开源不能靠爱发电

**Comment by ankouyang** [comment]
没有人维护了，里面好多坑啊
