### ISSUE TITLE
[Feature Request] 希望官方支持 @tarojs/components@"3.6.8"

### ISSUE THREAD

**Issue by Solyna** [mallfoundry/taroify#567]
### 使用示例，包括组件或 Hooks

希望官方支持 @tarojs/components@"3.6.8"

### 解决方案

希望官方支持 @tarojs/components@"3.6.8"

### 你想为这个功能创建一个 PR 吗

None

**Comment by Pilotager** [comment]
@Solyna 3.6.8版本Taro 配置项有错误，等待 3.6.9 版本发布再升级。

https://github.com/NervJS/taro/issues/14075

**Comment by Pilotager** [comment]
0.1.0-alpha.8 版本发布
