### ISSUE TITLE
[Bug Report] use-uncontrolled.ts的改动，导致Collapse折叠面板无法全部关闭

### ISSUE THREAD

**Issue by QingyunYang** [mallfoundry/taroify#575]
### 问题出在哪个包

@taroify/hooks

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.1.0-alpha.5

### 描述一下您遇到的问题以及重现步骤

if (Array.isArray(valueRef.current) && valueRef.current.length === 0) {}

加了上面的代码后，Collapse无法关闭最后一项

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
唔，这是个问题，我尽快发版修复

**Comment by Pilotager** [comment]
v0.1.0-alpha.6
