### ISSUE TITLE
[Bug Report] avatar group limit total 显示出错

### ISSUE THREAD

**Issue by ivantree** [mallfoundry/taroify#598]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.1.0-alpha.11

### 描述一下您遇到的问题以及重现步骤

avatar group
应该可以使用张统一大小的参数
```
<Avatar.Group spacing='mini' limit={3} total={24}>
                     <Avatar size='small' src='X' />
                     <Avatar size='small' src='X' />
                     <Avatar size='small' src='X' />
                     <Avatar size='small' src='X' />
`</Avatar.Group>`
```
显示有问题
![image](https://github.com/mallfoundry/taroify/assets/9014680/11c461f4-8c81-4522-adbc-f0fee1c650da)

### 你知道如何解决这个问题吗

No

### 您是否愿意参与修复这个问题，并创建一个 PR

None

### 修复这个问题的解决方案

应该可以使用张统一大小的参数

**Comment by Pilotager** [comment]
下一版本修复～

**Comment by Pilotager** [comment]
v0.1.0-alpha.12
