### ISSUE TITLE
[Bug Report] Picker 在连续多次滑动时滚动异常

### ISSUE THREAD

**Issue by zhangpeichao-cmd** [mallfoundry/taroify#599]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

"@taroify/core": "^0.1.0-alpha.11"

### 描述一下您遇到的问题以及重现步骤

Picker 组件在第一次拖动完成但滚动还未结束时 ，就进行第二次拖动，滚动行为异常

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by zhangpeichao-cmd** [comment]
https://github.com/mallfoundry/taroify/assets/81732513/821f29ca-f87d-46b0-99fc-99a6d25a5011

**Comment by Pilotager** [comment]
v0.1.0-alpha.12
