### ISSUE TITLE
[Bug Report] Swiper传入的items改变时，组件无法正常autoplay

### ISSUE THREAD

**Issue by CodeMak1r-zy** [mallfoundry/taroify#604]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

v0.1.0-alpha.12

### 描述一下您遇到的问题以及重现步骤

Swiper组件，初始传入一个Item，Swiper组件内计算count为1，
![image](https://github.com/mallfoundry/taroify/assets/90091332/5ab36b01-389c-4f36-bc77-754114dcc255)
这里的判断没有执行，但是当我新传入一个Item时，
![image](https://github.com/mallfoundry/taroify/assets/90091332/093ec785-6d14-4d90-9e9c-96bb528f154c)
![image](https://github.com/mallfoundry/taroify/assets/90091332/c6bba7cf-f1b1-475b-8e79-e8d2534d8f09)
这里的依赖项为空，没有重新根据count变化开始autoplay。

并且，当Item数量(count)不为1时，移除其中一项Item，页面的表现并没有如预期一般（比如，我初始传入3项Swiper.Item，后来去除一项，数据变化，但是Swiper还是轮播3项，只不过被移除的那一项的children为空）

正常的Swiper.Item
<img width="315" alt="image" src="https://github.com/mallfoundry/taroify/assets/90091332/e00b27d0-9246-4f64-af4b-655daad53fa9">

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by CodeMak1r-zy** [comment]
去除该项后的表现：
<img width="316" alt="image" src="https://github.com/mallfoundry/taroify/assets/90091332/ef066f08-35e1-4fce-8ec2-865af6e4d1d0">

**Comment by benjieming421** [comment]
遇到了一样的问题

**Comment by benjieming421** [comment]
workaround: 更新Swiper key值，让Swiper重新渲染
` <Swiper
        key={arr.join('_')}
        className='test-h'>
        {arr.map((item) => (
          <SwiperItem key={item}>
            <View className="item">swiper item{item}</View>
          </SwiperItem>
        ))}
 </Swiper>
`
作者有回答过 https://github.com/NervJS/taro/issues/6179

**Comment by CodeMak1r-zy** [comment]
> workaround: 更新Swiper key值，让Swiper重新渲染 `<Swiper key={arr.join('_')} className='test-h'> {arr.map((item) => ( <SwiperItem key={item}> <View className="item">swiper item{item}</View> </SwiperItem> ))} </Swiper>` 作者有回答过 [NervJS/taro#6179](https://github.com/NervJS/taro/issues/6179)

解决了
