### ISSUE TITLE
[Feature Request] Search组件可否加入debounce属性用于控制是否开启防抖

### ISSUE THREAD

**Issue by CodeMak1r-zy** [mallfoundry/taroify#605]
### 使用示例，包括组件或 Hooks

`<Search
      value={value}
      placeholder="请输入搜索关键词"
      onChange={(e) => setValue(e.detail.value)}
      debounce={true / false}
    />`

### 解决方案

加入debounce属性并且可在组件内部使用Toast展示loading效果
`<Toast open type="loading"/ >`

### 你想为这个功能创建一个 PR 吗

Yes

**Comment by Pilotager** [comment]
我觉得是不是在业务层面加防抖就好啊，比如在 onChange 上面，而不是在Search 组件内部加。

**Comment by CodeMak1r-zy** [comment]
> 我觉得是不是在业务层面加防抖就好啊，比如在 onChange 上面，而不是在Search 组件内部加。

也对
