### ISSUE TITLE
[Bug Report]  AreaPicker组件异常

### ISSUE THREAD

**Issue by AlanCoder** [mallfoundry/taroify#638]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5, 微信小程序

### 你正在使用的 Taroify 版本是多少

0.1.1-alpha.6

### 描述一下您遇到的问题以及重现步骤

AreaPicker创建了两个list，一个空的，现在的文档demo也呈现一样的问题

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
v0.1.1-alpha.7
