### ISSUE TITLE
[Bug Report] 微信小程序日历组件，日期最小值设置为当天前6个月，设置默认值，没有跳转到对应月份

### ISSUE THREAD

**Issue by saltovo** [mallfoundry/taroify#653]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.1.1-alpha.10

### 描述一下您遇到的问题以及重现步骤

日历组件设置 poppable，minDate设置为当天前6个月，maxDate设置为当天，defaultValue设置为当天，弹出的日历组件会定位在minDate所在月份，而不是在defaultValue所在月份
  const [minDate] = useState(new Date(2023, 0, 1))
  const [maxDate] = useState(new Date())
  const [open, setOpen] = useState(false)
  const [value, setValue] = useState<Date[]>(new Date())
  const [formatValue, setFormatValue] = useState<string>()

  return (
    <>
      <Cell
        title="自定义日期范围"
        isLink
        children={formatValue}
        onClick={() => setOpen(true)}
      />
      <Calendar
        type="range"
        min={minDate}
        max={maxDate}
        value={value}
        onChange={setValue}
        poppable
defaultValue={new Date()}
        showPopup={open}
        onClose={setOpen}
        onConfirm={(newValue) => {
          setFormatValue(formatRange(newValue))
          setOpen(false)
        }}
      >
      </Calendar>
    </>

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
您好，type="range"时，defaultValue和value为数组，传入 null 表示默认不选择
