### ISSUE TITLE
image启动懒加载属性时，当用户滚动加载过快的时候，会导致短暂的css样式错误[Bug Report] 

### ISSUE THREAD

**Issue by AlexL0ng** [mallfoundry/taroify#654]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

PC

### 你正在使用的 Taroify 版本是多少

^0.1.1-alpha.6

### 描述一下您遇到的问题以及重现步骤

一个新闻列表中的image启用lazyload,快速滚动这个列表渲染的时候，会出现短时间的样式错误

### 你知道如何解决这个问题吗

No

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
您好，短暂的样式错误指的是？方便提供下截图或者代码片段么，或者您指定给 `.taroify-image` 样式，或者通过 `View` 包裹一下 `Image` 组件呢。

**Comment by AlexL0ng** [comment]
https://github.com/mallfoundry/taroify/assets/53669064/32473153-64c9-4d77-aadb-9664c7710772

录屏在这
