### ISSUE TITLE
[Bug Report] 官网可复现 省市区选择组件切换时报错 无法正确触发事件 

### ISSUE THREAD

**Issue by xihuixiang** [mallfoundry/taroify#663]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5

### 你正在使用的 Taroify 版本是多少

0.1.1-alpha.9

### 描述一下您遇到的问题以及重现步骤

省市区组件 切换 控制台报错
Uncaught TypeError: Cannot read properties of undefined (reading 'slice')
    at genValOption (area-picker.tsx:107:45)
    at area-picker.tsx:123:29
    at o.current.o.current (use-memoized-fn.ts:18:28)
    at picker.tsx:171:5
    at R.animation.onClick (picker-button.tsx:39:11)
    at R.animation.handler (attachProps.js:48:29)
genValOption @ area-picker.tsx:107
(anonymous) @ area-picker.tsx:123
o.current.o.current @ use-memoized-fn.ts:18
(anonymous) @ picker.tsx:171
onClick @ picker-button.tsx:39
handler @ attachProps.js:48
Show 1 more frame
Show less

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
v0.1.2-alpha.0
