### ISSUE TITLE
小程序 popup 弹窗内的长列表无法滚动

### ISSUE THREAD

**Issue by Coffee-rabbit** [mallfoundry/taroify#678]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

v0.1.3-alpha.1

### 描述一下您遇到的问题以及重现步骤

 popup 弹窗内的内容无法滚动

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
您好，为了处理 `Popup` 滚动穿透问题，使用 `Taro` 本身提供的 `catchMove` 属性可以阻止，但是会导致 Popup 内部也无法滚动，我会在下个版本添加 `lock` 属性以便于控制是否阻止滚动穿透，`lock` 默认开启。

阻止滚动穿透后需要在 `Popup` 内手动添加 `ScrollView` 以支持滚动～

您现在可以：

```jsx
<Popup open placement="bottom" style={{ height: "30%" }} rounded>
  <ScrollView scrollY className="popup-demo-scroll">
    <View>我是内容</View>
    <View>我是内容</View>
    <View>我是内容</View>
    <View>我是内容</View>
    <View>我是内容</View>
    <View>我是内容</View>
    <View>我是内容</View>
    <View>我是内容</View>
    <View>我是内容</View>
  </ScrollView>
</Popup>
```

**Comment by Pilotager** [comment]
#679
