### ISSUE TITLE
期望（Notify / Dialog / Toast）支持函数式调用

### ISSUE THREAD

**Issue by waycowei** [mallfoundry/taroify#69]
如题，虽然现在也能用，但还是麻烦，特别是从 vant-weapp 迁过来，太麻烦了

**Comment by tgioer** [comment]
目前 taro 不支持 `selectComponent` 这样的 API，有什么好办法来解决将组件插入到节点上吗？

**Comment by waycowei** [comment]
不知道你想用的是哪个，我熟悉的差不多的有两个

- 直接操作 DOM：`createSelectorQuery` ，文档说它是支持微信和H5的（没说支持支付宝但好像也能用
- 获取实例：[ref](https://nervjs.github.io/taro/docs/ref#%E4%BD%BF%E7%94%A8%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%88%9B%E5%BB%BA-ref)

**Comment by waycowei** [comment]
不一定非要组件自己来插入节点，可以借鉴 Vant 官方的[小程序组件](https://vant-contrib.gitee.io/vant-weapp/#/dialog)，他们是需要自己手动写个节点，然后通过 selector 来操作

**Comment by tgioer** [comment]
```
  const context = options.context || getContext();
  const toast = context.selectComponent(options.selector as string);

  if (!toast) {
    console.warn('未找到 van-toast 节点，请确认 selector 及 context 是否正确');
    return;
  }

  delete options.context;
  delete options.selector;

  toast.clear = () => {
    toast.setData({ show: false });

    if (options.onClose) {
      options.onClose();
    }
  };
```
这个是 vant-weapp 中使用命令式调用的方法，目前 taro react 通过 selector 获得的是 dom，而不能获得组件实例。需要自定义 ref { open(), close() }，但是我感觉这样不优雅。

目前你可以先自己封装一下，或者提交一个PR。后续版本研究出来更优雅的方式时，会及时实现。

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/issues/71
