### ISSUE TITLE
[Bug Report] FloatingPanel组件无法向下滑动关闭

### ISSUE THREAD

**Issue by TingYan-Luo** [mallfoundry/taroify#707]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

微信开发者工具 1.06.2401020 Stable

### 你正在使用的 Taroify 版本是多少

0.1.5-alpha.0

### 描述一下您遇到的问题以及重现步骤

问题一：
浮动框向上打开后，向下滑动，无法关闭
<img width="334" alt="bug" src="https://github.com/mallfoundry/taroify/assets/66109363/ef7206ad-51a2-41f6-84c5-58a0ea88ebbe">

拷贝了源码后打印发现，scrollTop一直是undefined，无法获取到dom相关的信息。导致一直无法关闭
![image](https://github.com/mallfoundry/taroify/assets/66109363/b88af4f8-9200-4c34-bd64-f8443b759d36)

我尝试了使用scrollOffset方法获取scrollTop，但一直是0，还没有找到真是获取scrollTop的方法，但可以解决无法关闭问题。
<img width="509" alt="image" src="https://github.com/mallfoundry/taroify/assets/66109363/8b07cbd6-ee14-4d8f-8216-6163ea1366d1">

由于scrollTop一直等于0，会导致内容滚动和悬浮框滚动交互冲突，于是想通过关闭contentDraggable来解决。但触发了一个问题

问题二：
contentDraggable设置为false时，浮动框无法滑动

打印原因是：源码中的onTouchMove事件，event.target并不是元素dom，所以一直判错。
我尝试在content的view标签上增加onTouchMove的阻止冒泡方法，可以解决这个问题，但应该不规范

### 如果可能的话，请包含一个代码框的链接与复制的问题

https://codesandbox.io/p/devbox/kqcjk6?migrateFrom=lkwgmj&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltwcunxj00063b6h3ej46oel%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltwcunxi00023b6hhlupw0gv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltwcunxj00043b6hqzqzme2k%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltwcunxj00053b6h5qet9lo4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltwcunxi00023b6hhlupw0gv%2522%253A%257B%2522id%2522%253A%2522cltwcunxi00023b6hhlupw0gv%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltwcunxj00053b6h5qet9lo4%2522%253A%257B%2522id%2522%253A%2522cltwcunxj00053b6h5qet9lo4%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltwcunxj00043b6hqzqzme2k%2522%253A%257B%2522id%2522%253A%2522cltwcunxj00043b6hqzqzme2k%2522%252C%2522activeTabId%2522%253A%2522cltwcvztc00753b6hktxstih2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltwcunxi00033b6hsk0p6n30%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltwcutgf000tdif8gv4bh5id%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522cltwcvztc00753b6hktxstih2%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 你知道如何解决这个问题吗

No

### 您是否愿意参与修复这个问题，并创建一个 PR

Yes

**Comment by Pilotager** [comment]
Get，下一版本修复～

**Comment by Pilotager** [comment]
v0.1.6-alpha.0
