### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by xiaoli0705** [mallfoundry/taroify#713]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.1.6

### 描述一下您遇到的问题以及重现步骤

tabs组件配置animated后内容区域不会第一时间占满 会有闪烁 关闭动画后不会有这个问题
https://github.com/mallfoundry/taroify/assets/124589278/a82f1ea3-7ea2-4882-99dd-7a487b9d53e3

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
#717

**Comment by Pilotager** [comment]
0.1.7-alpha.0
