### ISSUE TITLE
Taro 引入 @taroify/icons 编译时报错

### ISSUE THREAD

**Issue by yudc13** [mallfoundry/taroify#715]
### 问题出在哪个包

@taroify/icons

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

"@taroify/icons": "0.1.6-alpha.0"    "@taroify/core": "0.1.6-alpha.0"

### 描述一下您遇到的问题以及重现步骤

<img width="1359" alt="image" src="https://github.com/mallfoundry/taroify/assets/76470486/d8ea19d9-a574-4307-9620-6265241da9a1">

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
下版本修复～

**Comment by hbztd** [comment]
测试发现： taro >= 3.6.26 且 不通过 babel-plugin-import 时会出现此问题，但通过 babel-plugin-import 能正常编译

**Comment by UyProject** [comment]
这个问题我这边也出现了

**Comment by Pilotager** [comment]
> 测试发现： taro >= 3.6.26 且 不通过 babel-plugin-import 时会出现此问题，但通过 babel-plugin-import 能正常编译

您方便看看如何修复这个问题么，我最近公司任务有点多，空闲时间有点不富裕。。。🌚

**Comment by hbztd** [comment]
> 这个问题我这边也出现了

先配下babel-plugin-import呗，，，绝大多数也是通过这个自动按需导入

**Comment by hbztd** [comment]
taro从3.16.19升级到3.6.20，更新了esbuild后prebundle的@taroify_core无法正常使用，
直接导入是引用的prebundle的@taroify_core
通过babel-plugin-import导入是直接引用@tarofiy/core包

暂时修复方法：配置babel-plugin-import或者关闭prebundle或者prebundle里exclude

**Comment by hbztd** [comment]
@Pilotager 关了
