### ISSUE TITLE
dropdown 的popup存在滚动穿透，需要也支持lock属性

### ISSUE THREAD

**Issue by woshiji1987** [mallfoundry/taroify#716]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5

### 你正在使用的 Taroify 版本是多少

0.1.6-alpha.0

### 描述一下您遇到的问题以及重现步骤

dropdown的popup存在滚动穿透，需要也支持lock属性

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

### 修复这个问题的解决方案

dropdown的popup存在滚动穿透，需要也支持lock属性

**Comment by Pilotager** [comment]
下版本修复～

**Comment by Pilotager** [comment]
#718

**Comment by Pilotager** [comment]
[0.1.7-alpha.0](https://github.com/mallfoundry/taroify/releases/tag/0.1.7-alpha.0)
