### ISSUE TITLE
[Bug Report]  Could not resolve dependency: npm ERR! peer @tarojs/components@"3.6.23" from @taroify/core@0.1.7-alpha.0

### ISSUE THREAD

**Issue by YEEY1010** [mallfoundry/taroify#720]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.1.7-alpha.0

### 描述一下您遇到的问题以及重现步骤

@tarojs/cli的版本是3.6.18，在安装@taroify/core最新版本时会报错，将tarojs/cli升级到3.6.28后也一样，是安装时必须是tarojs/cli为指定版本3.6.23吗？，报错信息如下：
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mini-taro-react@1.0.0
npm ERR! Found: @tarojs/components@3.6.28
npm ERR! node_modules/@tarojs/components
npm ERR!   @tarojs/components@"3.6.28" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @tarojs/components@"3.6.23" from @taroify/core@0.1.7-alpha.0
npm ERR! node_modules/@taroify/core
npm ERR!   @taroify/core@"0.1.7-alpha.0" from the root project

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
下版本修复～

**Comment by hbztd** [comment]
用npm --legacy-peer-deps，或者yarn,pnpm安装,
版本最好>=3.6.23

**Comment by Pilotager** [comment]
> 用npm --legacy-peer-deps，或者yarn,pnpm安装, 版本最好>=3.6.23

我在想我把 `@tarojs/components` 和 `@tarojs/taro` 的版本设置为 `>=3`

```
"peerDependencies": {
  "@tarojs/components": ">=3",
  "@tarojs/taro": ">=3",
  "react": "^18.2.0"
},
```

**Comment by YEEY1010** [comment]
> 下版本修复～

感谢~

**Comment by Pilotager** [comment]
v0.2.0-alpha.0
