### ISSUE TITLE
[Bug Report] popup在h5环境下由于内部默认状态是lock = true,所以h5popup相关交互都不可滚动，需要修复一下

### ISSUE THREAD

**Issue by woshiji1987** [mallfoundry/taroify#727]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5

### 你正在使用的 Taroify 版本是多少

0.2.0

### 描述一下您遇到的问题以及重现步骤

[Bug Report] popup在h5环境下由于内部默认状态是lock = true , popup被加上了class: 'taroify-popup-overflow-hidden', 所以h5环境下，popup相关交互默认都不可滚动，需要尽快修复一下

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
如果需要内容支持溢出滚动，则需要包裹一层 `ScrollView` 组件。

```
<Popup lock>
  <ScrollView>可以滑动</ScrollView>
</Popup>
```

**Comment by woshiji1987** [comment]
这种功能更新需要向前兼容，不然版本更新后，项目h5端，所有popup相关交互都变为不可滚动，需要配合代码改造，这太不友好了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月11日 18:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mallfoundry/taroify] [Bug Report] popup在h5环境下由于内部默认状态是lock = true,所以h5popup相关交互都不可滚动，需要修复一下 (Issue #727) |

如果需要内容支持溢出滚动，则需要包裹一层 ScrollView 组件。

<Popup lock>
  <ScrollView>可以滑动</ScrollView>
</Popup>

**Comment by Pilotager** [comment]
> 这种功能更新需要向前兼容，不然版本更新后，项目h5端，所有popup相关交互都变为不可滚动，需要配合代码改造，这太不友好了
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年05月11日 18:22 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [mallfoundry/taroify] [Bug Report] popup在h5环境下由于内部默认状态是lock = true,所以h5popup相关交互都不可滚动，需要修复一下 (Issue #727) | 如果需要内容支持溢出滚动，则需要包裹一层 ScrollView 组件。 <Popup lock> <ScrollView>可以滑动</ScrollView> </Popup> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

我的问题，当时应该升级次版本号而不是修订号。。。
