### ISSUE TITLE
[Bug Report] Input的readonly无效，仍然可以输入

### ISSUE THREAD

**Issue by qiaolin-pan** [mallfoundry/taroify#730]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.2.1-alpha.0

### 描述一下您遇到的问题以及重现步骤

```js
<Cell.Group inset>
    <Field label="文本">
        {/* readonly 属性无效 */}
        <Input placeholder="输入框只读" readonly />
    </Field>
</Cell.Group>
```

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
#731
