### ISSUE TITLE
[Bug Report] <Form.Label className="my-class">添加my-class后，原本的taroify-form-label的class样式没有了

### ISSUE THREAD

**Issue by qiaolin-pan** [mallfoundry/taroify#732]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

微信开发者工具查看

### 你正在使用的 Taroify 版本是多少

0.2.1-alpha.0

### 描述一下您遇到的问题以及重现步骤

```js
{/* 添加my-class后，看下图 */}
<Form.Label className="my-class">
```
<img width="483" alt="image" src="https://github.com/mallfoundry/taroify/assets/13342613/ecf0de0e-a3dd-41f5-a741-dd2fd2bf046d">

原本的taroify-form-label的class样式没有了，看下图
<img width="678" alt="image" src="https://github.com/mallfoundry/taroify/assets/13342613/e632354f-6f95-41bf-9b1e-70a1e616f941">

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
#733
