### ISSUE TITLE
[Bug Report] 使用 Signature 组件时报错

### ISSUE THREAD

**Issue by LiJiaYiTuanZi** [mallfoundry/taroify#737]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

Taro+React开发抖音小程序报错

### 你正在使用的 Taroify 版本是多少

0.2.2-alpha.0

### 描述一下您遇到的问题以及重现步骤

报错，页面无法显示
![error](https://github.com/mallfoundry/taroify/assets/134923654/9bcddd81-1774-4837-87dd-b1fc906a431c)

### 如果可能的话，请包含一个代码框的链接与复制的问题

https://developer.open-douyin.com/ide/minicode/i2v2Parx

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
抖音小程序？

**Comment by LiJiaYiTuanZi** [comment]
Watermark 组件也会报这个错误
![WX20240522-161741@2x](https://github.com/mallfoundry/taroify/assets/134923654/3ae5d190-ad98-45b0-9a9e-667260cc0a4f)
@Pilotager

**Comment by Pilotager** [comment]
> Watermark 组件也会报这个错误 ![WX20240522-161741@2x](https://private-user-images.githubusercontent.com/134923654/332717544-3ae5d190-ad98-45b0-9a9e-667260cc0a4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDE3NTcsIm5iZiI6MTcxNjcwMTQ1NywicGF0aCI6Ii8xMzQ5MjM2NTQvMzMyNzE3NTQ0LTNhZTVkMTkwLWFkOTgtNDViMC05YTllLTY2NzI2MGNjMGE0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNTMwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTJiMTgwYTU4M2Q4N2IwZjhiYmYzM2NjZWE5MGYzNGRlYmFmZTMzM2RiODUzOTIwYTQxODZhOTc4YjhhNTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AW0gfqtKJUV_Uyu-j7IqGLUlkFFT9kHLwUeHF0fWEZE) @Pilotager

都是 `getWindowInfo ` 的错误，一起修复了
