### ISSUE TITLE
[Bug Report] TextEllipsis 组件和 Timeline 组件失效

### ISSUE THREAD

**Issue by LiJiaYiTuanZi** [mallfoundry/taroify#740]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

Taro+React开发抖音小程序报错

### 你正在使用的 Taroify 版本是多少

0.2.2-alpha.0

### 描述一下您遇到的问题以及重现步骤

TextEllipsis 组件和 Timeline 组件所有功能都失效
![WX20240522-162249@2x](https://github.com/mallfoundry/taroify/assets/134923654/b9bf9047-461b-4c1a-a054-4042a84894e2)
![WX20240522-162302@2x](https://github.com/mallfoundry/taroify/assets/134923654/f63a7548-f1d3-4236-bbc4-caba6530d4cb)

### 如果可能的话，请包含一个代码框的链接与复制的问题

https://developer.open-douyin.com/ide/minicode/i2cg4DPM

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
<img width="321" alt="image" src="https://github.com/mallfoundry/taroify/assets/49061023/a36db8cf-5cd1-452a-90f4-f1424f1b0478">

时间轴应该没问题，`TextEllipsis ` 组件有些问题
