### ISSUE TITLE
[Bug Report] 官网提供的 IndexList 组件的“配合弹窗使用” demo 报错

### ISSUE THREAD

**Issue by LiJiaYiTuanZi** [mallfoundry/taroify#741]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

Taro+React开发抖音小程序报错

### 你正在使用的 Taroify 版本是多少

0.2.2-alpha.0

### 描述一下您遇到的问题以及重现步骤

官网提供的 IndexList 组件的“配合弹窗使用” demo 报错，当点击按钮弹起弹窗时就会报错
![WX20240522-162736@2x](https://github.com/mallfoundry/taroify/assets/134923654/7d465284-39c6-40bf-a79c-441c2538e4be)

### 如果可能的话，请包含一个代码框的链接与复制的问题

https://developer.open-douyin.com/ide/minicode/i2cpRrj2

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
这个能否贴一下 tsx 的代码，我更好复现一下。。

**Comment by LiJiaYiTuanZi** [comment]
import { View } from "@tarojs/components";
import { Button, Cell, IndexList, Popup } from "@taroify/core";
import _ from "lodash-es";
import { Fragment } from "react/jsx-runtime";
import { useState } from "react";

export default function Index() {
  const [open, setOpen] = useState(false);
  const indexList2: string[] = [];
  const charCodeOfA2 = "A".charCodeAt(0);
  for (let i = 0; i < 26; i++) {
    indexList2.push(String.fromCharCode(charCodeOfA2 + i));
  }

  return (
    <View>
      <View className="line"></View>
      <View>配合弹窗使用</View>
      <Button onClick={() => setOpen(true)}>打开弹窗</Button>
      <Popup
        open={open}
        style={{ height: "80%" }}
        placement="bottom"
        rounded
        onClose={() => setOpen(false)}
      >
        <Popup.Close />
        <View className="index-list-demo_wrap">
          <IndexList inner delay={300}>
            {_.map(indexList2, (index) => (
              <Fragment key={index}>
                <IndexList.Anchor index={index} />
                <Cell title="文本" />
                <Cell title="文本" />
                <Cell title="文本" />
              </Fragment>
            ))}
          </IndexList>
        </View>
      </Popup>
    </View>
  );
}
@Pilotager

**Comment by LiJiaYiTuanZi** [comment]
import { View } from "@tarojs/components";
import { Button, Cell, IndexList, Popup } from "@taroify/core";
import _ from "lodash-es";
import { Fragment } from "react/jsx-runtime";
import { useState } from "react";

export default function Index() {
  const [open, setOpen] = useState(false);
  const indexList2: string[] = [];
  const charCodeOfA2 = "A".charCodeAt(0);
  for (let i = 0; i < 26; i++) {
    indexList2.push(String.fromCharCode(charCodeOfA2 + i));
  }

  return (
    <View>
      <View className="line"></View>
      <View>配合弹窗使用</View>
      <Button onClick={() => setOpen(true)}>打开弹窗</Button>
      <Popup
        open={open}
        style={{ height: "80%" }}
        placement="bottom"
        rounded
        onClose={() => setOpen(false)}
      >
        <Popup.Close />
        <View className="index-list-demo_wrap">
          <IndexList inner delay={300}>
            {_.map(indexList2, (index) => (
              <Fragment key={index}>
                <IndexList.Anchor index={index} />
                <Cell title="文本" />
                <Cell title="文本" />
                <Cell title="文本" />
              </Fragment>
            ))}
          </IndexList>
        </View>
      </Popup>
    </View>
  );
}
@Pilotager

**Comment by LiJiaYiTuanZi** [comment]
`import { View } from "@tarojs/components";
import { Button, Cell, IndexList, Popup } from "@taroify/core";
import _ from "lodash-es";
import { Fragment } from "react/jsx-runtime";
import { useState } from "react";

export default function Index() {
  const [open, setOpen] = useState(false);
  const indexList2: string[] = [];
  const charCodeOfA2 = "A".charCodeAt(0);
  for (let i = 0; i < 26; i++) {
    indexList2.push(String.fromCharCode(charCodeOfA2 + i));
  }

  return (
    <View>
      <View className="line"></View>
      <View>配合弹窗使用</View>
      <Button onClick={() => setOpen(true)}>打开弹窗</Button>
      <Popup
        open={open}
        style={{ height: "80%" }}
        placement="bottom"
        rounded
        onClose={() => setOpen(false)}
      >
        <Popup.Close />
        <View className="index-list-demo_wrap">
          <IndexList inner delay={300}>
            {_.map(indexList2, (index) => (
              <Fragment key={index}>
                <IndexList.Anchor index={index} />
                <Cell title="文本" />
                <Cell title="文本" />
                <Cell title="文本" />
              </Fragment>
            ))}
          </IndexList>
        </View>
      </Popup>
    </View>
  );
}
`

**Comment by LiJiaYiTuanZi** [comment]
[Uploading index.txt…]()

**Comment by Pilotager** [comment]
```
function PopupIndexBar() {
  const [open, setOpen] = useState(false)

  const indexList: string[] = []
  const charCodeOfA = "A".charCodeAt(0)

  for (let i = 0; i < 26; i++) {
    indexList.push(String.fromCharCode(charCodeOfA + i))
  }

  return (
    <>
      <Button onClick={() => setOpen(true)}>打开弹窗</Button>
      <Popup
        open={open}
        style={{ height: "80%" }}
        placement="bottom"
        rounded
        onClose={() => setOpen(false)}
      >
        <Popup.Close />
        <View className="index-list-demo_wrap">
          <IndexList inner delay={300}>
            {_.map(indexList, (index) => {
              return (
                <Fragment key={index}>
                  <IndexList.Anchor index={index} />
                  <Cell title="文本" />
                  <Cell title="文本" />
                  <Cell title="文本" />
                </Fragment>
              )
            })}
          </IndexList>
        </View>
      </Popup>
    </>
  )
}
```
