### ISSUE TITLE
[Bug Report] 【Gird.Item】组件 icon 属性是 Image 节点时，会闪一下问题

### ISSUE THREAD

**Issue by wenqiyun** [mallfoundry/taroify#750]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.2.3-alpha.0

### 描述一下您遇到的问题以及重现步骤

问题：Gird.Item icon 使用 taroify Image 组件更新图片会闪 
1. 复现步骤：
```jsx
export function Text() {
  const [text, setText] = useState(0)

  return (
    <View>
      <View>
        当前值：
        {text}
      </View>
      <Button onClick={() => setText(v => v + 1)}>+1</Button>

      <Grid bordered={false} clickable>
        <Grid.Item icon={<Image className="h-96px w-96px" src="图片路径" />} text="XXXX" />
      </Grid>
    </View>
  )
}
```
2. 将 taroify Image 替换成 taro Image  只有首次点击时闪烁。
3. 通过插槽自定义格子的内容， 没有这个问题

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by hbztd** [comment]
@Pilotager 关了
