### ISSUE TITLE
[Bug Report] Form Field 多条校验规则错误显示问题

### ISSUE THREAD

**Issue by mzc9915** [mallfoundry/taroify#752]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.2.3-alpha.0

### 描述一下您遇到的问题以及重现步骤

当一个Field组件设置多条 valid rule 时，如果每一个 rule 都校验不通过，目前会将 所有需求信息都显示出来。想请问一下，能否支持 只显示第一条校验错误信息，以节省 ui 空间。 如果目前支持，能否告知一下，该如何实现？

我目前的代码如下：
```jsx
      <Form ref={formRef} className="login-info-form">
        <Field
          name="phoneNum"
          required
          icon={<Image src={phoneSvg} className="icon-img" />}
          rules={[
            { required: true, message: "请输入手机号"},
            { pattern: /^1[3-9]\d{9}$/, message: "手机号格式错误" },
          ]}
        >
          <Input
            value={phoneNum}
            clearable
            onChange={(e) => setPhoneNum(e.detail.value)}
            type="number"
            placeholder="请输入手机号"
          />
        </Field>
      </Form>

```

错误提示如下：
<img width="358" alt="image" src="https://github.com/mallfoundry/taroify/assets/50267789/2413bd39-caaa-45f6-9570-5e1f5caa781b">

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by hbztd** [comment]
只写一个rule
 
 rules={[{ validator: val => val ? /^1[3-9]\d{9}$/.test(val) ? true : "手机号格式错误" : "请输入手机号" }]}

**Comment by 1920h** [comment]
这个bug真解决了吗？我在Taro4使用了最新版的时候也出现了这个问题

**Comment by hbztd** [comment]
你rules怎么写的,写了几个就会显示。还是你加了validateFirst不好使，刚看那个文档写错了，要加在Form.Item(Field)上,不是rule里
