### ISSUE TITLE
[Bug Report] Countdown 组件在卸载时仍然继续执行倒计时并触发 onComplete

### ISSUE THREAD

**Issue by Shenyouxiangwai** [mallfoundry/taroify#756]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5, 微信小程序

### 你正在使用的 Taroify 版本是多少

0.2.13

### 描述一下您遇到的问题以及重现步骤

1、在页面中引入 Countdown 并开始倒计时
2、卸载页面中的 Countdown
3、在倒计时结束后仍然执行了 onComplete 回调

### 你知道如何解决这个问题吗

Yes

### 您是否愿意参与修复这个问题，并创建一个 PR

Yes

### 修复这个问题的解决方案

是否可以在 Countdown 组件被卸载时清除定时器？

**Comment by Pilotager** [comment]
[0.3.0-alpha.0](https://github.com/mallfoundry/taroify/releases/tag/0.3.0-alpha.0)
