### ISSUE TITLE
[Bug Report]ActionBar.IconButton 的样式似乎有问题

### ISSUE THREAD

**Issue by felix9ia** [mallfoundry/taroify#757]
### 问题出在哪个包

@taroify/commerce

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

^0.2.3-alpha.0

### 描述一下您遇到的问题以及重现步骤

样式在 app.js 引入`import "@taroify/commerce/action-bar/style"`

在page页面使用 ActionBar
```
  <ActionBar>
            <ActionBar.IconButton onClick={this.onPhoneClick}>
              <PhoneOutlined/>
              <Text>联系商家</Text>
            </ActionBar.IconButton>
            <ActionBar.IconButton onClick={this.redirectOrderList}>
              <OrdersOutlined/>
              <Text>我的订单</Text>
            </ActionBar.IconButton>
            <ActionBar.Button color="primary" onClick={this.redirectShop}>
              <Bag size="20px"/>
              继续下单
            </ActionBar.Button>
          </ActionBar>
```
最后就长这样
![image](https://github.com/mallfoundry/taroify/assets/23549191/53e1c2ff-9334-4239-9e5d-ecfa6b8be72b)

如果把 `import "@taroify/commerce/action-bar/style"` 放到页面里，就会报一堆 Conflicting order. Following module has been added: 警告
<details>
```

⚠️ Warnings: 

Error: chunk common [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[4]!./node_modules/@taroify/core/flex/index.scss
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[4]!./node_modules/@taroify/core/loading/index.scss
   - couldn't fulfill desired order of chunk group(s) app
   - while fulfilling desired order of chunk group(s) pages/orderDetail/index
    at Array.forEach (<anonymous>)

Error: chunk common [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[4]!./node_modules/@taroify/core/safe-area/index.scss
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[4]!./node_modules/@taroify/core/loading/index.scss
   - couldn't fulfill desired order of chunk group(s) app
   - while fulfilling desired order of chunk group(s) pages/orderDetail/index
    at Array.forEach (<anonymous>)

Error: chunk common [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[4]!./node_modules/@taroify/core/fixed-view/index.scss
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[4]!./node_modules/@taroify/core/loading/index.scss
   - couldn't fulfill desired order of chunk group(s) app
   - while fulfilling desired order of chunk group(s) pages/orderDetail/index
    at Array.forEach (<anonymous>)

Error: chunk common [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[4]!./node_modules/@taroify/core/loading/index.scss
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[4]!./node_modules/@taroify/core/badge/index.scss
   - couldn't fulfill desired order of chunk group(s) pages/orderDetail/index
   - while fulfilling desired order of chunk group(s) app
    at Array.forEach (<anonymous>)
```
</details>

是我的打开方式不对吗？

### 你知道如何解决这个问题吗

No

### 您是否愿意参与修复这个问题，并创建一个 PR

No

**Comment by WyntersN** [comment]
![image](https://github.com/mallfoundry/taroify/assets/27792650/9b964cdd-c1e2-42b9-93ee-b13c9b2f7215)


为什么我的是这样的

**Comment by felix9ia** [comment]
> ![image](https://private-user-images.githubusercontent.com/27792650/341390739-9b964cdd-c1e2-42b9-93ee-b13c9b2f7215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4OTMzMjksIm5iZiI6MTcxODg5MzAyOSwicGF0aCI6Ii8yNzc5MjY1MC8zNDEzOTA3MzktOWI5NjRjZGQtYzFlMi00MmI5LTkzZWUtYjEzYzliMmY3MjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE0MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNTI5ZWFmNGEwOWZjNGQzOWExZDJmZTFmNDg1ZWQ5MDM4YTZlODViNmQ4ZWZjMTRlNTllMmQzYmEwNzkyNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uEi-hyFQ3ew6y3RIhqsb9QeztxLeOckxIO8zQSWjDyQ)
> 
> 为什么我的是这样的

呃，各有各的诡异...

**Comment by WyntersN** [comment]
我的比你好一点 我的缩小就行了，你的样式都有问题

**Comment by WyntersN** [comment]
![image](https://github.com/mallfoundry/taroify/assets/27792650/3166e0c3-5950-4bf3-a054-75ecc925ac0b)

我的漂亮不？

**Comment by felix9ia** [comment]
> ![image](https://private-user-images.githubusercontent.com/27792650/341662676-3166e0c3-5950-4bf3-a054-75ecc925ac0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjYxMTksIm5iZiI6MTcxODk2NTgxOSwicGF0aCI6Ii8yNzc5MjY1MC8zNDE2NjI2NzYtMzE2NmUwYzMtNTk1MC00YmYzLWEwNTQtNzVlY2M5MjVhYzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEwMzAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MzM2YzI3MmNhYjQ5YjBkOTNhNjRiNzJiYzc1N2JlMWI5NGE2ZTU2YmI3ZjMxNzRiMmE0NjgxYzM2ZDNmMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U7Z3SVnCGZFZXsc6mObsgcdfQMA7Zzr045C2jTMcSgs)
> 
> 我的漂亮不？

为嘛我的不行，感觉是CSS冲突掉了。我在首页是这么引用的
```
import {useLaunch} from '@tarojs/taro'
import "@taroify/core/loading/style"
import "@taroify/commerce/action-bar/style"
import "@taroify/core/grid/style"
import "@taroify/core/flex/style"
import "@taroify/core/popup/style"
import "@taroify/core/index-list/style"
import "@taroify/core/sidebar/style"
import "@taroify/core/stepper/style"
import "@taroify/core/list/style"
import "@taroify/core/badge/style"
import "@taroify/core/cell/style"
import "@taroify/core/radio/style"
import "@taroify/core/dropdown-menu/style"
import "@taroify/core/password-input/style"
import "@taroify/core/number-keyboard/style"
import "@taroify/core/navbar/style"
import "@taroify/core/tag/style"
import "@taroify/core/input/style"
import "@taroify/core/field/style"
import "@taroify/core/tabbar/style"
import "@taroify/core/toast/style"
import "@taroify/core/button/style"
import "@taroify/core/image/style"
import "@taroify/core/space/style"
import "@taroify/core/skeleton/style"
import "@taroify/core/floating-panel/style"
import "@taroify/core/floating-bubble/style"
import "@taroify/core/fixed-view/style"
import './app.scss'
```

**Comment by WyntersN** [comment]
我没全部导入，我是按需引入的

**Comment by Pilotager** [comment]
按需导入

```
// babel.config.js
module.exports = {
  plugins: [
    [
      "import",
      {
        libraryName: "@taroify/core",
        libraryDirectory: "",
        style: true,
      },
      "@taroify/core",
    ],
    [
      "import",
      {
        libraryName: "@taroify/icons",
        libraryDirectory: "",
        camel2DashComponentName: false,
        style: () => "@taroify/icons/style",
      },
      "@taroify/icons",
    ],
  ],
};
```

**Comment by felix9ia** [comment]
> 按需导入
> 
> ```
> // babel.config.js
> module.exports = {
>   plugins: [
>     [
>       "import",
>       {
>         libraryName: "@taroify/core",
>         libraryDirectory: "",
>         style: true,
>       },
>       "@taroify/core",
>     ],
>     [
>       "import",
>       {
>         libraryName: "@taroify/icons",
>         libraryDirectory: "",
>         camel2DashComponentName: false,
>         style: () => "@taroify/icons/style",
>       },
>       "@taroify/icons",
>     ],
>   ],
> };
> ```

必须在页面里面按需引入吗？我觉得引入麻烦，就在app.js 直接全部引入了

**Comment by WyntersN** [comment]
是的按需后 全局挂载

**Comment by felix9ia** [comment]
> 是的按需，我sku选择都做好了，你还停留在这个问题
> 
> ![image](https://private-user-images.githubusercontent.com/27792650/341802871-5e459724-0eca-4032-b22e-3bf8ad899df1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODIzNDQsIm5iZiI6MTcxODk4MjA0NCwicGF0aCI6Ii8yNzc5MjY1MC8zNDE4MDI4NzEtNWU0NTk3MjQtMGVjYS00MDMyLWIyMmUtM2JmOGFkODk5ZGYxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxNTAwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTQzMWIzZWYxZWY4Y2JlMTEwZmFiN2ViOWU5MTlkZDAyYTRhMTFjMDA4OGJiMDZlZjY5YjViODJlNjZmZjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Uq79E2GULUw0TiLsKDoJXY1yU9zt1Uh82gSGriCOgiw)

看你的真不错，我自己写样式搞定了

**Comment by WyntersN** [comment]
写这个写了个把小时。

**Comment by Pilotager** [comment]
`@taroify/commerce`

```
[
  "import",
  {
    libraryName: "@taroify/commerce",
    libraryDirectory: "",
    style: true,
  },
  "@taroify/commerce",
],
```
