### ISSUE TITLE
[Bug Report] taro react weapp 字体好大

### ISSUE THREAD

**Issue by WyntersN** [mallfoundry/taroify#758]
### 问题出在哪个包

@taroify/core, @taroify/icons, @taroify/commerce

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

taro

### 你正在使用的 Taroify 版本是多少

0.2.3-alpha.0

### 描述一下您遇到的问题以及重现步骤

```js
//babel.config.js

module.exports = {
  presets: [
    [
      "taro",
      {
        framework: "react",
        ts: true,
      },
    ],
  ],
  plugins: [
    [
      "import",
      {
        libraryName: "@nutui/nutui-react-taro",
        libraryDirectory: "dist/esm",
        style: "css",
        camel2DashComponentName: false,
      },
      "nutui-react-taro",
    ],
    [
      "import",
      {
        libraryName: "@taroify/core",
        libraryDirectory: "",
        style: true,
      },
      "@taroify/core",
    ],
    [
      "import",
      {
        libraryName: "@taroify/commerce",
        libraryDirectory: "",
        style: true,
      },
      "@taroify/commerce",
    ],
    [
      "import",
      {
        libraryName: "@taroify/icons",
        libraryDirectory: "",
        camel2DashComponentName: false,
        style: () => "@taroify/icons/style",
      },
      "@taroify/icons",
    ],
  ],
};


```

```ts
//config/index.ts

 mini: {
    esnextModules: ["@taroify",'nutui-react']
}
```

```react
import { ActionBar } from "@taroify/commerce";
import { CartOutlined, ChatOutlined, ShopOutlined } from "@taroify/icons"


      <ActionBar>
        <ActionBar.IconButton>
          <ChatOutlined />
          <Text>客服</Text>
        </ActionBar.IconButton>
        <ActionBar.IconButton>
          <CartOutlined />
          <Text>购物车</Text>
        </ActionBar.IconButton>
        <ActionBar.IconButton>
          <ShopOutlined />
          <Text>店铺</Text>
        </ActionBar.IconButton>
        <ActionBar.Button>立即购买</ActionBar.Button>
      </ActionBar>

```

![image](https://github.com/mallfoundry/taroify/assets/27792650/dbc6e09f-28a0-4c64-86d0-a64ac3a35b5c)

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
你的设计稿尺寸是多少？

可以在 config 下的 index.ts 中增加如下配置：

```
deviceRatio: {
  640: 2.34 / 2,
  750: 1,
  375: 2,
  828: 1.81 / 2,
},
```

**Comment by WyntersN** [comment]
designWidth: 375

**Comment by WyntersN** [comment]
> 你的设计稿尺寸是多少？
> 
> 
> 
> 可以在 config 下的 index.ts 中增加如下配置：
> 
> 
> 
> ```
> 
> deviceRatio: {
> 
>   640: 2.34 / 2,
> 
>   750: 1,
> 
>   375: 2,
> 
>   828: 1.81 / 2,
> 
> },
> 
> ```

designWidth: 375

**Comment by Pilotager** [comment]
Taroify designWidth为750，如果你的designWidth为375，显示效果为两倍大，可以通过修改sass变量`$hd`适配（或者你想修改显示大小）

```tsx
// config/index.js
module.exports = {
  // ...
  sass: {
    data: "$hd: 1;"
  }
}
```

**Comment by Pilotager** [comment]
> > 你的设计稿尺寸是多少？
> > 可以在 config 下的 index.ts 中增加如下配置：
> > ```
> > 
> > deviceRatio: {
> > 
> >   640: 2.34 / 2,
> > 
> >   750: 1,
> > 
> >   375: 2,
> > 
> >   828: 1.81 / 2,
> > 
> > },
> > ```
> 
> 这是我现在的
> 
> ```js
> designWidth: 375,
> deviceRatio: {
>     640: 2.34 / 2,
>     750: 1,
>     828: 1.81 / 2,
>     375: 2 / 1
>   }
> ```

Taroify designWidth为750，如果你的designWidth为375，显示效果为两倍大，可以通过修改sass变量`$hd`适配（或者你想修改显示大小）
```tsx
// config/index.js
module.exports = {
  // ...
  sass: {
    data: "$hd: 1;"
  }
}
```

**Comment by WyntersN** [comment]
> > > 你的设计稿尺寸是多少？
> > > 可以在 config 下的 index.ts 中增加如下配置：
> > > ```
> > > 
> > > deviceRatio: {
> > > 
> > >   640: 2.34 / 2,
> > > 
> > >   750: 1,
> > > 
> > >   375: 2,
> > > 
> > >   828: 1.81 / 2,
> > > 
> > > },
> > > ```
> > 
> > 
> > 这是我现在的
> > ```js
> > designWidth: 375,
> > deviceRatio: {
> >     640: 2.34 / 2,
> >     750: 1,
> >     828: 1.81 / 2,
> >     375: 2 / 1
> >   }
> > ```
> 
> Taroify designWidth为750，如果你的designWidth为375，显示效果为两倍大，可以通过修改sass变量`$hd`适配（或者你想修改显示大小）
> 
> ```tsx
> // config/index.js
> module.exports = {
>   // ...
>   sass: {
>     data: "$hd: 1;"
>   }
> }
> ```

![image](https://github.com/mallfoundry/taroify/assets/27792650/0f09491f-acc3-464b-b827-9d8e8ad55cb0)

BackTop 似乎没有改变 
```tsx
import { BackTop } from "@taroify/core"
 <BackTop immediate  />
```

**Comment by Pilotager** [comment]
> ```tsx
> BackTop
> ```

`BackTop` 的 sass 变量有点问题，周末发布新版班，我会检查下其他组建的 sass 变量

**Comment by WyntersN** [comment]
好的谢谢！！！

**Comment by WyntersN** [comment]
还有一个疑问就是 BackTop 必须要Cell 才能回到顶部吗
