### ISSUE TITLE
[Bug Report] FixedNav 样式有问题

### ISSUE THREAD

**Issue by WyntersN** [mallfoundry/taroify#766]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

微信

### 你正在使用的 Taroify 版本是多少

0.3.0-alpha.0

### 描述一下您遇到的问题以及重现步骤
```ts
  designWidth: 375,
  deviceRatio: {
    640: 2.34 / 2,
    750: 1,
    828: 1.81 / 2,
    375: 2 / 1,
  },
  sass: {
    data: "$hd: 1;",
  },
```

![image](https://github.com/mallfoundry/taroify/assets/27792650/93f335cc-dffb-4b97-b00a-7cbe73136f7d)

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
这周发版解决相应的样式倍数问题
