### ISSUE TITLE
[Bug Report] IndexList 索引栏 右侧的索引都没有，完全和文档不一样啊

### ISSUE THREAD

**Issue by my3188** [mallfoundry/taroify#770]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.2.2-alpha.0

### 描述一下您遇到的问题以及重现步骤

按照官网文档引入组件，发现和文档里长的不一样啊。右侧fixed定位的索引根本就不存在。。。。

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
方便贴下代码片段么

**Comment by Pilotager** [comment]
是否使用了

```
<IndexList.Anchor index={index} />
```

**Comment by my3188** [comment]
import React, { useEffect, useMemo, useState } from "react";
import { Location } from "@taroify/icons";
import Taro from "@tarojs/taro";
import { Button, IndexList } from "@taroify/core";
import { View, Picker, Text } from "@tarojs/components";
import { useStore } from "@/store/index";
import Style from "./Search.module.scss";
import Layout from "@/components/Layout/index";

const indexList = [];
const charCodeOfA = "A".charCodeAt(0);

for (let i = 0; i < 26; i++) {
  indexList.push(String.fromCharCode(charCodeOfA + i));
}
const Search = () => {
  return (
   
    <IndexList>
      {indexList.map((index) => {
        return (
          <View key={index}>
            <IndexList.Anchor index={index} />
            <View title="文本">文本</View>
            <View title="文本">文本</View>
            <View title="文本">文本</View>
          </View>
        );
      })}
    </IndexList>
  );
};

export default Search;

**Comment by my3188** [comment]
> 是否使用了
> 
> ```
> <IndexList.Anchor index={index} />
> ```

import React, { useEffect, useMemo, useState } from "react";
import Taro from "@tarojs/taro";
import { Button, IndexList } from "@taroify/core";
import { View, Picker, Text } from "@tarojs/components";

const indexList = [];
const charCodeOfA = "A".charCodeAt(0);

for (let i = 0; i < 26; i++) {
  indexList.push(String.fromCharCode(charCodeOfA + i));
}
const Search = () => {
  return (
   
    <IndexList>
      {indexList.map((index) => {
        return (
          <View key={index}>
            <IndexList.Anchor index={index} />
            <View title="文本">文本</View>
            <View title="文本">文本</View>
            <View title="文本">文本</View>
          </View>
        );
      })}
    </IndexList>
  );
};

export default Search;

**Comment by my3188** [comment]
> 是否使用了
> 
> ```
> <IndexList.Anchor index={index} />
> ```

<IndexList>
  {indexList.map((index) => {
    return (
      <>
        <IndexList.Anchor index={index} />
        <View title="文本">文本</View>
        <View title="文本">文本</View>
        <View title="文本">文本</View>
      </>
    );
  })}
</IndexList>
换成这样可以了， 谢谢

**Comment by my3188** [comment]
> 是否使用了
> 
> ```
> <IndexList.Anchor index={index} />
> ```
换成下面这样可以了
` <IndexList>
      {indexList.map((index) => {
        return (
          <>
            <IndexList.Anchor index={index} />
            <View title="文本">文本</View>
            <View title="文本">文本</View>
            <View title="文本">文本</View>
          </>
        );
      })}
    </IndexList>`

**Comment by my3188** [comment]
> 是否使用了
> 
> ```
> <IndexList.Anchor index={index} />
> ```
换成下面这样可以了
<img width="436" alt="image" src="https://github.com/mallfoundry/taroify/assets/5450674/4b5ee011-5e2f-43e5-9b72-eb140a2bc183">

**Comment by my3188** [comment]
是我自己使用的问题
