### ISSUE TITLE
[Bug Report] IndexList 索引栏.如果页面顶部有fixed的元素，索引栏的定位会有问题，会被遮挡？这种情况下， 官方的建议使用方式是怎么样的？

### ISSUE THREAD

**Issue by my3188** [mallfoundry/taroify#773]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.2.2-alpha.0

### 描述一下您遇到的问题以及重现步骤

 索引栏.如果页面顶部有fixed的元素或者FixedView top的元素，索引栏的定位会有问题，会被遮挡？这种情况下， 官方的建议使用方式是怎么样的？

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by my3188** [comment]
补充示例代码
`
import React, { useEffect, useMemo, useState } from "react";
import { View, Text } from '@tarojs/components'
import { useLoad } from '@tarojs/taro'
import { Button,IndexList,Cell,Search, FixedView } from "@taroify/core"
import './index.scss'

const indexList = []
  const charCodeOfA = "A".charCodeAt(0)

  for (let i = 0; i < 26; i++) {
    indexList.push(String.fromCharCode(charCodeOfA + i))
  }

export default function Index() {
  const [value, setValue] = useState("");



  return (
    <View className='index'>
      <FixedView position="top">
        <Search
          shape="rounded"
          value={value}
          placeholder="请输入搜索关键词"
          onChange={(e) => setValue(e.detail.value)}
        />
      </FixedView>

      <IndexList>
      {indexList.map((index) => {
        return (
          < >
            <IndexList.Anchor index={index} />
            <Cell title="文本" />
            <Cell title="文本" />
            <Cell title="文本" />
          </>
        )
      })}
    </IndexList>
    </View>
  )
}
`

**Comment by my3188** [comment]
补充示例代码。搜索框会遮挡索引栏

import React, { useEffect, useMemo, useState } from "react";
import { View, Text } from '@tarojs/components'
import { useLoad } from '@tarojs/taro'
import { Button,IndexList,Cell,Search, FixedView } from "@taroify/core"
import './index.scss'

const indexList = []
  const charCodeOfA = "A".charCodeAt(0)

  for (let i = 0; i < 26; i++) {
    indexList.push(String.fromCharCode(charCodeOfA + i))
  }

export default function Index() {
  const [value, setValue] = useState("");



  return (
    <View className='index'>
      <FixedView position="top">
        <Search
          shape="rounded"
          value={value}
          placeholder="请输入搜索关键词"
          onChange={(e) => setValue(e.detail.value)}
        />
      </FixedView>

      <IndexList>
      {indexList.map((index) => {
        return (
          < >
            <IndexList.Anchor index={index} />
            <Cell title="文本" />
            <Cell title="文本" />
            <Cell title="文本" />
          </>
        )
      })}
    </IndexList>
    </View>
  )
}

**Comment by my3188** [comment]
IndexList 索引栏这个组件是要考虑他的父组件的，父组件在哪，滚动定位都和父组件相关的

**Comment by Pilotager** [comment]
> IndexList 索引栏这个组件是要考虑他的父组件的，父组件在哪，滚动定位都和父组件相关的

索引栏是基于 `fixed` 定位，如果想自定义，可以重写样式

页面级别的是基于 `usePageScroll` 滚动

容器内的话(弹窗)是基于 `ScrollView`

具体代码实现：

```
const TagElement = inner ? ScrollView : View
```

如果想在页面某个容器中，可以使用 `inner` 属性

**Comment by my3188** [comment]
> > IndexList 索引栏这个组件是要考虑他的父组件的，父组件在哪，滚动定位都和父组件相关的
> 
> 索引栏是基于 `fixed` 定位，如果想自定义，可以重写样式
> 
> 页面级别的是基于 `usePageScroll` 滚动
> 
> 容器内的话(弹窗)是基于 `ScrollView`
> 
> 具体代码实现：
> 
> ```
> const TagElement = inner ? ScrollView : View
> ```
> 
> 如果想在页面某个容器中，可以使用 `inner` 属性

感谢，有用，建议文档中写得再直白一点，用户可能会更好理解，例如切换到ScrollView模式，父类的高度一般是要固定，当然这个都是ScrollView的基本参数要求。但是对于菜鸟可能会比较友好。不过，还是谢谢你的及时回复。感激不尽👍

**Comment by Pilotager** [comment]
> > > IndexList 索引栏这个组件是要考虑他的父组件的，父组件在哪，滚动定位都和父组件相关的
> > 
> > 
> > 索引栏是基于 `fixed` 定位，如果想自定义，可以重写样式
> > 页面级别的是基于 `usePageScroll` 滚动
> > 容器内的话(弹窗)是基于 `ScrollView`
> > 具体代码实现：
> > ```
> > const TagElement = inner ? ScrollView : View
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果想在页面某个容器中，可以使用 `inner` 属性
> 
> 感谢，有用，建议文档中写得再直白一点，用户可能会更好理解，例如切换到ScrollView模式，父类的高度一般是要固定，当然这个都是ScrollView的基本参数要求。但是对于菜鸟可能会比较友好。不过，还是谢谢你的及时回复。感激不尽👍

我考虑下如何重新实现下 `IndexList`，让其变得更加灵活

**Comment by my3188** [comment]
> > > > IndexList 索引栏这个组件是要考虑他的父组件的，父组件在哪，滚动定位都和父组件相关的
> > > 
> > > 
> > > 索引栏是基于 `fixed` 定位，如果想自定义，可以重写样式
> > > 页面级别的是基于 `usePageScroll` 滚动
> > > 容器内的话(弹窗)是基于 `ScrollView`
> > > 具体代码实现：
> > > ```
> > > const TagElement = inner ? ScrollView : View
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 如果想在页面某个容器中，可以使用 `inner` 属性
> > 
> > 
> > 感谢，有用，建议文档中写得再直白一点，用户可能会更好理解，例如切换到ScrollView模式，父类的高度一般是要固定，当然这个都是ScrollView的基本参数要求。但是对于菜鸟可能会比较友好。不过，还是谢谢你的及时回复。感激不尽👍
> 
> 我考虑下如何重新实现下 `IndexList`，让其变得更加灵活

我遇到一个问题，就是在微信开发者工具里面是正常的，但是在真机下，索引sider和左侧的不一致的问题。
<img width="565" alt="image" src="https://github.com/mallfoundry/taroify/assets/5450674/fcf87778-474e-4033-aafc-7616b2096cf8">

**Comment by my3188** [comment]
真机下概率性出现下面错误
<img width="570" alt="image" src="https://github.com/mallfoundry/taroify/assets/5450674/53263239-68aa-44b2-b7cd-e13239396f6f">
MiniProgramError
Cannot read properties of undefined (reading 'top')
TypeError: Cannot read properties of undefined (reading 'top')
at top (pages/pages/CitySearch/index.js:2:5028)
at en (pages/pages/CitySearch/index.js:2:5333)
at jn (pages/pages/CitySearch/index.js:2:5504)
at t (appservice.app.js:5264:38148)
at t.value (appservice.app.js:5264:53041)
at (appservice.app.js:5264:27919)
at t.runWithPriority (appservice.app.js:5267:304707)
at t.<anonymous> (appservice.app.js:5264:27887)
at t.value (appservice.app.js:5264:107755)
at a (appservice.app.js:5264:66857)

**Comment by Pilotager** [comment]
> 真机下概率性出现下面错误 <img alt="image" width="570" src="https://private-user-images.githubusercontent.com/5450674/346309401-53263239-68aa-44b2-b7cd-e13239396f6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjMwMjIsIm5iZiI6MTcyMDMyMjcyMiwicGF0aCI6Ii81NDUwNjc0LzM0NjMwOTQwMS01MzI2MzIzOS02OGFhLTQ0YjItYjdjZC1lMTMyMzkzOTZmNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMDMyNTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZjNDRhM2E0OTAyN2FhNGU3OGM3OTdjNTc5ZWE0NjZlZWU2ZWQzMjIxM2I3ZGNkMTQ3NmQ5NjZmZmMxMWNlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EQ64epnSaHB-LmFuf-OpzD2YBenW48Kpfkmx65W0Mzk"> MiniProgramError Cannot read properties of undefined (reading 'top') TypeError: Cannot read properties of undefined (reading 'top') at top (pages/pages/CitySearch/index.js:2:5028) at en (pages/pages/CitySearch/index.js:2:5333) at jn (pages/pages/CitySearch/index.js:2:5504) at t (appservice.app.js:5264:38148) at t.value (appservice.app.js:5264:53041) at (appservice.app.js:5264:27919) at t.runWithPriority (appservice.app.js:5267:304707) at t. (appservice.app.js:5264:27887) at t.value (appservice.app.js:5264:107755) at a (appservice.app.js:5264:66857)

我貌似知道问题了，初始化时候数据没拿到，貌似是异步问题，你可以先做个回调兼容，我看看怎么在组件中处理

**Comment by my3188** [comment]
> > 真机下概率性出现下面错误 <img alt="image" width="570" src="https://private-user-images.githubusercontent.com/5450674/346309401-53263239-68aa-44b2-b7cd-e13239396f6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjMwMjIsIm5iZiI6MTcyMDMyMjcyMiwicGF0aCI6Ii81NDUwNjc0LzM0NjMwOTQwMS01MzI2MzIzOS02OGFhLTQ0YjItYjdjZC1lMTMyMzkzOTZmNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMDMyNTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZjNDRhM2E0OTAyN2FhNGU3OGM3OTdjNTc5ZWE0NjZlZWU2ZWQzMjIxM2I3ZGNkMTQ3NmQ5NjZmZmMxMWNlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EQ64epnSaHB-LmFuf-OpzD2YBenW48Kpfkmx65W0Mzk"> MiniProgramError Cannot read properties of undefined (reading 'top') TypeError: Cannot read properties of undefined (reading 'top') at top (pages/pages/CitySearch/index.js:2:5028) at en (pages/pages/CitySearch/index.js:2:5333) at jn (pages/pages/CitySearch/index.js:2:5504) at t (appservice.app.js:5264:38148) at t.value (appservice.app.js:5264:53041) at (appservice.app.js:5264:27919) at t.runWithPriority (appservice.app.js:5267:304707) at t. (appservice.app.js:5264:27887) at t.value (appservice.app.js:5264:107755) at a (appservice.app.js:5264:66857)
> 
> 我貌似知道问题了，初始化时候数据没拿到，貌似是异步问题，你可以先做个回调兼容，我看看怎么在组件中处理

大佬，具体是在哪里做个回调？

**Comment by Pilotager** [comment]
> > > 真机下概率性出现下面错误 <img alt="image" width="570" src="https://private-user-images.githubusercontent.com/5450674/346309401-53263239-68aa-44b2-b7cd-e13239396f6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjMwMjIsIm5iZiI6MTcyMDMyMjcyMiwicGF0aCI6Ii81NDUwNjc0LzM0NjMwOTQwMS01MzI2MzIzOS02OGFhLTQ0YjItYjdjZC1lMTMyMzkzOTZmNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMDMyNTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZjNDRhM2E0OTAyN2FhNGU3OGM3OTdjNTc5ZWE0NjZlZWU2ZWQzMjIxM2I3ZGNkMTQ3NmQ5NjZmZmMxMWNlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EQ64epnSaHB-LmFuf-OpzD2YBenW48Kpfkmx65W0Mzk"> MiniProgramError Cannot read properties of undefined (reading 'top') TypeError: Cannot read properties of undefined (reading 'top') at top (pages/pages/CitySearch/index.js:2:5028) at en (pages/pages/CitySearch/index.js:2:5333) at jn (pages/pages/CitySearch/index.js:2:5504) at t (appservice.app.js:5264:38148) at t.value (appservice.app.js:5264:53041) at (appservice.app.js:5264:27919) at t.runWithPriority (appservice.app.js:5267:304707) at t. (appservice.app.js:5264:27887) at t.value (appservice.app.js:5264:107755) at a (appservice.app.js:5264:66857)
> > 
> > 
> > 我貌似知道问题了，初始化时候数据没拿到，貌似是异步问题，你可以先做个回调兼容，我看看怎么在组件中处理
> 
> 大佬，具体是在哪里做个回调？

可以加个 `loading`，在数据回来之后显示 `IndexList`，很蠢的方式，我尽量尽快修复这个问题

**Comment by my3188** [comment]
> > > > 真机下概率性出现下面错误 <img alt="image" width="570" src="https://private-user-images.githubusercontent.com/5450674/346309401-53263239-68aa-44b2-b7cd-e13239396f6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjMwMjIsIm5iZiI6MTcyMDMyMjcyMiwicGF0aCI6Ii81NDUwNjc0LzM0NjMwOTQwMS01MzI2MzIzOS02OGFhLTQ0YjItYjdjZC1lMTMyMzkzOTZmNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMDMyNTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZjNDRhM2E0OTAyN2FhNGU3OGM3OTdjNTc5ZWE0NjZlZWU2ZWQzMjIxM2I3ZGNkMTQ3NmQ5NjZmZmMxMWNlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EQ64epnSaHB-LmFuf-OpzD2YBenW48Kpfkmx65W0Mzk"> MiniProgramError Cannot read properties of undefined (reading 'top') TypeError: Cannot read properties of undefined (reading 'top') at top (pages/pages/CitySearch/index.js:2:5028) at en (pages/pages/CitySearch/index.js:2:5333) at jn (pages/pages/CitySearch/index.js:2:5504) at t (appservice.app.js:5264:38148) at t.value (appservice.app.js:5264:53041) at (appservice.app.js:5264:27919) at t.runWithPriority (appservice.app.js:5267:304707) at t. (appservice.app.js:5264:27887) at t.value (appservice.app.js:5264:107755) at a (appservice.app.js:5264:66857)
> > > 
> > > 
> > > 我貌似知道问题了，初始化时候数据没拿到，貌似是异步问题，你可以先做个回调兼容，我看看怎么在组件中处理
> > 
> > 
> > 大佬，具体是在哪里做个回调？
> 
> 可以加个 `loading`，在数据回来之后显示 `IndexList`，很蠢的方式，我尽量尽快修复这个问题

感谢！

**Comment by my3188** [comment]
> > > > 真机下概率性出现下面错误 <img alt="image" width="570" src="https://private-user-images.githubusercontent.com/5450674/346309401-53263239-68aa-44b2-b7cd-e13239396f6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjMwMjIsIm5iZiI6MTcyMDMyMjcyMiwicGF0aCI6Ii81NDUwNjc0LzM0NjMwOTQwMS01MzI2MzIzOS02OGFhLTQ0YjItYjdjZC1lMTMyMzkzOTZmNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMDMyNTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZjNDRhM2E0OTAyN2FhNGU3OGM3OTdjNTc5ZWE0NjZlZWU2ZWQzMjIxM2I3ZGNkMTQ3NmQ5NjZmZmMxMWNlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EQ64epnSaHB-LmFuf-OpzD2YBenW48Kpfkmx65W0Mzk"> MiniProgramError Cannot read properties of undefined (reading 'top') TypeError: Cannot read properties of undefined (reading 'top') at top (pages/pages/CitySearch/index.js:2:5028) at en (pages/pages/CitySearch/index.js:2:5333) at jn (pages/pages/CitySearch/index.js:2:5504) at t (appservice.app.js:5264:38148) at t.value (appservice.app.js:5264:53041) at (appservice.app.js:5264:27919) at t.runWithPriority (appservice.app.js:5267:304707) at t. (appservice.app.js:5264:27887) at t.value (appservice.app.js:5264:107755) at a (appservice.app.js:5264:66857)
> > > 
> > > 
> > > 我貌似知道问题了，初始化时候数据没拿到，貌似是异步问题，你可以先做个回调兼容，我看看怎么在组件中处理
> > 
> > 
> > 大佬，具体是在哪里做个回调？
> 
> 可以加个 `loading`，在数据回来之后显示 `IndexList`，很蠢的方式，我尽量尽快修复这个问题

我加loading了，是不报错了，但是sider的高亮和左侧的index对不上，有时候会差一个

**Comment by my3188** [comment]
> > > > 真机下概率性出现下面错误 <img alt="image" width="570" src="https://private-user-images.githubusercontent.com/5450674/346309401-53263239-68aa-44b2-b7cd-e13239396f6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjMwMjIsIm5iZiI6MTcyMDMyMjcyMiwicGF0aCI6Ii81NDUwNjc0LzM0NjMwOTQwMS01MzI2MzIzOS02OGFhLTQ0YjItYjdjZC1lMTMyMzkzOTZmNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMDMyNTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZjNDRhM2E0OTAyN2FhNGU3OGM3OTdjNTc5ZWE0NjZlZWU2ZWQzMjIxM2I3ZGNkMTQ3NmQ5NjZmZmMxMWNlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EQ64epnSaHB-LmFuf-OpzD2YBenW48Kpfkmx65W0Mzk"> MiniProgramError Cannot read properties of undefined (reading 'top') TypeError: Cannot read properties of undefined (reading 'top') at top (pages/pages/CitySearch/index.js:2:5028) at en (pages/pages/CitySearch/index.js:2:5333) at jn (pages/pages/CitySearch/index.js:2:5504) at t (appservice.app.js:5264:38148) at t.value (appservice.app.js:5264:53041) at (appservice.app.js:5264:27919) at t.runWithPriority (appservice.app.js:5267:304707) at t. (appservice.app.js:5264:27887) at t.value (appservice.app.js:5264:107755) at a (appservice.app.js:5264:66857)
> > > 
> > > 
> > > 我貌似知道问题了，初始化时候数据没拿到，貌似是异步问题，你可以先做个回调兼容，我看看怎么在组件中处理
> > 
> > 
> > 大佬，具体是在哪里做个回调？
> 
> 可以加个 `loading`，在数据回来之后显示 `IndexList`，很蠢的方式，我尽量尽快修复这个问题

其实我有个建议，改下交互，可能实现起来更简单一点。右侧sider上不用高亮当前的索引，只需要点击右侧sider或者滑动的时候tip提示一下就好，我觉得你现在索引和sider的对应，计算起来还麻烦，直接用ScrollView 的scrollIntoView，这样跳转就简单很多。你现在的交互会有个问题，就是如果按a-z的索引，假设 xyz下的数据都只有一条，那么xyz可能永远都无法高亮，因为高度太低，就没有机会滚动到他们的位置，可能xyz之前的某一个字母已经是最低了
