### ISSUE TITLE
[Bug Report] toast怎么设置不自动关闭

### ISSUE THREAD

**Issue by luoqiang-wm** [mallfoundry/taroify#791]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

无

### 你正在使用的 Taroify 版本是多少

0.3.2

### 描述一下您遇到的问题以及重现步骤

无

### 你知道如何解决这个问题吗

No

### 您是否愿意参与修复这个问题，并创建一个 PR

No

### 修复这个问题的解决方案

无

**Comment by Pilotager** [comment]
这个需要处理下，我加个 `duration` 为 `0` 的时候不自动关闭

**Comment by luoqiang-wm** [comment]
> 这个需要处理下，我加个 `duration` 为 `0` 的时候不自动关闭

👍🏻
