### ISSUE TITLE
`Dialog.Content`内容过多时无法滚动展示

### ISSUE THREAD

**Issue by sayll** [mallfoundry/taroify#792]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

IOS真机出现，模拟器开发正常

### 你正在使用的 Taroify 版本是多少

0.3.2-alpha.0

### 描述一下您遇到的问题以及重现步骤

`Dialog.Content`内容过多，无法正常显示完且无法滚动，期望可以滚动展示

### 你知道如何解决这个问题吗

No

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
可以给 `content` 里面添加 `ScrollView`

eg:

```
<Dialog.Content>
  <ScrollView scrollY className="dialog-demo-scroll">
    代码是写出来给人看的，附带能在机器上运行代码是写出来给人看的，附带能在机器上运行代码是写出来给人看的，附带能在机器上运行代码是写出来给人看的，附带能在机器上运行
  </ScrollView>
</Dialog.Content>
```
