### ISSUE TITLE
[Bug Report] process组件文档有错误

### ISSUE THREAD

**Issue by gaogaomie** [mallfoundry/taroify#798]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

3.6.32

### 描述一下您遇到的问题以及重现步骤

![image](https://github.com/user-attachments/assets/d6fe3e25-9a52-487c-82d0-39c4beedc309)
process组件，线条粗细属性给出的文档不对，其次没有动画条纹组件

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
哈哈。。。   好尴尬啊
