### ISSUE TITLE
[Bug Report] couldn't fulfill desired order of chunk group(s) pages/category/index    - while fulfilling desired order of chunk group(s) pages/order-list/index

### ISSUE THREAD

**Issue by lvxiaoqian-git** [mallfoundry/taroify#808]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

^0.4.0-alpha.0

### 描述一下您遇到的问题以及重现步骤

同时使用Sticky 和Sidebar，并且Sticky 在 Sidebar之前。 就会报错～

Error: chunk common [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[4]!./node_modules/@taroify/core/sticky/index.scss
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[0].use[4]!./node_modules/@taroify/core/badge/index.scss
   - couldn't fulfill desired order of chunk group(s) pages/category/index
   - while fulfilling desired order of chunk group(s) pages/order-list/index
    at Array.forEach (<anonymous>)

### 你知道如何解决这个问题吗

No

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
`config/index.ts` 里面：

```
miniCssExtractPluginOption: {
  ignoreOrder: true,
},
```

试试

**Comment by Pilotager** [comment]
> `config/index.ts` 里面：
> 
> ```
> miniCssExtractPluginOption: {
>   ignoreOrder: true,
> },
> ```
> 
> 试试

https://docs.taro.zone/docs/config-detail#ministylusloaderoption

**Comment by lvxiaoqian-git** [comment]
谢谢

> > `config/index.ts`里面：
> > ```
> > miniCssExtractPluginOption: {
> >   ignoreOrder: true,
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 参观
> 
> https://docs.taro.zone/docs/config-detail#ministylusloaderoption

谢谢
