### ISSUE TITLE
Cascader 级联选择

### ISSUE THREAD

**Issue by William-walk** [mallfoundry/taroify#811]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.4.0-alpha.0

### 描述一下您遇到的问题以及重现步骤

Cascader 级联选择组件不能上下滑动，开启swipeable可左右滑动

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by William-walk** [comment]
![test](https://github.com/user-attachments/assets/80b09c57-57a2-4bec-8a42-ee9cf878eef2)

**Comment by William-walk** [comment]
当数据超出弹出层高度时touch 上下滑动不生效

**Comment by William-walk** [comment]
是版本的问题吗？

**Comment by Pilotager** [comment]
https://github.com/mallfoundry/taroify/pull/813
