### ISSUE TITLE
[Bug Report] Cascader 级联选择的 taroify-tabs__nav 无法完整显示选中的内容，即使只有一级

### ISSUE THREAD

**Issue by felix9ia** [mallfoundry/taroify#816]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

小程序

### 你正在使用的 Taroify 版本是多少

0.4.2-alpha.0

### 描述一下您遇到的问题以及重现步骤

![image](https://github.com/user-attachments/assets/9a43fbe1-adbd-4678-8a50-c0a65f6623a7)
选中后的文字，不能够完整的显示，即使只有一级的选中项。

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

### 修复这个问题的解决方案

希望可以和[ vant-ui ](https://vant-ui.github.io/vant/#/zh-CN/cascader)一样,完整的展示选中内容
![image](https://github.com/user-attachments/assets/5fd325f7-ea12-4e47-9381-23f51e018ec8)

**Comment by Pilotager** [comment]
https://github.com/mallfoundry/taroify/pull/817
