### ISSUE TITLE
[Bug Report] Navbar 微信小程序没有自适应

### ISSUE THREAD

**Issue by Niubility-SunLight** [mallfoundry/taroify#819]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

0.4.2-alpha.0

### 描述一下您遇到的问题以及重现步骤

Navbar 微信小程序中会被胶囊这档。navbar好想没有适配微信环境

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
<img width="1030" alt="image" src="https://github.com/user-attachments/assets/1b32a6fa-2292-4431-98dc-1ecaf26988e9">

有个安全区域

**Comment by Niubility-SunLight** [comment]
![Snipaste_2024-10-17_10-57-32](https://github.com/user-attachments/assets/26cd6523-4fcd-4a2b-9f0c-063373704429)
并没有用

**Comment by Pilotager** [comment]
> ![Snipaste_2024-10-17_10-57-32](https://private-user-images.githubusercontent.com/38355384/377294326-26cd6523-4fcd-4a2b-9f0c-063373704429.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDQ3NzEsIm5iZiI6MTcyOTE0NDQ3MSwicGF0aCI6Ii8zODM1NTM4NC8zNzcyOTQzMjYtMjZjZDY1MjMtNGZjZC00YTJiLTlmMGMtMDYzMzczNzA0NDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA1NTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZWQzYjAwMmRkMThhNmQwN2JmMGNkYjdmY2IxNWYwMDI5Nzc4OGY5MWU5MGMzNzNjZGU4MmM1ZDIwYTMxMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WDHxaYx-mFI6OUIKnSd0vA4fgIwVeOo96b5DZKLNosM) 并没有用

您先自己填充下，我重新看下实现

**Comment by CodeMak1r-zy** [comment]
@Niubility-SunLight 没有复现
<img width="394" alt="image" src="https://github.com/user-attachments/assets/9f2f735e-75dd-43f0-b116-0f96c1fcf51d">

**Comment by Niubility-SunLight** [comment]
> @Niubility-SunLight 没有复现 <img alt="image" width="394" src="https://private-user-images.githubusercontent.com/90091332/377398748-9f2f735e-75dd-43f0-b116-0f96c1fcf51d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzE1NDksIm5iZiI6MTcyOTE3MTI0OSwicGF0aCI6Ii85MDA5MTMzMi8zNzczOTg3NDgtOWYyZjczNWUtNzVkZC00M2YwLWIxMTYtMGY5NmMxZmNmNTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEzMjA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NTY5ODJiYzE1NjZiYzhlMjgyODljOGU1OGE2NTA1Y2U4ZDFlNjYxZjdlYzBmMGMwOTRhN2U4MmNjMjNkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UXf3UlRmki4ytL-2OTnagJKer6IBinbhASms4RxpLRI">

设置export default definePageConfig({
  // navigationBarTitleText: '首页',
  navigationStyle: 'custom',
})
自定义导航栏的时候就有这个问题、应该是navbar没有针对自定义导航栏适配

**Comment by Pilotager** [comment]
新增了 `nativeSafeTop` 属性，判断了状态栏高度
