### ISSUE TITLE
[Bug Report] 并未兼容到 Chrome 51

### ISSUE THREAD

**Issue by bigbigDreamer** [mallfoundry/taroify#825]
### 问题出在哪个包

@taroify/core, @taroify/hooks

### 问题出在哪个平台/设备/浏览器

H5

### 平台/设备/浏览器

Android 8

### 你正在使用的 Taroify 版本是多少

0.3.2-alpha.0

### 描述一下您遇到的问题以及重现步骤

<img width="1330" alt="image" src="https://github.com/user-attachments/assets/c4ef3f85-7d7a-49de-a699-690dc2ff2ec6">

下载的 npm 源码里甚至都还有 `??` 和 `?.` 的操作符号

### 你知道如何解决这个问题吗

Yes

### 您是否愿意参与修复这个问题，并创建一个 PR

None

### 修复这个问题的解决方案

更改 `babel` 的编译配置

**Comment by Pilotager** [comment]
依赖于 `Taro` 的编译：

`config/index` 下面

```
h5: {
  compile: {
    include: [
      (filename) => {
        return ()
      }
    ]   
  }
}
```

这里加上需要处理的包

**Comment by bigbigDreamer** [comment]
@Pilotager 如果我要用 webpack 编译，有推荐的方案或者配置吗
