### ISSUE TITLE
[Bug Report] IndexList 组件异步使用报错

### ISSUE THREAD

**Issue by Niubility-SunLight** [mallfoundry/taroify#827]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5

### 你正在使用的 Taroify 版本是多少

0.4.2-alpha.0

### 描述一下您遇到的问题以及重现步骤

后台请求数据，在初始数据为空数组时  使用IndexList 报错
![image](https://github.com/user-attachments/assets/431738f3-5394-4dfd-a45b-d6c80f7f67fd)
![image](https://github.com/user-attachments/assets/c905dde9-35db-4ac8-a0e8-af76a593d2cb)
初步怀疑是获取IndexList 子节点位置状态时，因为数据在加载不存在子节点所以获取报错

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by Pilotager** [comment]
周末版本修复

**Comment by Pilotager** [comment]
https://github.com/mallfoundry/taroify/pull/828
