### ISSUE TITLE
[Bug Report] 微信小程序环境，List组件Placeholder会出现在最上面

### ISSUE THREAD

**Issue by zc2638** [mallfoundry/taroify#856]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 平台/设备/浏览器

微信开发者工具，真机

### 你正在使用的 Taroify 版本是多少

4.0.7

### 描述一下您遇到的问题以及重现步骤

List组件Placeholder会出现在最上面。

直接拷贝List的网站示例，即可重现。

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by CodeMak1r-zy** [comment]
<img width="342" alt="image" src="https://github.com/user-attachments/assets/aa838f81-45b6-4c00-b185-d8401566dbcc" />
未复现

**Comment by zc2638** [comment]
@Pilotager 
我测试过，`preact` 需要多套一层 View 标签固定变量位置。
作者不想因为`preact`这个问题去多套一层标签，怕影响样式。

我还反应了好几个问题，但是一直都没有解决，最佳方法就是自己把组件拷出来改。
下一阶段我的项目要移除这个UI库了
