### ISSUE TITLE
[Feature Request] 各组件文档中新增feature特性、破坏性更新的版本号说明

### ISSUE THREAD

**Issue by CodeMak1r-zy** [mallfoundry/taroify#859]
### 使用示例，包括组件或 Hooks

参照Vant文档：https://vant-ui.github.io/vant/#/zh-CN/radio

<img width="153" alt="image" src="https://github.com/user-attachments/assets/e3ea4635-9c7c-4f1a-9f6d-2fd5b5838eff">

### 你想为这个功能创建一个 PR 吗

None

**Comment by Pilotager** [comment]
这个好，我咋就没想到呢

**Comment by ianzone** [comment]
话说版本号怎么都是alpha的
<img width="109" alt="image" src="https://github.com/user-attachments/assets/ed7d8035-7fed-4ff6-9ef7-e88601b0fd66" />

**Comment by ianzone** [comment]
推荐使用 [git-cz](https://github.com/streamich/git-cz) 和 [semantic-release](https://github.com/semantic-release/semantic-release) 进行版本管理

**Comment by Pilotager** [comment]
> 推荐使用 [git-cz](https://github.com/streamich/git-cz) 和 [semantic-release](https://github.com/semantic-release/semantic-release) 进行版本管理

我看下
