### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by eleliauk** [mallfoundry/taroify#860]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序

### 你正在使用的 Taroify 版本是多少

"^0.4.0-alpha.0"

### 描述一下您遇到的问题以及重现步骤

<img width="369" alt="截屏2024-12-10 22 28 57" src="https://github.com/user-attachments/assets/ca3de3d3-2a8a-4516-b22c-7ff6b47e3127">
<br/>
确定下面会有一个叉号 但是我并没有去写这个叉号 
我的代码是<br/>
<img width="369" alt="截屏2024-12-10 22 28 57" src="https://github.com/user-attachments/assets/f69e07ee-aa26-46d5-b9fb-6c70fce18c58">

### 如果可能的话，请包含一个代码框的链接与复制的问题

https://github.com/eleliauk/muxiK-StackFrontend2.0/blob/main/src/modules/guide/components/Selector.tsx

### 你知道如何解决这个问题吗

Yes

### 您是否愿意参与修复这个问题，并创建一个 PR

Yes

**Comment by Pilotager** [comment]
<img width="631" alt="image" src="https://github.com/user-attachments/assets/37d55498-be1a-44bb-8e69-34afa214326d">

`<Popup.Close />`

**Comment by eleliauk** [comment]
thanks!
