### ISSUE TITLE
dialog打包编译后层级样式问题

### ISSUE THREAD

**Issue by coulis1018** [mallfoundry/taroify#87]
[相关issue](https://github.com/mallfoundry/taroify/issues/72)，Dialog组件目前打包后还是会出现背景板覆盖内容之上

**Comment by coulis1018** [comment]
![9e5ea02ee19e7a6e8e5a05924f866fb](https://user-images.githubusercontent.com/54612727/140881219-b63efe6f-fd20-4944-8a1b-2cdfea19a117.png)

**Comment by tgioer** [comment]
请问你使用的哪个版本？我测试的最新版本好像没有问题。你可以更新到最新版本试试

![image](https://user-images.githubusercontent.com/18252854/140916600-222b074c-e792-4fd4-8d38-af575221c8de.png)

**Comment by coulis1018** [comment]
> 请问你使用的哪个版本？我测试的最新版本好像没有问题。你可以更新到最新版本试试
> 
> ![image](https://user-images.githubusercontent.com/18252854/140916600-222b074c-e792-4fd4-8d38-af575221c8de.png)

现在就是用的最新的0.0.17-alpha.1

**Comment by tgioer** [comment]
我测试的没有问题，你提交个最小的repo，我看看

**Comment by coulis1018** [comment]
> 我测试的没有问题，你提交个复现的repo，我看看

好像是依赖缓存的问题，删除nodemodule后重新install后就好了。
